// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.file.sites
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzRkNDlmYyIgZD0iTTQgMjRoMTZhMiAyIDAgMCAwIDItMlY2Ljc0M2EzIDMgMCAwIDAtLjg3OS0yLjEyMkwxNy4zOC44OEEzIDMgMCAwIDAgMTUuMjU3IDBINGEyIDIgMCAwIDAtMiAydjIwYTIgMiAwIDAgMCAyIDIiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yMiA3di0uMjU3YTMgMyAwIDAgMC0uODc5LTIuMTIyTDE3LjM4Ljg4QTMgMyAwIDAgMCAxNS4yNTcgMGgtLjIzN0ExIDEgMCAwIDEgMTYgMXYzYTIgMiAwIDAgMCAyIDJoM2ExIDEgMCAwIDEgMSAxbS04LjQ4IDExLjc2NWE1IDUgMCAwIDAgMy40NTUtNC4yNjVoLTIuNDg0Yy0uMDYgMS43MzYtLjQyNyAzLjI2My0uOTcxIDQuMjY1TTEyIDIwYTYgNiAwIDEgMCAwLTEyIDYgNiAwIDAgMCAwIDEyTTEwLjQ4IDkuMjM1QTUgNSAwIDAgMCA3LjAyNSAxMy41aDIuNDg0Yy4wNi0xLjczNi40MjctMy4yNjMuOTcxLTQuMjY1bS4wMyA0LjI2NWMuMDQ5LTEuMzQ5LjI5Ny0yLjUyMy42NDUtMy4zNTguMTk2LS40Ny40MDQtLjc4Ni41ODQtLjk2OWEuOC44IDAgMCAxIC4xOTgtLjE1NEMxMS45NzcgOSAxMS45OTUgOSAxMiA5cy4wMjQgMCAuMDYzLjAyYy4wNDMuMDIuMTEuMDY1LjE5OC4xNTMuMTguMTgzLjM4OC40OTguNTg0Ljk2OS4zNDguODM1LjU5NiAyLjAxLjY0NiAzLjM1OHptMCAxYy4wNDkgMS4zNDkuMjk3IDIuNTIzLjY0NSAzLjM1OC4xOTYuNDcuNDA0Ljc4Ni41ODQuOTY5YS44LjggMCAwIDAgLjE5OC4xNTNjLjA0LjAyLjA1OC4wMi4wNjMuMDJzLjAyNCAwIC4wNjMtLjAyYS44LjggMCAwIDAgLjE5OC0uMTUzYy4xOC0uMTgzLjM4OC0uNDk4LjU4NC0uOTY5LjM0OC0uODM1LjU5Ni0yLjAxLjY0Ni0zLjM1OHptLTEuMDAxIDBjLjA2IDEuNzM2LjQyNyAzLjI2My45NzEgNC4yNjVBNSA1IDAgMCAxIDcuMDI1IDE0LjV6bTQuOTgyLTFjLS4wNi0xLjczNi0uNDI3LTMuMjYzLS45NzEtNC4yNjVhNSA1IDAgMCAxIDMuNDU1IDQuMjY1eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11689
 */
export const Icon24FileSites = memo(function Icon24FileSites(props: SVGIconProps) {
  return (
    <ColorTheme brand="seascape">
      <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M4 24h16a2 2 0 0 0 2-2V6.743a3 3 0 0 0-.879-2.122L17.38.88A3 3 0 0 0 15.257 0H4a2 2 0 0 0-2 2v20a2 2 0 0 0 2 2"
        />
        <path
          fill="var(--color-icon-onbrand-tertiary)"
          fillRule="evenodd"
          d="M22 7v-.257a3 3 0 0 0-.879-2.122L17.38.88A3 3 0 0 0 15.257 0h-.237A1 1 0 0 1 16 1v3a2 2 0 0 0 2 2h3a1 1 0 0 1 1 1"
          clipRule="evenodd"
        />
        <path
          fill="var(--color-icon-onbrand)"
          fillRule="evenodd"
          d="M13.52 18.765a5 5 0 0 0 3.455-4.265h-2.484c-.06 1.736-.427 3.263-.971 4.265M12 20a6 6 0 1 0 0-12 6 6 0 0 0 0 12M10.48 9.235A5 5 0 0 0 7.025 13.5h2.484c.06-1.736.427-3.263.971-4.265m.03 4.265c.049-1.349.297-2.523.645-3.358.196-.47.404-.786.584-.969a.8.8 0 0 1 .198-.154C11.977 9 11.995 9 12 9s.024 0 .063.02c.043.02.11.065.198.153.18.183.388.498.584.969.348.835.596 2.01.646 3.358zm0 1c.049 1.349.297 2.523.645 3.358.196.47.404.786.584.969a.8.8 0 0 0 .198.153c.04.02.058.02.063.02s.024 0 .063-.02a.8.8 0 0 0 .198-.153c.18-.183.388-.498.584-.969.348-.835.596-2.01.646-3.358zm-1.001 0c.06 1.736.427 3.263.971 4.265A5 5 0 0 1 7.025 14.5zm4.982-1c-.06-1.736-.427-3.263-.971-4.265a5 5 0 0 1 3.455 4.265z"
          clipRule="evenodd"
        />
      </svg>
    </ColorTheme>
  )
})
