// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.boolean.intersect
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOSA3djJIN1Y3eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyAxMmg1VjdoLTJ2MmExIDEgMCAwIDEtMSAxSDd6bS41LTNIN1Y3aDJ2MnpNNiA5SDRWNGg1djJIN2ExIDEgMCAwIDAtMSAxem0tMSAxSDRhMSAxIDAgMCAxLTEtMVY0YTEgMSAwIDAgMSAxLTFoNWExIDEgMCAwIDEgMSAxdjJoMmExIDEgMCAwIDEgMSAxdjVhMSAxIDAgMCAxLTEgMUg3YTEgMSAwIDAgMS0xLTF2LTJ6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12866
 */
export const Icon16BooleanIntersect = memo(function Icon16BooleanIntersect(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M9 7v2H7V7z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 12h5V7h-2v2a1 1 0 0 1-1 1H7zm.5-3H7V7h2v2zM6 9H4V4h5v2H7a1 1 0 0 0-1 1zm-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v2h2a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-2z"
        clipRule="evenodd"
      />
    </svg>
  )
})
