// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.rewind.template.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCA5YTUgNSAwIDEgMS0xIDMgLjUuNSAwIDAgMC0xIDAgNiA2IDAgMSAwIDEuNS0zLjk2OFY3YS41LjUgMCAxIDAtMSAwdjIuNWEuNS41IDAgMCAwIC41LjVoMi41YS41LjUgMCAxIDAgMC0xem00IDBhLjUuNSAwIDAgMSAuNS41djIuMjkzbDEuMzUzIDEuMzUzYS41LjUgMCAwIDEtLjcwNy43MDhsLTEuNS0xLjVBLjUuNSAwIDAgMSAxMS41IDEyVjkuNUEuNS41IDAgMCAxIDEyIDkiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPjwvc3ZnPg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10754
 */
export const Icon24RewindTemplateSmall = memo(function Icon24RewindTemplateSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 9a5 5 0 1 1-1 3 .5.5 0 0 0-1 0 6 6 0 1 0 1.5-3.968V7a.5.5 0 1 0-1 0v2.5a.5.5 0 0 0 .5.5h2.5a.5.5 0 1 0 0-1zm4 0a.5.5 0 0 1 .5.5v2.293l1.353 1.353a.5.5 0 0 1-.707.708l-1.5-1.5A.5.5 0 0 1 11.5 12V9.5A.5.5 0 0 1 12 9"
        clipRule="evenodd"
      />
    </svg>
  )
})
