// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.actions.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS4yMDcgNS43OTNhMSAxIDAgMCAwLTEuNDE0IDBsLTIgMmExIDEgMCAwIDAgMCAxLjQxNGwyIDJhMSAxIDAgMCAwIDEuNDE0IDBsMi0yYTEgMSAwIDAgMCAwLTEuNDE0ek02LjUgOC41bC43MDcuNzA3LjU4Ni41ODYuNzA3LjcwNy43MDctLjcwNy41ODYtLjU4Ni43MDctLjcwNy0uNzA3LS43MDctLjU4Ni0uNTg2TDguNSA2LjVsLS43MDcuNzA3LS41ODYuNTg2em05IDIuNWEyLjUgMi41IDAgMSAwIDAtNSAyLjUgMi41IDAgMCAwIDAgNU0xNyA4LjVhMS41IDEuNSAwIDEgMS0zIDAgMS41IDEuNSAwIDAgMSAzIDBNMTUuNSAxM2EuNS41IDAgMCAxIC41LjVWMTVoMS41YS41LjUgMCAxIDEgMCAxSDE2djEuNWEuNS41IDAgMSAxLTEgMFYxNmgtMS41YS41LjUgMCAwIDEgMC0xSDE1di0xLjVhLjUuNSAwIDAgMSAuNS0uNW0tNiAwaC0yQTEuNSAxLjUgMCAwIDAgNiAxNC41djJBMS41IDEuNSAwIDAgMCA3LjUgMThoMmExLjUgMS41IDAgMCAwIDEuNS0xLjV2LTJBMS41IDEuNSAwIDAgMCA5LjUgMTNNNyAxNC41YS41LjUgMCAwIDEgLjUtLjVoMmEuNS41IDAgMCAxIC41LjV2MmEuNS41IDAgMCAxLS41LjVoLTJhLjUuNSAwIDAgMS0uNS0uNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2562
 */
export const Icon24ActionsSmall = memo(function Icon24ActionsSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9.207 5.793a1 1 0 0 0-1.414 0l-2 2a1 1 0 0 0 0 1.414l2 2a1 1 0 0 0 1.414 0l2-2a1 1 0 0 0 0-1.414zM6.5 8.5l.707.707.586.586.707.707.707-.707.586-.586.707-.707-.707-.707-.586-.586L8.5 6.5l-.707.707-.586.586zm9 2.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5M17 8.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0M15.5 13a.5.5 0 0 1 .5.5V15h1.5a.5.5 0 1 1 0 1H16v1.5a.5.5 0 1 1-1 0V16h-1.5a.5.5 0 0 1 0-1H15v-1.5a.5.5 0 0 1 .5-.5m-6 0h-2A1.5 1.5 0 0 0 6 14.5v2A1.5 1.5 0 0 0 7.5 18h2a1.5 1.5 0 0 0 1.5-1.5v-2A1.5 1.5 0 0 0 9.5 13M7 14.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
