// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.hidden
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMi4xNTkgNi4wNThjLS4xNC0uMjkyLjEwMy0uNTU4LjQyNy0uNTU4LjM4IDAgLjQzLjA4LjU3MS4zMDdxLjA0Ny4wNzYuMTEzLjE3NWMuMjMyLjMzOC41ODguNzM4IDEuMDUzIDEuMTIxQzUuMjU3IDcuODczIDYuNTQgOC41IDggOC41czIuNzQzLS42MjggMy42NzctMS4zOTdhNS42IDUuNiAwIDAgMCAxLjA1My0xLjEyMWwuMTA5LS4xNjhjLjE0OC0uMjM1LjE5OC0uMzE0LjU3NS0uMzE0LjMyNCAwIC41NjYuMjY2LjQyNy41NTgtLjIzNC40OTEtLjcxOCAxLjEyLTEuMzk3IDEuNzA2bC45NzIgMS40NTlhLjUuNSAwIDEgMS0uODMyLjU1NGwtLjk0LTEuNDFhNy4yIDcuMiAwIDAgMS0xLjU5Ljc4NGwuNDMgMS43MjhhLjUuNSAwIDAgMS0uOTcuMjQybC0uNDI5LTEuNzE4YTYuMiA2LjIgMCAwIDEtMi4xNyAwbC0uNDMgMS43MThhLjUuNSAwIDAgMS0uOTctLjI0MmwuNDMyLTEuNzI4YTcuMiA3LjIgMCAwIDEtMS41OS0uNzg0bC0uOTQxIDEuNDFhLjUuNSAwIDAgMS0uODMyLS41NTRsLjk3Mi0xLjQ1OWMtLjY4LS41ODYtMS4xNjMtMS4yMTUtMS4zOTctMS43MDYiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12251
 */
export const Icon16Hidden = memo(function Icon16Hidden(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M2.159 6.058c-.14-.292.103-.558.427-.558.38 0 .43.08.571.307q.047.076.113.175c.232.338.588.738 1.053 1.121C5.257 7.873 6.54 8.5 8 8.5s2.743-.628 3.677-1.397a5.6 5.6 0 0 0 1.053-1.121l.109-.168c.148-.235.198-.314.575-.314.324 0 .566.266.427.558-.234.491-.718 1.12-1.397 1.706l.972 1.459a.5.5 0 1 1-.832.554l-.94-1.41a7.2 7.2 0 0 1-1.59.784l.43 1.728a.5.5 0 0 1-.97.242l-.429-1.718a6.2 6.2 0 0 1-2.17 0l-.43 1.718a.5.5 0 0 1-.97-.242l.432-1.728a7.2 7.2 0 0 1-1.59-.784l-.941 1.41a.5.5 0 0 1-.832-.554l.972-1.459c-.68-.586-1.163-1.215-1.397-1.706"
        clipRule="evenodd"
      />
    </svg>
  )
})
