// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.cms.repeater.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEuNSA2aDVhLjUuNSAwIDAgMSAuNS41VjloLTZWNi41YS41LjUgMCAwIDEgLjUtLjVNMTAgMTBWNi41QTEuNSAxLjUgMCAwIDEgMTEuNSA1aDVBMS41IDEuNSAwIDAgMSAxOCA2LjV2MTBhMS41IDEuNSAwIDAgMS0xLjUgMS41aC01YTEuNSAxLjUgMCAwIDEtMS41LTEuNXptMSA2LjVWMTRoNnYyLjVhLjUuNSAwIDAgMS0uNS41aC01YS41LjUgMCAwIDEtLjUtLjVtNi0zLjVoLTZ2LTNoNnpNOCA3LjVhLjUuNSAwIDEgMS0xIDAgLjUuNSAwIDAgMSAxIDBtMSAwYTEuNSAxLjUgMCAxIDEtMyAwIDEuNSAxLjUgMCAwIDEgMyAwTTcuNSAxMmEuNS41IDAgMSAwIDAtMSAuNS41IDAgMCAwIDAgMW0wIDFhMS41IDEuNSAwIDEgMCAwLTMgMS41IDEuNSAwIDAgMCAwIDNtLjUgMi41YS41LjUgMCAxIDEtMSAwIC41LjUgMCAwIDEgMSAwbTEgMGExLjUgMS41IDAgMSAxLTMgMCAxLjUgMS41IDAgMCAxIDMgMCIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1982-29905
 */
export const Icon24CmsRepeaterSmall = memo(function Icon24CmsRepeaterSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.5 6h5a.5.5 0 0 1 .5.5V9h-6V6.5a.5.5 0 0 1 .5-.5M10 10V6.5A1.5 1.5 0 0 1 11.5 5h5A1.5 1.5 0 0 1 18 6.5v10a1.5 1.5 0 0 1-1.5 1.5h-5a1.5 1.5 0 0 1-1.5-1.5zm1 6.5V14h6v2.5a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5m6-3.5h-6v-3h6zM8 7.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m1 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0M7.5 12a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m0 1a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m.5 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m1 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
