// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.lock.open
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOSA3YTMgMyAwIDEgMSA2IDB2LjVhLjUuNSAwIDAgMCAxIDBWN2E0IDQgMCAwIDAtOCAwdjNoLS4xMjVDNi44MzkgMTAgNiAxMC44NCA2IDExLjg3NXY1LjI1QzYgMTguMTYgNi44NCAxOSA3Ljg3NSAxOWg4LjI1QzE3LjE2IDE5IDE4IDE4LjE2IDE4IDE3LjEyNXYtNS4yNUMxOCAxMC44MzkgMTcuMTYgMTAgMTYuMTI1IDEwSDl6bS0yIDQuODc1YzAtLjQ4My4zOTItLjg3NS44NzUtLjg3NWg4LjI1Yy40ODMgMCAuODc1LjM5Mi44NzUuODc1djUuMjVhLjg3NS44NzUgMCAwIDEtLjg3NS44NzVoLTguMjVBLjg3NS44NzUgMCAwIDEgNyAxNy4xMjV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1464
 */
export const Icon24LockOpen = memo(function Icon24LockOpen(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9 7a3 3 0 1 1 6 0v.5a.5.5 0 0 0 1 0V7a4 4 0 0 0-8 0v3h-.125C6.839 10 6 10.84 6 11.875v5.25C6 18.16 6.84 19 7.875 19h8.25C17.16 19 18 18.16 18 17.125v-5.25C18 10.839 17.16 10 16.125 10H9zm-2 4.875c0-.483.392-.875.875-.875h8.25c.483 0 .875.392.875.875v5.25a.875.875 0 0 1-.875.875h-8.25A.875.875 0 0 1 7 17.125z"
        clipRule="evenodd"
      />
    </svg>
  )
})
