// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.section.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTMgN2gzYTEgMSAwIDAgMSAxIDF2OGExIDEgMCAwIDEtMSAxSDhhMSAxIDAgMCAxLTEtMXYtNmg1LjI1YS43NS43NSAwIDAgMCAuNzUtLjc1em0tMSAwSDhhMSAxIDAgMCAwLTEgMXYxaDV6bS4yNS0xSDE2YTIgMiAwIDAgMSAyIDJ2OGEyIDIgMCAwIDEtMiAySDhhMiAyIDAgMCAxLTItMlY4cTAtLjEwNC4wMS0uMjA0QTIgMiAwIDAgMSA4IDZ6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3020
 */
export const Icon24SectionSmall = memo(function Icon24SectionSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M13 7h3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1v-6h5.25a.75.75 0 0 0 .75-.75zm-1 0H8a1 1 0 0 0-1 1v1h5zm.25-1H16a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8q0-.104.01-.204A2 2 0 0 1 8 6z"
        clipRule="evenodd"
      />
    </svg>
  )
})
