// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.warning
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTAuMjczIDQuOTc3LTcuMDEgMTIuMDE1QzIuNDg3IDE4LjMyNSAzLjQ0OSAyMCA0Ljk5MiAyMEgxOS4wMWMxLjU0NCAwIDIuNTA1LTEuNjc1IDEuNzI4LTMuMDA4bC03LjAxLTEyLjAxNWMtLjc3MS0xLjMyMy0yLjY4My0xLjMyMy0zLjQ1NCAwTTQuMTI3IDE3LjQ5Nmw3LjAxLTEyLjAxNWExIDEgMCAwIDEgMS43MjcgMGw3LjAwOSAxMi4wMTVBMSAxIDAgMCAxIDE5LjAwOSAxOUg0Ljk5MWExIDEgMCAwIDEtLjg2NC0xLjUwNE0xMiA4LjVhLjUuNSAwIDAgMSAuNS41djQuNWEuNS41IDAgMCAxLTEgMFY5YS41LjUgMCAwIDEgLjUtLjVtMSA3LjVhMSAxIDAgMSAxLTIgMCAxIDEgMCAwIDEgMiAwIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=875-5676
 */
export const Icon24Warning = memo(function Icon24Warning(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m10.273 4.977-7.01 12.015C2.487 18.325 3.449 20 4.992 20H19.01c1.544 0 2.505-1.675 1.728-3.008l-7.01-12.015c-.771-1.323-2.683-1.323-3.454 0M4.127 17.496l7.01-12.015a1 1 0 0 1 1.727 0l7.009 12.015A1 1 0 0 1 19.009 19H4.991a1 1 0 0 1-.864-1.504M12 8.5a.5.5 0 0 1 .5.5v4.5a.5.5 0 0 1-1 0V9a.5.5 0 0 1 .5-.5m1 7.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
