// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.sound.off
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS45OTMgMy44ODVhMSAxIDAgMCAwLTEuNy0uNTkzbC0xIDFMNi41ODYgNUg1LjVBMS41IDEuNSAwIDAgMCA0IDYuNXYzcTAgLjE3NS4wMzkuMzRsLjM0LS4zNEw1IDguODc4VjYuNWEuNS41IDAgMCAxIC41LS41SDdsLjI5My0uMjkzTDggNWwuMTIxLS4xMjIuNDQtLjQzOS40MzktLjQ0di44OGwuNDQtLjQ0LjQzOS0uNDR6TTEwIDguMTIxbC0xIDFWMTJsLS43MzItLjczMkw4IDExbC0uNDQtLjQzOS0uNzA2LjcwNy40MzkuNDQuMjY4LjI2OC43MzIuNzMyQTEgMSAwIDAgMCAxMCAxMS45OTl6bTIuODU0LTQuMjY4YS41LjUgMCAwIDAtLjcwOC0uNzA3bC05IDlhLjUuNSAwIDEgMCAuNzA4LjcwN3oiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13401
 */
export const Icon16SoundOff = memo(function Icon16SoundOff(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9.993 3.885a1 1 0 0 0-1.7-.593l-1 1L6.586 5H5.5A1.5 1.5 0 0 0 4 6.5v3q0 .175.039.34l.34-.34L5 8.878V6.5a.5.5 0 0 1 .5-.5H7l.293-.293L8 5l.121-.122.44-.439.439-.44v.88l.44-.44.439-.44zM10 8.121l-1 1V12l-.732-.732L8 11l-.44-.439-.706.707.439.44.268.268.732.732A1 1 0 0 0 10 11.999zm2.854-4.268a.5.5 0 0 0-.708-.707l-9 9a.5.5 0 1 0 .708.707z"
        clipRule="evenodd"
      />
    </svg>
  )
})
