// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.right-arrow.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyIDYuNDg0YzAtMS4wMDIgMS4xMzYtMS41MzYgMS45MDEtLjk3NmwuMTQ4LjEyNyA1LjQ4MSA1LjQ4MmExLjI1IDEuMjUgMCAwIDEgLjAwMSAxLjc2NnYuMDAxbC01LjQ4MiA1LjQ4My0uMTQ4LjEyN2MtLjcxNC41MjMtMS43NS4wOTEtMS44ODYtLjc4MkwxMiAxNy41MTh2LTIuNTE3SDYuMjVhMS4yNSAxLjI1IDAgMCAxLTEuMjQzLTEuMTIyTDUgMTMuNzV2LTMuNWMwLS42NDYuNDkxLTEuMTggMS4xMjItMS4yNDRsLjEyOC0uMDA1SDEyem0xLjM0Mi0uMTQyYS4yLjIgMCAwIDAtLjMzMi4wOGwtLjAxLjA2MlYxMEg2LjI1bC0uMDUuMDA0YS4yNS4yNSAwIDAgMC0uMi4yNDV2My41YS4yNS4yNSAwIDAgMCAuMi4yNDVsLjA1LjAwNkgxM3YzLjUxN2EuMi4yIDAgMCAwIC4zNDIuMTQybDUuNDgxLTUuNDgzYS4yNS4yNSAwIDAgMCAwLS4zNTN6Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-8008
 */
export const Icon24ShapeRightArrowSmall = memo(function Icon24ShapeRightArrowSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12 6.484c0-1.002 1.136-1.536 1.901-.976l.148.127 5.481 5.482a1.25 1.25 0 0 1 .001 1.766v.001l-5.482 5.483-.148.127c-.714.523-1.75.091-1.886-.782L12 17.518v-2.517H6.25a1.25 1.25 0 0 1-1.243-1.122L5 13.75v-3.5c0-.646.491-1.18 1.122-1.244l.128-.005H12zm1.342-.142a.2.2 0 0 0-.332.08l-.01.062V10H6.25l-.05.004a.25.25 0 0 0-.2.245v3.5a.25.25 0 0 0 .2.245l.05.006H13v3.517a.2.2 0 0 0 .342.142l5.481-5.483a.25.25 0 0 0 0-.353z"
      />
    </svg>
  )
})
