// This file was auto-generated by fpl/foundations/figma-import

import { memo } from "react";

import type { SVGIconProps } from "./support/icon-types";

/**
 * icon.16.frame
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNS41IDNhLjUuNSAwIDAgMSAuNS41VjVoNFYzLjVhLjUuNSAwIDAgMSAxIDBWNWgxLjVhLjUuNSAwIDAgMSAwIDFIMTF2NGgxLjVhLjUuNSAwIDAgMSAwIDFIMTF2MS41YS41LjUgMCAwIDEtMSAwVjExSDZ2MS41YS41LjUgMCAwIDEtMSAwVjExSDMuNWEuNS41IDAgMCAxIDAtMUg1VjZIMy41YS41LjUgMCAwIDEgMC0xSDVWMy41YS41LjUgMCAwIDEgLjUtLjVtNC41IDdWNkg2djR6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12135
 */
export const Icon16Frame = memo(function Icon16Frame(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5.5 3a.5.5 0 0 1 .5.5V5h4V3.5a.5.5 0 0 1 1 0V5h1.5a.5.5 0 0 1 0 1H11v4h1.5a.5.5 0 0 1 0 1H11v1.5a.5.5 0 0 1-1 0V11H6v1.5a.5.5 0 0 1-1 0V11H3.5a.5.5 0 0 1 0-1H5V6H3.5a.5.5 0 0 1 0-1H5V3.5a.5.5 0 0 1 .5-.5m4.5 7V6H6v4z"
        clipRule="evenodd"
      />
    </svg>
  );
});
