// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.interaction.default.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTggMTJhNiA2IDAgMCAxLTkuODc0IDQuNTgxbDguNDU1LTguNDU1QTUuOTggNS45OCAwIDAgMSAxOCAxMk03LjQxOCAxNS44NzRsOC40NTYtOC40NTZhNiA2IDAgMCAwLTguNDU2IDguNDU2TTE5IDEyYTcgNyAwIDEgMS0xNCAwIDcgNyAwIDAgMSAxNCAwIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-9691
 */
export const Icon24InteractionDefaultSmall = memo(function Icon24InteractionDefaultSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M18 12a6 6 0 0 1-9.874 4.581l8.455-8.455A5.98 5.98 0 0 1 18 12M7.418 15.874l8.456-8.456a6 6 0 0 0-8.456 8.456M19 12a7 7 0 1 1-14 0 7 7 0 0 1 14 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
