// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.tint
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtOCAzIC43MzQtLjY4YTEgMSAwIDAgMC0xLjQ2OCAwem0zLjYwNCA2Yy0uMjU3LTEuNzc4LTEuOTc3LTQuMDY4LTIuOTQ1LTUuMjM4QzguMjY4IDMuMjkgNy45OTkgMyA3Ljk5OSAzbC43MzUtLjY3OS4wMDEuMDAxLjAwMy4wMDMuMDEuMDEuMDMzLjAzOC4xMjQuMTM4YTI2IDI2IDAgMCAxIDEuNzMyIDIuMTkxYy40NzIuNjc0Ljk2IDEuNDUgMS4zMzUgMi4yNC4zNjYuNzcyLjY2NCAxLjY0NC42NjQgMi40ODdDMTIuNjM2IDExLjk3IDEwLjU0MyAxNCA4IDE0cy00LjYzNy0yLjAzLTQuNjM3LTQuNTcxYzAtLjg0My4yOTktMS43MTUuNjY1LTIuNDg4LjM3NC0uNzg5Ljg2Mi0xLjU2NSAxLjMzNS0yLjIzOWEyNiAyNiAwIDAgMSAxLjg1NS0yLjMyOWwuMDM0LS4wMzcuMDEtLjAxLjAwMi0uMDA0aC4wMDFWMi4zMkw4IDNzLS4yNjkuMjktLjY2Ljc2MkM2LjM3NCA0LjkzMiA0LjY1MyA3LjIyMiA0LjM5NyA5em0tLjAxNCAxSDQuNDFjLjI3OCAxLjcgMS43OCAzIDMuNTkgM3MzLjMxMS0xLjMgMy41OS0zIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13590
 */
export const Icon16Tint = memo(function Icon16Tint(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m8 3 .734-.68a1 1 0 0 0-1.468 0zm3.604 6c-.257-1.778-1.977-4.068-2.945-5.238C8.268 3.29 7.999 3 7.999 3l.735-.679.001.001.003.003.01.01.033.038.124.138a26 26 0 0 1 1.732 2.191c.472.674.96 1.45 1.335 2.24.366.772.664 1.644.664 2.487C12.636 11.97 10.543 14 8 14s-4.637-2.03-4.637-4.571c0-.843.299-1.715.665-2.488.374-.789.862-1.565 1.335-2.239a26 26 0 0 1 1.855-2.329l.034-.037.01-.01.002-.004h.001V2.32L8 3s-.269.29-.66.762C6.374 4.932 4.653 7.222 4.397 9zm-.014 1H4.41c.278 1.7 1.78 3 3.59 3s3.311-1.3 3.59-3"
        clipRule="evenodd"
      />
    </svg>
  )
})
