// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.auto.rename
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCAzLjVhLjUuNSAwIDAgMSAuNS0uNWgyYS41LjUgMCAxIDEgMCAxSDEwdjhoLjVhLjUuNSAwIDEgMSAwIDFoLTJhLjUuNSAwIDAgMSAwLTFIOVY0aC0uNWEuNS41IDAgMCAxLS41LS41bTMgMmEuNS41IDAgMCAxIC41LS41aDFBMS41IDEuNSAwIDAgMSAxNCA2LjV2M2ExLjUgMS41IDAgMCAxLTEuNSAxLjVoLTFhLjUuNSAwIDAgMSAwLTFoMWEuNS41IDAgMCAwIC41LS41di0zYS41LjUgMCAwIDAtLjUtLjVoLTFhLjUuNSAwIDAgMS0uNS0uNU0yLjUgN2EuNS41IDAgMCAxIC41LjV2MmEuNS41IDAgMCAwIC41LjVoNGEuNS41IDAgMSAxIDAgMWgtNEExLjUgMS41IDAgMCAxIDIgOS41di0yYS41LjUgMCAwIDEgLjUtLjVtMi41MTUtMy41Nkw0LjcgNC43bC0xLjI2LjMxNWMtLjUwNS4xMjYtLjUwNS44NDQgMCAuOTdMNC43IDYuM2wuMzE1IDEuMjZjLjEyNi41MDUuODQ0LjUwNS45NyAwTDYuMyA2LjNsMS4yNi0uMzE1Yy41MDUtLjEyNi41MDUtLjg0NCAwLS45N0w2LjMgNC43bC0uMzE1LTEuMjZjLS4xMjYtLjUwNS0uODQ0LS41MDUtLjk3IDAiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13222
 */
export const Icon16AutoRename = memo(function Icon16AutoRename(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 3.5a.5.5 0 0 1 .5-.5h2a.5.5 0 1 1 0 1H10v8h.5a.5.5 0 1 1 0 1h-2a.5.5 0 0 1 0-1H9V4h-.5a.5.5 0 0 1-.5-.5m3 2a.5.5 0 0 1 .5-.5h1A1.5 1.5 0 0 1 14 6.5v3a1.5 1.5 0 0 1-1.5 1.5h-1a.5.5 0 0 1 0-1h1a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 1-.5-.5M2.5 7a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 .5.5h4a.5.5 0 1 1 0 1h-4A1.5 1.5 0 0 1 2 9.5v-2a.5.5 0 0 1 .5-.5m2.515-3.56L4.7 4.7l-1.26.315c-.505.126-.505.844 0 .97L4.7 6.3l.315 1.26c.126.505.844.505.97 0L6.3 6.3l1.26-.315c.505-.126.505-.844 0-.97L6.3 4.7l-.315-1.26c-.126-.505-.844-.505-.97 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
