// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.file.design
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzBkOTlmZiIgZD0iTTQgMjRoMTZhMiAyIDAgMCAwIDItMlY2Ljc0M2EzIDMgMCAwIDAtLjg3OS0yLjEyMkwxNy4zOC44OEEzIDMgMCAwIDAgMTUuMjU3IDBINGEyIDIgMCAwIDAtMiAydjIwYTIgMiAwIDAgMCAyIDIiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yMiA3di0uMjU3YTMgMyAwIDAgMC0uODc5LTIuMTIyTDE3LjM4Ljg4QTMgMyAwIDAgMCAxNS4yNTcgMGgtLjIzN0ExIDEgMCAwIDEgMTYgMXYzYTIgMiAwIDAgMCAyIDJoM2ExIDEgMCAwIDEgMSAxIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBkPSJNNy4zOSA4LjIwOGMuMjM2LS4xODIuNTQ1LS4yNS44NC0uMTgybDUuMDU4IDEuMTkuMjI2LjA2YTQuODcgNC44NyAwIDAgMSAzLjUyMiA0Ljg0NmwuNjcyLjY3MmExIDEgMCAwIDEgMCAxLjQxNGwtMy41IDMuNWExIDEgMCAwIDEtMS40MTQgMGwtLjY3My0uNjczYTQuODcgNC44NyAwIDAgMS00Ljg0NS0zLjUybC0uMDYtLjIyNy0xLjE5LTUuMDU3YTEgMSAwIDAgMSAuMjY3LS45MzdsMS0xek03IDEwLjAwMWwxLjE5IDUuMDU4QTMuODY3IDMuODY3IDAgMCAwIDEyLjUgMThsMSAxLjAwMSAzLjUtMy41LTEtMWEzLjg3IDMuODcgMCAwIDAtMi45NDEtNC4zMUw3Ljk5OSA5em0zLjk4NiAyLjI3N2EyIDIgMCAxIDEtLjcwNy43MDdsLTMuMTMyLTMuMTMuNzA3LS43MDd6bTEuMDE1LjcyMmExIDEgMCAxIDAgMCAyIDEgMSAwIDAgMCAwLTIiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11533
 */
export const Icon24FileDesign = memo(function Icon24FileDesign(props: SVGIconProps) {
  return (
    <ColorTheme brand="design">
      <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M4 24h16a2 2 0 0 0 2-2V6.743a3 3 0 0 0-.879-2.122L17.38.88A3 3 0 0 0 15.257 0H4a2 2 0 0 0-2 2v20a2 2 0 0 0 2 2"
        />
        <path
          fill="var(--color-icon-onbrand-tertiary)"
          fillRule="evenodd"
          d="M22 7v-.257a3 3 0 0 0-.879-2.122L17.38.88A3 3 0 0 0 15.257 0h-.237A1 1 0 0 1 16 1v3a2 2 0 0 0 2 2h3a1 1 0 0 1 1 1"
          clipRule="evenodd"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M7.39 8.208c.236-.182.545-.25.84-.182l5.058 1.19.226.06a4.87 4.87 0 0 1 3.522 4.846l.672.672a1 1 0 0 1 0 1.414l-3.5 3.5a1 1 0 0 1-1.414 0l-.673-.673a4.87 4.87 0 0 1-4.845-3.52l-.06-.227-1.19-5.057a1 1 0 0 1 .267-.937l1-1zM7 10.001l1.19 5.058A3.867 3.867 0 0 0 12.5 18l1 1.001 3.5-3.5-1-1a3.87 3.87 0 0 0-2.941-4.31L7.999 9zm3.986 2.277a2 2 0 1 1-.707.707l-3.132-3.13.707-.707zm1.015.722a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
        />
      </svg>
    </ColorTheme>
  )
})
