// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.devmode.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzE0YWU1YyIgZD0iTTAgNWE1IDUgMCAwIDEgNS01aDE0YTUgNSAwIDAgMSA1IDV2MTRhNSA1IDAgMCAxLTUgNUg1YTUgNSAwIDAgMS01LTV6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEzLjYzMSA2LjAxOGEuNS41IDAgMCAxIC4zNjcuNTEzbC0uMDE2LjEtMyAxMS0uMDM2LjA5NWEuNTAxLjUwMSAwIDAgMS0uOTMtLjM1OGwzLTExIC4wMzctLjA5NWEuNS41IDAgMCAxIC41NzgtLjI1NU04LjIyNCA4LjU4MmEuNTAxLjUwMSAwIDAgMSAuNjkzLjY5M2wtLjA2NC4wNzhMNi4yMDYgMTJsMi42NDcgMi42NDZhLjUuNSAwIDAgMS0uNzA3LjcwN2wtMy0zYS41LjUgMCAwIDEgMC0uNzA3bDMtM3ptNi45MjIuMDY0YS41LjUgMCAwIDEgLjcwNyAwbDMgM2EuNS41IDAgMCAxIDAgLjcwN2wtMyAzLS4wNzguMDY1YS41LjUgMCAwIDEtLjY5NC0uNjkzbC4wNjUtLjA3OUwxNy43OTIgMTJsLTIuNjQ2LTIuNjQ3YS41LjUgMCAwIDEgMC0uNzA3Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=7584-9527
 */
export const Icon24DevmodeFavicon = memo(function Icon24DevmodeFavicon(props: SVGIconProps) {
  return (
    <ColorTheme brand="dev-handoff">
      <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 5a5 5 0 0 1 5-5h14a5 5 0 0 1 5 5v14a5 5 0 0 1-5 5H5a5 5 0 0 1-5-5z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M13.631 6.018a.5.5 0 0 1 .367.513l-.016.1-3 11-.036.095a.501.501 0 0 1-.93-.358l3-11 .037-.095a.5.5 0 0 1 .578-.255M8.224 8.582a.501.501 0 0 1 .693.693l-.064.078L6.206 12l2.647 2.646a.5.5 0 0 1-.707.707l-3-3a.5.5 0 0 1 0-.707l3-3zm6.922.064a.5.5 0 0 1 .707 0l3 3a.5.5 0 0 1 0 .707l-3 3-.078.065a.5.5 0 0 1-.694-.693l.065-.079L17.792 12l-2.646-2.647a.5.5 0 0 1 0-.707"
        />
      </svg>
    </ColorTheme>
  )
})
