// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.summing-junction.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTcuMDUgNy4wNWE3IDcgMCAxIDEgOS45IDkuOSA3IDcgMCAwIDEtOS45LTkuOW0xLjA3NyA5LjUzYTUuOTk2IDUuOTk2IDAgMCAwIDcuNzQ1IDBMMTIgMTIuNzA2ek03LjQyIDguMTI3YTYgNiAwIDAgMCAwIDcuNzQ2TDExLjI5MyAxMnpNMTIuNzA3IDEybDMuODcyIDMuODcyYTUuOTk2IDUuOTk2IDAgMCAwIC4wMDEtNy43NDV6bTMuMTY2LTQuNThhNiA2IDAgMCAwLTcuNzQ2IDBMMTIgMTEuMjkzeiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7920
 */
export const Icon24ShapeSummingJunctionSmall = memo(function Icon24ShapeSummingJunctionSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M7.05 7.05a7 7 0 1 1 9.9 9.9 7 7 0 0 1-9.9-9.9m1.077 9.53a5.996 5.996 0 0 0 7.745 0L12 12.706zM7.42 8.127a6 6 0 0 0 0 7.746L11.293 12zM12.707 12l3.872 3.872a5.996 5.996 0 0 0 .001-7.745zm3.166-4.58a6 6 0 0 0-7.746 0L12 11.293z"
      />
    </svg>
  )
})
