// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.32.community.new.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDMyIDMyIj4KICA8cmVjdCB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzFlMWUxZSIgZD0iTTAgNWE1IDUgMCAwIDEgNS01aDIyYTUgNSAwIDAgMSA1IDV2MjJhNSA1IDAgMCAxLTUgNUg1YTUgNSAwIDAgMS01LTV6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTIyLjMyIDEzLjI0NGMuNzk3LS4yOTYgMS42OC4yOSAxLjY4MSAxLjE3NHY1LjI4NWMwIC42NzYtLjM3MyAxLjI5Ny0uOTY5IDEuNjE1bC02Ljc5NiAzLjYyNGEuNS41IDAgMCAxLS40MTQuMDI3bC0uMDU2LS4wMjctNi43OTYtMy42MjRBMS44MyAxLjgzIDAgMCAxIDggMTkuNzAzdi01LjI4NWExLjI1IDEuMjUgMCAwIDEgMS44MzgtMS4xMDNMMTYgMTYuNmw2LjE2Mi0zLjI4NnptLTEyLjk1Mi45NTNhLjI1LjI1IDAgMCAwLS4zNjcuMjIxdjUuMjg1YS44My44MyAwIDAgMCAuNDQuNzMzbDYuMDYgMy4yMzJ2LTYuMnptMTMuNjMzLjIyMWEuMjUuMjUgMCAwIDAtLjM2Ny0uMjJsLTYuMTMzIDMuMjd2Ni4ybDYuMDYtMy4yMzJhLjgzLjgzIDAgMCAwIC40NC0uNzMzem0tNy03LjQxOGEzLjUgMy41IDAgMSAxLS4wMDIgNy4wMDJBMy41IDMuNSAwIDAgMSAxNi4wMDEgN20wIDFhMi41IDIuNSAwIDEgMCAwIDUgMi41IDIuNSAwIDAgMCAwLTUiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=7584-16706
 */
export const Icon32CommunityNewFavicon = memo(function Icon32CommunityNewFavicon(
  props: SVGIconProps,
) {
  return (
    <svg width="32" height="32" fill="none" viewBox="0 0 32 32" {...props}>
      <path
        fill="var(--color-bg-menu)"
        d="M0 5a5 5 0 0 1 5-5h22a5 5 0 0 1 5 5v22a5 5 0 0 1-5 5H5a5 5 0 0 1-5-5z"
      />
      <path
        fill="var(--color-icon-onbrand)"
        d="M22.32 13.244c.797-.296 1.68.29 1.681 1.174v5.285c0 .676-.373 1.297-.969 1.615l-6.796 3.624a.5.5 0 0 1-.414.027l-.056-.027-6.796-3.624A1.83 1.83 0 0 1 8 19.703v-5.285a1.25 1.25 0 0 1 1.838-1.103L16 16.6l6.162-3.286zm-12.952.953a.25.25 0 0 0-.367.221v5.285a.83.83 0 0 0 .44.733l6.06 3.232v-6.2zm13.633.221a.25.25 0 0 0-.367-.22l-6.133 3.27v6.2l6.06-3.232a.83.83 0 0 0 .44-.733zm-7-7.418a3.5 3.5 0 1 1-.002 7.002A3.5 3.5 0 0 1 16.001 7m0 1a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5"
      />
    </svg>
  )
})
