// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.exposure
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC41IDIuMjVhLjUuNSAwIDEgMC0xIDB2MS4yNzhhNC41IDQuNSAwIDAgMC0yLjMwOC45NTVsLS45MDQtLjkwM2EuNS41IDAgMSAwLS43MDcuNzA3bC45MDQuOTAzYTQuNSA0LjUgMCAwIDAtLjk1NyAyLjMxSDIuMjVhLjUuNSAwIDEgMCAwIDFoMS4yNzdjLjA5Ni44NjguNDM5IDEuNjYyLjk1NyAyLjMxbC0uOTAzLjkwMmEuNS41IDAgMCAwIC43MDcuNzA3bC45MDMtLjkwMmE0LjUgNC41IDAgMCAwIDIuMzA4Ljk1N3YxLjI3NGEuNS41IDAgMSAwIDEgMHYtMS4yNzRhNC41IDQuNSAwIDAgMCAyLjMxLS45NTdsLjkuOTAxYS41LjUgMCAxIDAgLjcwNy0uNzA3bC0uOS0uOWE0LjUgNC41IDAgMCAwIC45NTctMi4zMTFoMS4yNzRhLjUuNSAwIDEgMCAwLTFoLTEuMjc1YTQuNSA0LjUgMCAwIDAtLjk1OC0yLjMxbC45MDItLjkwMmEuNS41IDAgMSAwLS43MDctLjcwN2wtLjkwMi45MDNhNC41IDQuNSAwIDAgMC0yLjMwOC0uOTU2em0tMSAyLjI4NWEzLjUgMy41IDAgMCAwIDAgNi45M3ptMSA2LjkzYTMuNSAzLjUgMCAwIDAgMC02LjkzeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13536
 */
export const Icon16Exposure = memo(function Icon16Exposure(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8.5 2.25a.5.5 0 1 0-1 0v1.278a4.5 4.5 0 0 0-2.308.955l-.904-.903a.5.5 0 1 0-.707.707l.904.903a4.5 4.5 0 0 0-.957 2.31H2.25a.5.5 0 1 0 0 1h1.277c.096.868.439 1.662.957 2.31l-.903.902a.5.5 0 0 0 .707.707l.903-.902a4.5 4.5 0 0 0 2.308.957v1.274a.5.5 0 1 0 1 0v-1.274a4.5 4.5 0 0 0 2.31-.957l.9.901a.5.5 0 1 0 .707-.707l-.9-.9a4.5 4.5 0 0 0 .957-2.311h1.274a.5.5 0 1 0 0-1h-1.275a4.5 4.5 0 0 0-.958-2.31l.902-.902a.5.5 0 1 0-.707-.707l-.902.903a4.5 4.5 0 0 0-2.308-.956zm-1 2.285a3.5 3.5 0 0 0 0 6.93zm1 6.93a3.5 3.5 0 0 0 0-6.93z"
        clipRule="evenodd"
      />
    </svg>
  )
})
