// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.polygon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCAzYTEgMSAwIDAgMSAuODcyLjUxbDQuNSA4QTEgMSAwIDAgMSAxMi41IDEzaC05YTEgMSAwIDAgMS0uODcyLTEuNDlsNC41LThBMSAxIDAgMCAxIDggM20wIDEtLjU3NCAxLjAyTDQuMDYyIDExIDMuNSAxMmg5bC0uNTYyLTEtMy4zNjQtNS45OHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12741
 */
export const Icon16Polygon = memo(function Icon16Polygon(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 3a1 1 0 0 1 .872.51l4.5 8A1 1 0 0 1 12.5 13h-9a1 1 0 0 1-.872-1.49l4.5-8A1 1 0 0 1 8 3m0 1-.574 1.02L4.062 11 3.5 12h9l-.562-1-3.364-5.98z"
        clipRule="evenodd"
      />
    </svg>
  )
})
