// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.16.list-view
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTQgMTFhMSAxIDAgMSAxIDAgMiAxIDEgMCAwIDEgMC0ybTguNi41MWEuNS41IDAgMCAxIDAgLjk4bC0uMS4wMWgtNWEuNS41IDAgMCAxIDAtMWg1ek00IDdhMSAxIDAgMSAxIDAgMiAxIDEgMCAwIDEgMC0ybTguNi41MWEuNS41IDAgMCAxIDAgLjk4bC0uMS4wMWgtNWEuNS41IDAgMCAxIDAtMWg1ek00IDNhMSAxIDAgMSAxIDAgMiAxIDEgMCAwIDEgMC0ybTguNi41MWEuNS41IDAgMCAxIDAgLjk4bC0uMS4wMWgtNWEuNS41IDAgMCAxIDAtMWg1eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=4198-8154
 */
export const Icon16ListView = memo(function Icon16ListView(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M4 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2m8.6.51a.5.5 0 0 1 0 .98l-.1.01h-5a.5.5 0 0 1 0-1h5zM4 7a1 1 0 1 1 0 2 1 1 0 0 1 0-2m8.6.51a.5.5 0 0 1 0 .98l-.1.01h-5a.5.5 0 0 1 0-1h5zM4 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2m8.6.51a.5.5 0 0 1 0 .98l-.1.01h-5a.5.5 0 0 1 0-1h5z"
      />
    </svg>
  ) : (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M4 10.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2m8.5.5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM4 6.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2m8.5.5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM4 2.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2m8.5.5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1z"
      />
    </svg>
  )

  return icon
})
