// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-align-right-group
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTguNSAxOGEuNS41IDAgMCAxLS41LS41di0xMmEuNS41IDAgMCAxIDEgMHYxMmEuNS41IDAgMCAxLS41LjVNNiA5LjI1YzAgLjQxNC4zMzYuNzUuNzUuNzVoOC41YS43NS43NSAwIDAgMCAuNzUtLjc1di0uNWEuNzUuNzUgMCAwIDAtLjc1LS43NWgtOC41YS43NS43NSAwIDAgMC0uNzUuNzV6bTQgNWMwIC40MTQuMzM2Ljc1Ljc1Ljc1aDQuNWEuNzUuNzUgMCAwIDAgLjc1LS43NXYtLjVhLjc1Ljc1IDAgMCAwLS43NS0uNzVoLTQuNWEuNzUuNzUgMCAwIDAtLjc1Ljc1eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTYgMTcuNWEuNS41IDAgMCAxLS41LjVINS4yNUM0LjU2IDE4IDQgMTcuNDQgNCAxNi43NVY2LjI1QzQgNS41NiA0LjU2IDUgNS4yNSA1SDE1LjVhLjUuNSAwIDAgMSAwIDFINS4yNWEuMjUuMjUgMCAwIDAtLjI1LjI1djEwLjVjMCAuMTM4LjExMi4yNS4yNS4yNUgxNS41YS41LjUgMCAwIDEgLjUuNSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7037
 */
export const Icon24LayoutAlignRightGroup = memo(function Icon24LayoutAlignRightGroup(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M18.5 18a.5.5 0 0 1-.5-.5v-12a.5.5 0 0 1 1 0v12a.5.5 0 0 1-.5.5M6 9.25c0 .414.336.75.75.75h8.5a.75.75 0 0 0 .75-.75v-.5a.75.75 0 0 0-.75-.75h-8.5a.75.75 0 0 0-.75.75zm4 5c0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75v-.5a.75.75 0 0 0-.75-.75h-4.5a.75.75 0 0 0-.75.75z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M16 17.5a.5.5 0 0 1-.5.5H5.25C4.56 18 4 17.44 4 16.75V6.25C4 5.56 4.56 5 5.25 5H15.5a.5.5 0 0 1 0 1H5.25a.25.25 0 0 0-.25.25v10.5c0 .138.112.25.25.25H15.5a.5.5 0 0 1 .5.5"
        clipRule="evenodd"
      />
    </svg>
  )
})
