// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.doc.plus
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyAyMGgxMGExIDEgMCAwIDAgMS0xVjloLTNhMiAyIDAgMCAxLTItMlY0SDdhMSAxIDAgMCAwLTEgMXYxNGExIDEgMCAwIDAgMSAxbTctMTUuNTU0TDE3LjU4IDhIMTVhMSAxIDAgMCAxLTEtMXpNMTcgMjFIN2EyIDIgMCAwIDEtMi0yVjVhMiAyIDAgMCAxIDItMmg2LjM0NWExLjUgMS41IDAgMCAxIDEuMDU2LjQzNWw0LjE1NiA0LjEyNUExLjUgMS41IDAgMCAxIDE5IDguNjI1VjE5YTIgMiAwIDAgMS0yIDJtLTQuOTUtMTFhLjUuNSAwIDAgMSAuNS41djIuMDVoMS45NWEuNS41IDAgMCAxIDAgMWgtMS45NXYxLjk1YS41LjUgMCAwIDEtMSAwdi0xLjk1SDkuNWEuNS41IDAgMCAxIDAtMWgyLjA1VjEwLjVhLjUuNSAwIDAgMSAuNS0uNSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-4753
 */
export const Icon24DocPlus = memo(function Icon24DocPlus(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 20h10a1 1 0 0 0 1-1V9h-3a2 2 0 0 1-2-2V4H7a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1m7-15.554L17.58 8H15a1 1 0 0 1-1-1zM17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6.345a1.5 1.5 0 0 1 1.056.435l4.156 4.125A1.5 1.5 0 0 1 19 8.625V19a2 2 0 0 1-2 2m-4.95-11a.5.5 0 0 1 .5.5v2.05h1.95a.5.5 0 0 1 0 1h-1.95v1.95a.5.5 0 0 1-1 0v-1.95H9.5a.5.5 0 0 1 0-1h2.05V10.5a.5.5 0 0 1 .5-.5"
        clipRule="evenodd"
      />
    </svg>
  )
})
