// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.zoom.out.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEuNSAxNmE0LjUgNC41IDAgMSAwIDAtOSA0LjUgNC41IDAgMCAwIDAgOW0wIDFhNS40OCA1LjQ4IDAgMCAwIDMuNTQ0LTEuMjk0LjUuNSAwIDAgMCAuMTAzLjE0OGwzIDNhLjUuNSAwIDEgMCAuNzA3LS43MDhsLTMtM2EuNS41IDAgMCAwLS4xNDgtLjEwMkE1LjUgNS41IDAgMSAwIDExLjUgMTdtLTItNmEuNS41IDAgMCAwIDAgMWg0YS41LjUgMCAwIDAgMC0xeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-758
 */
export const Icon24ZoomOutSmall = memo(function Icon24ZoomOutSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.5 16a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9m0 1a5.48 5.48 0 0 0 3.544-1.294.5.5 0 0 0 .103.148l3 3a.5.5 0 1 0 .707-.708l-3-3a.5.5 0 0 0-.148-.102A5.5 5.5 0 1 0 11.5 17m-2-6a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  )
})
