// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.home
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy4zMzYgMi40MjJhMSAxIDAgMCAxIDEuMzI4IDBsNCAzLjU1NS0uMzMyLjM3NC4zMzItLjM3NGExIDEgMCAwIDEgLjMzNi43NDdWMTJhMSAxIDAgMCAxLTEgMWgtMmExIDEgMCAwIDEtMS0xVjlIN3YzYTEgMSAwIDAgMS0xIDFINGExIDEgMCAwIDEtMS0xVjYuNzI1YTEgMSAwIDAgMSAuMzM2LS43NDh6TTggMy4xNjkgNCA2LjcyNVYxMmgyVjlhMSAxIDAgMCAxIDEtMWgyYTEgMSAwIDAgMSAxIDF2M2gyVjYuNzI1eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12949
 */
export const Icon16Home = memo(function Icon16Home(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7.336 2.422a1 1 0 0 1 1.328 0l4 3.555-.332.374.332-.374a1 1 0 0 1 .336.747V12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V9H7v3a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6.725a1 1 0 0 1 .336-.748zM8 3.169 4 6.725V12h2V9a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h2V6.725z"
        clipRule="evenodd"
      />
    </svg>
  )
})
