// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.table.ai.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtNS4xOCA1LjI4MS0uMjggMS4xMi0xLjEyLjI4Yy0uMzMzLjA4My0uMzMzLjU1NiAwIC42NGwxLjEyLjI4LjI4IDEuMTE5Yy4wODMuMzMzLjU1Ny4zMzMuNjQgMEw2LjEgNy42bDEuMTItLjI4Yy4zMzMtLjA4My4zMzMtLjU1NiAwLS42NEw2LjEgNi40bC0uMjgtMS4xMTljLS4wODMtLjMzMy0uNTU3LS4zMzMtLjY0IDBNOC41IDdhLjUuNSAwIDAgMCAuNS41VjEwSDUuNWEuNS41IDAgMCAwLS41LjVWMTZsLjAxLjIwNWEyIDIgMCAwIDAgMS43ODUgMS43ODVMNyAxOGg3LjVhLjUuNSAwIDEgMC0uMDI1LTFIMTB2LTIuNWg4LjVhLjUuNSAwIDAgMCAuNS0uNTE5di01LjQ4YTIgMiAwIDAgMC0xLjc5Ni0xLjk5TDE3IDYuNTAxSDkuMDI1QS41LjUgMCAwIDAgOC41IDdNNSA4LjQ2NFYxMHpNNyAxN2ExIDEgMCAwIDEtMS0xdi0xLjVoM1YxN3ptMi0zLjVINlYxMWgzem0xIDBWMTFoOHYyLjV6bTgtMy41aC04VjcuNWg3YTEgMSAwIDAgMSAxIDF6bS4wMTUgNS40NEwxNy43IDE2LjdsLTEuMjYuMzE1Yy0uNTA1LjEyNi0uNTA1Ljg0NCAwIC45N2wxLjI2LjMxNS4zMTUgMS4yNmMuMTI2LjUwNC44NDQuNTA0Ljk3IDBsLjMxNS0xLjI2IDEuMjYtLjMxNWMuNTA1LS4xMjcuNTA1LS44NDQgMC0uOTdMMTkuMyAxNi43bC0uMzE1LTEuMjZjLS4xMjYtLjUwNS0uODQ0LS41MDUtLjk3IDAiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3504-7368
 */
export const Icon24TableAiSmall = memo(function Icon24TableAiSmall(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m5.18 5.281-.28 1.12-1.12.28c-.333.083-.333.556 0 .64l1.12.28.28 1.119c.083.333.557.333.64 0L6.1 7.6l1.12-.28c.333-.083.333-.556 0-.64L6.1 6.4l-.28-1.119c-.083-.333-.557-.333-.64 0M8.5 7a.5.5 0 0 0 .5.5V10H5.5a.5.5 0 0 0-.5.5V16l.01.205a2 2 0 0 0 1.785 1.785L7 18h7.5a.5.5 0 1 0-.025-1H10v-2.5h8.5a.5.5 0 0 0 .5-.519v-5.48a2 2 0 0 0-1.796-1.99L17 6.501H9.025A.5.5 0 0 0 8.5 7M5 8.464V10zM7 17a1 1 0 0 1-1-1v-1.5h3V17zm2-3.5H6V11h3zm1 0V11h8v2.5zm8-3.5h-8V7.5h7a1 1 0 0 1 1 1zm.015 5.44L17.7 16.7l-1.26.315c-.505.126-.505.844 0 .97l1.26.315.315 1.26c.126.504.844.504.97 0l.315-1.26 1.26-.315c.505-.127.505-.844 0-.97L19.3 16.7l-.315-1.26c-.126-.505-.844-.505-.97 0"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5.18 5.78 4.9 6.898l-1.12.28c-.333.083-.333.556 0 .64l1.12.28.28 1.12c.083.332.557.332.64 0l.28-1.12 1.12-.28c.333-.083.333-.557 0-.64l-1.12-.28-.28-1.12c-.083-.333-.557-.333-.64 0M5 8.961V10zM5 15v-4.5a.5.5 0 0 1 .525-.5H9V8.001a.5.5 0 0 1 0-1v-.002h8l.204.011A2 2 0 0 1 19 9v3.5a.5.5 0 1 1-1 0V11h-8v2h7a.5.5 0 1 1-.02 1H10v2h4.5a.5.5 0 1 1-.02 1H7l-.205-.011a2 2 0 0 1-1.785-1.786zm2 1a1 1 0 0 1-1-1v-1h3v2zm2-3H6v-2h3zm9-3h-8V8h7a1 1 0 0 1 1 1zm.015 4.441L17.7 15.7l-1.26.315c-.505.126-.505.844 0 .97l1.26.315.315 1.26c.126.505.844.505.97 0l.315-1.26 1.26-.315c.505-.126.505-.844 0-.97L19.3 15.7l-.315-1.26c-.126-.505-.844-.505-.97 0"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
