// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.devmode.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzE0YWU1YyIgZD0iTTAgMmEyIDIgMCAwIDEgMi0yaDEyYTIgMiAwIDAgMSAyIDJ2MTJhMiAyIDAgMCAxLTIgMkgyYTIgMiAwIDAgMS0yLTJ6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTkuMDYgMi43NjJhLjUuNSAwIDAgMSAuOTM4LjI4MWwtLjAyLjEtMyAxMGEuNS41IDAgMSAxLS45NTctLjI4N2wzLTEwem0tNC44MzYgMi4zMmEuNTAxLjUwMSAwIDAgMSAuNjk0LjY5M2wtLjA2NS4wNzhMMi43MDcgOGwyLjE0NiAyLjE0NmEuNS41IDAgMCAxLS43MDcuNzA3bC0yLjUtMi41YS41LjUgMCAwIDEgMC0uNzA3bDIuNS0yLjV6bTYuOTIyLjA2NGEuNS41IDAgMCAxIC43MDcgMGwyLjUgMi41YS41LjUgMCAwIDEgMCAuNzA3bC0yLjUgMi41LS4wNzguMDY1YS41LjUgMCAwIDEtLjY5My0uNjk0bC4wNjQtLjA3OCAyLjE0Ny0yLjE0Ny0yLjE0Ny0yLjE0NmEuNS41IDAgMCAxIDAtLjcwNyIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=606-6142
 */
export const Icon16DevmodeFavicon = memo(function Icon16DevmodeFavicon(props: SVGIconProps) {
  return (
    <ColorTheme brand="dev-handoff">
      <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M9.06 2.762a.5.5 0 0 1 .938.281l-.02.1-3 10a.5.5 0 1 1-.957-.287l3-10zm-4.836 2.32a.501.501 0 0 1 .694.693l-.065.078L2.707 8l2.146 2.146a.5.5 0 0 1-.707.707l-2.5-2.5a.5.5 0 0 1 0-.707l2.5-2.5zm6.922.064a.5.5 0 0 1 .707 0l2.5 2.5a.5.5 0 0 1 0 .707l-2.5 2.5-.078.065a.5.5 0 0 1-.693-.694l.064-.078 2.147-2.147-2.147-2.146a.5.5 0 0 1 0-.707"
        />
      </svg>
    </ColorTheme>
  )
})
