// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.rotate
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAuMjMzIDYuNDc0YTIuNSAyLjUgMCAwIDEgMy41MzUgMEwxNS4yOTMgOEgxNGEuNS41IDAgMCAwIDAgMWgyLjVhLjUuNSAwIDAgMCAuNS0uNVY2YS41LjUgMCAxIDAtMSAwdjEuMjkybC0xLjUyNS0xLjUyNWEzLjUgMy41IDAgMCAwLTQuOTUgMEw3LjE0NyA4LjE0NmEuNS41IDAgMCAwIC43MDcuNzA3em0yLjgyOCAzLjE3MmExLjUgMS41IDAgMCAwLTIuMTIxIDBsLTMuMjkzIDMuMjkzYTEuNSAxLjUgMCAwIDAgMCAyLjEyMWwzLjI5MyAzLjI5M2ExLjUgMS41IDAgMCAwIDIuMTIgMGwzLjI5NC0zLjI5M2ExLjUgMS41IDAgMCAwIDAtMi4xMjF6bS0xLjQxNC43MDdhLjUuNSAwIDAgMSAuNzA3IDBsMy4yOTMgMy4yOTNhLjUuNSAwIDAgMSAwIC43MDdsLTMuMjkzIDMuMjkzYS41LjUgMCAwIDEtLjcwNyAwbC0zLjI5My0zLjI5M2EuNS41IDAgMCAxIDAtLjcwN3oiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-9536
 */
export const Icon24Rotate = memo(function Icon24Rotate(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10.233 6.474a2.5 2.5 0 0 1 3.535 0L15.293 8H14a.5.5 0 0 0 0 1h2.5a.5.5 0 0 0 .5-.5V6a.5.5 0 1 0-1 0v1.292l-1.525-1.525a3.5 3.5 0 0 0-4.95 0L7.147 8.146a.5.5 0 0 0 .707.707zm2.828 3.172a1.5 1.5 0 0 0-2.121 0l-3.293 3.293a1.5 1.5 0 0 0 0 2.121l3.293 3.293a1.5 1.5 0 0 0 2.12 0l3.294-3.293a1.5 1.5 0 0 0 0-2.121zm-1.414.707a.5.5 0 0 1 .707 0l3.293 3.293a.5.5 0 0 1 0 .707l-3.293 3.293a.5.5 0 0 1-.707 0l-3.293-3.293a.5.5 0 0 1 0-.707z"
        clipRule="evenodd"
      />
    </svg>
  )
})
