// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.design
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTMuMzkgMi4yMDZjLjIzNi0uMTgyLjU0NS0uMjUuODQtLjE4MWw1LjA1OCAxLjE5LjIyNy4wNmE0Ljg3IDQuODcgMCAwIDEgMy41MjEgNC44NDVsLjY3Mi42NzJhMSAxIDAgMCAxIDAgMS40MTRsLTMuNSAzLjVhMSAxIDAgMCAxLTEuNDE0IDBsLS42NzMtLjY3M2E0Ljg3IDQuODcgMCAwIDEtNC44NDUtMy41MmwtLjA2LS4yMjctMS4xOS01LjA1N2ExIDEgMCAwIDEgLjI2Ny0uOTM3bDEtMXpNMyA0bDEuMTkgNS4wNThhMy44NjcgMy44NjcgMCAwIDAgNC4zMSAyLjk0MUw5LjUgMTMgMTMgOS41bC0xLTFhMy44NyAzLjg3IDAgMCAwLTIuOTQyLTQuMzFMNCAyLjk5OXptMy45ODYgMi4yNzdhMiAyIDAgMSAxLS43MDcuNzA3TDMuMTQ3IDMuODUzbC43MDctLjcwN3ptMS4wMTUuNzIyYTEgMSAwIDEgMCAwIDIgMSAxIDAgMCAwIDAtMiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13697
 */
export const Icon16Design = memo(function Icon16Design(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M3.39 2.206c.236-.182.545-.25.84-.181l5.058 1.19.227.06a4.87 4.87 0 0 1 3.521 4.845l.672.672a1 1 0 0 1 0 1.414l-3.5 3.5a1 1 0 0 1-1.414 0l-.673-.673a4.87 4.87 0 0 1-4.845-3.52l-.06-.227-1.19-5.057a1 1 0 0 1 .267-.937l1-1zM3 4l1.19 5.058a3.867 3.867 0 0 0 4.31 2.941L9.5 13 13 9.5l-1-1a3.87 3.87 0 0 0-2.942-4.31L4 2.999zm3.986 2.277a2 2 0 1 1-.707.707L3.147 3.853l.707-.707zm1.015.722a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
      />
    </svg>
  )
})
