// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.version.new.branch
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC4xNDYgNi4xNDZhLjUuNSAwIDAgMSAuNzA4IDBsMiAyYS41LjUgMCAwIDEtLjcwOC43MDhMOSA3LjcwN1YxN2E2IDYgMCAwIDAgNi02VjcuNzA3bC0xLjE0NiAxLjE0N2EuNS41IDAgMCAxLS43MDgtLjcwOGwyLTJhLjUuNSAwIDAgMSAuNzA4IDBsMiAyYS41LjUgMCAwIDEtLjcwOC43MDhMMTYgNy43MDdWMTFhNyA3IDAgMCAxLTcgN2gtLjVhLjUuNSAwIDAgMS0uNS0uNVY3LjcwN0w2Ljg1NCA4Ljg1NGEuNS41IDAgMSAxLS43MDgtLjcwOHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-8637
 */
export const Icon24VersionNewBranch = memo(function Icon24VersionNewBranch(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8.146 6.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L9 7.707V17a6 6 0 0 0 6-6V7.707l-1.146 1.147a.5.5 0 0 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L16 7.707V11a7 7 0 0 1-7 7h-.5a.5.5 0 0 1-.5-.5V7.707L6.854 8.854a.5.5 0 1 1-.708-.708z"
        clipRule="evenodd"
      />
    </svg>
  )
})
