// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.trapezoid
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE5LjIxOCA1YTIgMiAwIDAgMSAxLjk4NiAyLjI0OWwtLjA0NS4yMzYtMi40NTIgOS44MUEyLjI1IDIuMjUgMCAwIDEgMTYuNTI0IDE5SDcuNDc1YTIuMjUgMi4yNSAwIDAgMS0yLjE4Mi0xLjcwNEwyLjg0IDcuNDg2QTIgMiAwIDAgMSA0Ljc4IDV6TTQuNzgxIDZhMSAxIDAgMCAwLS45NyAxLjI0MmwyLjQ1MiA5LjgxYy4xMy41MjIuNTc4Ljg5OCAxLjEwNi45NDNsLjEwNi4wMDVoOS4wNDlhMS4yNSAxLjI1IDAgMCAwIDEuMTgyLS44NDVsLjAzLS4xMDIgMi40NTMtOS44MWExIDEgMCAwIDAtLjg1LTEuMjM2TDE5LjIxOSA2eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7908
 */
export const Icon24ShapeTrapezoid = memo(function Icon24ShapeTrapezoid(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M19.218 5a2 2 0 0 1 1.986 2.249l-.045.236-2.452 9.81A2.25 2.25 0 0 1 16.524 19H7.475a2.25 2.25 0 0 1-2.182-1.704L2.84 7.486A2 2 0 0 1 4.78 5zM4.781 6a1 1 0 0 0-.97 1.242l2.452 9.81c.13.522.578.898 1.106.943l.106.005h9.049a1.25 1.25 0 0 0 1.182-.845l.03-.102 2.453-9.81a1 1 0 0 0-.85-1.236L19.219 6z"
      />
    </svg>
  )
})
