// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.save.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTIuNzA1IDE1LjgxNi0uNzA1LS43LS43MDUuN0w5IDE4LjA5NlY2LjVhLjUuNSAwIDAgMSAuNS0uNWg1YS41LjUgMCAwIDEgLjUuNXYxMS41OTd6bTEuNTkgMi45OUwxMiAxNi41MjZsLTIuMjk1IDIuMjhjLS42MzEuNjI3LTEuNzA1LjE4LTEuNzA1LS43MVY2LjVBMS41IDEuNSAwIDAgMSA5LjUgNWg1QTEuNSAxLjUgMCAwIDEgMTYgNi41djExLjU5N2MwIC44OS0xLjA3NCAxLjMzNi0xLjcwNS43MSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-898
 */
export const Icon24SaveSmall = memo(function Icon24SaveSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m12.705 15.816-.705-.7-.705.7L9 18.096V6.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 .5.5v11.597zm1.59 2.99L12 16.526l-2.295 2.28c-.631.627-1.705.18-1.705-.71V6.5A1.5 1.5 0 0 1 9.5 5h5A1.5 1.5 0 0 1 16 6.5v11.597c0 .89-1.074 1.336-1.705.71"
        clipRule="evenodd"
      />
    </svg>
  )
})
