// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.inspect
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNSA2LjVBMS41IDEuNSAwIDAgMSA2LjUgNWgxMEExLjUgMS41IDAgMCAxIDE4IDYuNXY1YS41LjUgMCAwIDAgMSAwdi01QTIuNSAyLjUgMCAwIDAgMTYuNSA0aC0xMEEyLjUgMi41IDAgMCAwIDQgNi41djEwQTIuNSAyLjUgMCAwIDAgNi41IDE5aDVhLjUuNSAwIDAgMCAwLTFoLTVBMS41IDEuNSAwIDAgMSA1IDE2LjV6bTExLjUyMyAxMC4wMjMgMi42MDEtLjguMDcyLS4wMjMuMzA4LS4wOTUuMjUyLS4wNzdhLjMzLjMzIDAgMCAwIC4wMjMtLjYyM2wtLjI0NC0uMDk2LS4zLS4xMTgtLjA3LS4wMjctNi4xNDMtMi40MTMtLjAyMi0uMDEtLjIxNC0uMDgzLS4zMy0uMTNhLjMzLjMzIDAgMCAwLS40MjguNDI4bC4xMy4zMy4wODQuMjE0LjAwOC4wMjIgMi40MTMgNi4xNDIuMDI4LjA3LjExOC4zLjA5Ni4yNDZhLjMzLjMzIDAgMCAwIC42MjMtLjAyNGwuMDc3LS4yNTEuMDk1LS4zMDkuMDIyLS4wNzJ6bTMuNTI3LS4wNC0yLjcyNy44NC0uODQgMi43MjdjLS4zNyAxLjIwMy0yLjA0OSAxLjI2Ny0yLjUwOS4wOTVsLTIuODc3LTcuMzIzYy0uNDI1LTEuMDgxLjY0My0yLjE1IDEuNzI0LTEuNzI1bDcuMzI0IDIuODc4YzEuMTcxLjQ2IDEuMTA4IDIuMTM4LS4wOTUgMi41MDkiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2621
 */
export const Icon24Inspect = memo(function Icon24Inspect(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5 6.5A1.5 1.5 0 0 1 6.5 5h10A1.5 1.5 0 0 1 18 6.5v5a.5.5 0 0 0 1 0v-5A2.5 2.5 0 0 0 16.5 4h-10A2.5 2.5 0 0 0 4 6.5v10A2.5 2.5 0 0 0 6.5 19h5a.5.5 0 0 0 0-1h-5A1.5 1.5 0 0 1 5 16.5zm11.523 10.023 2.601-.8.072-.023.308-.095.252-.077a.33.33 0 0 0 .023-.623l-.244-.096-.3-.118-.07-.027-6.143-2.413-.022-.01-.214-.083-.33-.13a.33.33 0 0 0-.428.428l.13.33.084.214.008.022 2.413 6.142.028.07.118.3.096.246a.33.33 0 0 0 .623-.024l.077-.251.095-.309.022-.072zm3.527-.04-2.727.84-.84 2.727c-.37 1.203-2.049 1.267-2.509.095l-2.877-7.323c-.425-1.081.643-2.15 1.724-1.725l7.324 2.878c1.171.46 1.108 2.138-.095 2.509"
        clipRule="evenodd"
      />
    </svg>
  )
})
