// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.mask
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy40MyA1LjQzNEE3Ljk5IDcuOTkgMCAwIDAgNCAxMmE3Ljk5IDcuOTkgMCAwIDAgMy40MyA2LjU2NyA3LjAwMyA3LjAwMyAwIDAgMCAwLTEzLjEzMyIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMjAgMTJhOCA4IDAgMCAxLTExLjUgNy4xOTZBOCA4IDAgMCAwIDEzIDEyYTggOCAwIDAgMC00LjUtNy4xOTZBOCA4IDAgMCAxIDIwIDEyTTQgMTJhNy45OSA3Ljk5IDAgMCAxIDMuNDMtNi41NjcgNy4wMDMgNy4wMDMgMCAwIDEgMCAxMy4xMzRBNy45OSA3Ljk5IDAgMCAxIDQgMTJtLTEgMGE5IDkgMCAxIDEgNC4yODcgNy42NjlBOSA5IDAgMCAxIDMgMTIiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3798
 */
export const Icon24Mask = memo(function Icon24Mask(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M7.43 5.434A7.99 7.99 0 0 0 4 12a7.99 7.99 0 0 0 3.43 6.567 7.003 7.003 0 0 0 0-13.133"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M20 12a8 8 0 0 1-11.5 7.196A8 8 0 0 0 13 12a8 8 0 0 0-4.5-7.196A8 8 0 0 1 20 12M4 12a7.99 7.99 0 0 1 3.43-6.567 7.003 7.003 0 0 1 0 13.134A7.99 7.99 0 0 1 4 12m-1 0a9 9 0 1 1 4.287 7.669A9 9 0 0 1 3 12"
        clipRule="evenodd"
      />
    </svg>
  )
})
