// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.open.session.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgOEg4LjVhLjUuNSAwIDAgMC0uNS41djhhLjUuNSAwIDAgMCAuNS41aDdhLjUuNSAwIDAgMCAuNS0uNXYtOGEuNS41IDAgMCAwLS41LS41em00LTFoMS41QTEuNSAxLjUgMCAwIDEgMTcgOC41djhhMS41IDEuNSAwIDAgMS0xLjUgMS41aC03QTEuNSAxLjUgMCAwIDEgNyAxNi41di04QTEuNSAxLjUgMCAwIDEgOC41IDdIMTB2LS41QTEuNSAxLjUgMCAwIDEgMTEuNSA1aDFBMS41IDEuNSAwIDAgMSAxNCA2LjV6bS0xIDB2LS41YS41LjUgMCAwIDAtLjUtLjVoLTFhLjUuNSAwIDAgMC0uNS41Vjd6bS0xIDVhMSAxIDAgMSAwIDAtMiAxIDEgMCAwIDAgMCAybTEuMDY0LjY5NGEyIDIgMCAxIDAtMi4xMjcgMEEzIDMgMCAwIDAgOSAxNS41YS41LjUgMCAwIDAgMSAwIDIgMiAwIDEgMSA0IDAgLjUuNSAwIDAgMCAxIDAgMyAzIDAgMCAwLTEuOTM2LTIuODA2IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10537
 */
export const Icon24OpenSessionSmall = memo(function Icon24OpenSessionSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 8H8.5a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5zm4-1h1.5A1.5 1.5 0 0 1 17 8.5v8a1.5 1.5 0 0 1-1.5 1.5h-7A1.5 1.5 0 0 1 7 16.5v-8A1.5 1.5 0 0 1 8.5 7H10v-.5A1.5 1.5 0 0 1 11.5 5h1A1.5 1.5 0 0 1 14 6.5zm-1 0v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V7zm-1 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2m1.064.694a2 2 0 1 0-2.127 0A3 3 0 0 0 9 15.5a.5.5 0 0 0 1 0 2 2 0 1 1 4 0 .5.5 0 0 0 1 0 3 3 0 0 0-1.936-2.806"
        clipRule="evenodd"
      />
    </svg>
  )
})
