// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.al.height-max
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi41IDVhLjUuNSAwIDAgMCAwIDFoMTBhLjUuNSAwIDAgMCAwLTF6bTAgMTNhLjUuNSAwIDAgMCAwIDFoMTBhLjUuNSAwIDAgMCAwLTF6bTQuNjQ2LTEwLjg1NGEuNS41IDAgMCAxIC43MDggMGwyLjUgMi41YS41LjUgMCAwIDEtLjcwOC43MDhMMTIgOC43MDd2Ni41ODZsMS42NDYtMS42NDdhLjUuNSAwIDAgMSAuNzA4LjcwOGwtMi41IDIuNWEuNS41IDAgMCAxLS43MDggMGwtMi41LTIuNWEuNS41IDAgMCAxIC43MDgtLjcwOEwxMSAxNS4yOTNWOC43MDdsLTEuNjQ2IDEuNjQ3YS41LjUgMCAwIDEtLjcwOC0uNzA4eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7568
 */
export const Icon24AlHeightMax = memo(function Icon24AlHeightMax(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.5 5a.5.5 0 0 0 0 1h10a.5.5 0 0 0 0-1zm0 13a.5.5 0 0 0 0 1h10a.5.5 0 0 0 0-1zm4.646-10.854a.5.5 0 0 1 .708 0l2.5 2.5a.5.5 0 0 1-.708.708L12 8.707v6.586l1.646-1.647a.5.5 0 0 1 .708.708l-2.5 2.5a.5.5 0 0 1-.708 0l-2.5-2.5a.5.5 0 0 1 .708-.708L11 15.293V8.707l-1.646 1.647a.5.5 0 0 1-.708-.708z"
        clipRule="evenodd"
      />
    </svg>
  )
})
