// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.calendar.template.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOSA1LjVhLjUuNSAwIDAgMSAxIDBWNmg0di0uNWEuNS41IDAgMCAxIDEgMFY2aDFhMiAyIDAgMCAxIDIgMnY4YTIgMiAwIDAgMS0yIDJIOGEyIDIgMCAwIDEtMi0yVjhhMiAyIDAgMCAxIDItMmgxek0xNCA3di41YS41LjUgMCAwIDAgMSAwVjdoMWExIDEgMCAwIDEgMSAxdjFIN1Y4YTEgMSAwIDAgMSAxLTFoMXYuNWEuNS41IDAgMCAwIDEgMFY3em0tNyAzdjZhMSAxIDAgMCAwIDEgMWg4YTEgMSAwIDAgMCAxLTF2LTZ6bTQuNzUgMmEuNS41IDAgMCAwIDAgMWguNWEuNS41IDAgMCAwIDAtMXptMS43MjggMS4zNjJBMS41IDEuNSAwIDAgMCAxMi4yNSAxMWgtLjVhMS41IDEuNSAwIDAgMC0xLjIyOCAyLjM2MkExLjUgMS41IDAgMCAwIDExLjUgMTZoMWExLjUgMS41IDAgMCAwIC45NzgtMi42MzhNMTIuMjUgMTRoLS43NWEuNS41IDAgMCAwIDAgMWgxYS41LjUgMCAwIDAgMC0xeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+PC9zdmc+)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10763
 */
export const Icon24CalendarTemplateSmall = memo(function Icon24CalendarTemplateSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9 5.5a.5.5 0 0 1 1 0V6h4v-.5a.5.5 0 0 1 1 0V6h1a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h1zM14 7v.5a.5.5 0 0 0 1 0V7h1a1 1 0 0 1 1 1v1H7V8a1 1 0 0 1 1-1h1v.5a.5.5 0 0 0 1 0V7zm-7 3v6a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-6zm4.75 2a.5.5 0 0 0 0 1h.5a.5.5 0 0 0 0-1zm1.728 1.362A1.5 1.5 0 0 0 12.25 11h-.5a1.5 1.5 0 0 0-1.228 2.362A1.5 1.5 0 0 0 11.5 16h1a1.5 1.5 0 0 0 .978-2.638M12.25 14h-.75a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  )
})
