// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.design.library.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzBkOTlmZiIgZD0iTTAgMmEyIDIgMCAwIDEgMi0yaDEyYTIgMiAwIDAgMSAyIDJ2MTJhMiAyIDAgMCAxLTIgMkgyYTIgMiAwIDAgMS0yLTJ6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTggNC4zMzNhMy41IDMuNSAwIDAgMSA0LjU3NS4wNjVsLjI1Ny4yMjhBLjUuNSAwIDAgMSAxMyA1djdhLjUuNSAwIDAgMS0uODMyLjM3NGwtLjI1Ny0uMjI4YTIuNSAyLjUgMCAwIDAtMy4zMjIgMGwtLjI1Ny4yMjhhLjUuNSAwIDAgMS0uNjY0IDBsLS4yNTctLjIyOGEyLjUgMi41IDAgMCAwLTMuMTM5LS4xNDlsLS4xODMuMTQ5LS4yNTcuMjI4QS41LjUgMCAwIDEgMyAxMlY1YzAtLjE0My4wNjEtLjI4LjE2OC0uMzc0bC4yNTctLjIyOC4xMjYtLjEwN0EzLjUgMy41IDAgMCAxIDggNC4zMzNtLS41ODkuODEzYTIuNSAyLjUgMCAwIDAtMy4xMzktLjE0OWwtLjE4My4xNDlMNCA1LjIyNHY1Ljc2YTMuNSAzLjUgMCAwIDEgMy41IDB2LTUuNzZ6bTQuNSAwYTIuNSAyLjUgMCAwIDAtMy4zMjIgMGwtLjA4OS4wNzh2NS43NmEzLjUgMy41IDAgMCAxIDMuNSAwdi01Ljc2eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=641-5482
 */
export const Icon16DesignLibraryFavicon = memo(function Icon16DesignLibraryFavicon(
  props: SVGIconProps,
) {
  return (
    <ColorTheme brand="design">
      <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M8 4.333a3.5 3.5 0 0 1 4.575.065l.257.228A.5.5 0 0 1 13 5v7a.5.5 0 0 1-.832.374l-.257-.228a2.5 2.5 0 0 0-3.322 0l-.257.228a.5.5 0 0 1-.664 0l-.257-.228a2.5 2.5 0 0 0-3.139-.149l-.183.149-.257.228A.5.5 0 0 1 3 12V5c0-.143.061-.28.168-.374l.257-.228.126-.107A3.5 3.5 0 0 1 8 4.333m-.589.813a2.5 2.5 0 0 0-3.139-.149l-.183.149L4 5.224v5.76a3.5 3.5 0 0 1 3.5 0v-5.76zm4.5 0a2.5 2.5 0 0 0-3.322 0l-.089.078v5.76a3.5 3.5 0 0 1 3.5 0v-5.76z"
        />
      </svg>
    </ColorTheme>
  )
})
