// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.figma.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEuNSA2LjVIMTBhMS41IDEuNSAwIDEgMCAwIDNoMS41em0tMS41IDRoMS41djNIMTBhMS41IDEuNSAwIDAgMSAwLTNtNS41LS41QTIuNSAyLjUgMCAwIDAgMTQgNS41aC00QTIuNSAyLjUgMCAwIDAgOC41IDEwYy0uNjA3LjQ1Ni0xIDEuMTgyLTEgMnMuMzkzIDEuNTQ0IDEgMmEyLjUgMi41IDAgMSAwIDQgMnYtMmEyLjUgMi41IDAgMCAwIDMtNG0tMyAyYTEuNSAxLjUgMCAxIDAgMyAwIDEuNSAxLjUgMCAwIDAtMyAwTTE0IDkuNWgtMS41di0zSDE0YTEuNSAxLjUgMCAwIDEgMCAzbS00IDVhMS41IDEuNSAwIDEgMCAxLjUgMS41di0xLjV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-935
 */
export const Icon24FigmaSmall = memo(function Icon24FigmaSmall(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.5 6.5H10a1.5 1.5 0 1 0 0 3h1.5zm-1.5 4h1.5v3H10a1.5 1.5 0 0 1 0-3m5.5-.5A2.5 2.5 0 0 0 14 5.5h-4A2.5 2.5 0 0 0 8.5 10c-.607.456-1 1.182-1 2s.393 1.544 1 2a2.5 2.5 0 1 0 4 2v-2a2.5 2.5 0 0 0 3-4m-3 2a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0M14 9.5h-1.5v-3H14a1.5 1.5 0 0 1 0 3m-4 5a1.5 1.5 0 1 0 1.5 1.5v-1.5z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M12 7h-1.5a1.5 1.5 0 1 0 0 3H12zm-1.5 4H12v3h-1.5a1.5 1.5 0 0 1 0-3m5.5-.5A2.5 2.5 0 0 0 14.5 6h-4A2.5 2.5 0 0 0 9 10.5c-.607.456-1 1.182-1 2s.393 1.544 1 2a2.5 2.5 0 1 0 4 2v-2a2.5 2.5 0 0 0 3-4m-3 2a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0m1.5-2.5H13V7h1.5a1.5 1.5 0 0 1 0 3m-4 5a1.5 1.5 0 1 0 1.5 1.5V15z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
