// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.stroke.both.points.reversed.triangle-arrow
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDgiIGhlaWdodD0iNjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA1MiAxNiI+CiAgPHJlY3Qgd2lkdGg9IjUyIiBoZWlnaHQ9IjE2IiBmaWxsPSIjMDAwIiByeD0iNCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTQuODczIDguNDkzIDEgMTAuNzUyVjYuMjM0ek0wIDUuNjg3YzAtLjUzLjU3NC0uODYgMS4wMzEtLjU5M2w0LjgxIDIuODA3YS43LjcgMCAwIDEgLjEyNi4wOTJoNDAuMDY2YS43LjcgMCAwIDEgLjEyNS0uMDkybDQuODEtMi44MDdBLjY4Ni42ODYgMCAwIDEgNTIgNS42ODd2NS42MTJjMCAuNTMtLjU3NC44NTktMS4wMzEuNTkybC00LjgxLTIuODA2YS43LjcgMCAwIDEtLjEyNS0uMDkySDUuOTY2YS43LjcgMCAwIDEtLjEyNC4wOTJsLTQuODEgMi44MDZBLjY4Ni42ODYgMCAwIDEgMCAxMS4zem01MSAuNTQ3LTMuODczIDIuMjU5TDUxIDEwLjc1MnoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-14150
 */
export const Icon16StrokeBothPointsReversedTriangleArrow = memo(
  function Icon16StrokeBothPointsReversedTriangleArrow(props: SVGIconProps) {
    return (
      <svg width="52" height="16" fill="none" viewBox="0 0 52 16" {...props}>
        <path
          fill="var(--color-icon)"
          fillRule="evenodd"
          d="M4.873 8.493 1 10.752V6.234zM0 5.687c0-.53.574-.86 1.031-.593l4.81 2.807a.7.7 0 0 1 .126.092h40.066a.7.7 0 0 1 .125-.092l4.81-2.807A.686.686 0 0 1 52 5.687v5.612c0 .53-.574.859-1.031.592l-4.81-2.806a.7.7 0 0 1-.125-.092H5.966a.7.7 0 0 1-.124.092l-4.81 2.806A.686.686 0 0 1 0 11.3zm51 .547-3.873 2.259L51 10.752z"
          clipRule="evenodd"
        />
      </svg>
    )
  },
)
