// This file was auto-generated by fpl/foundations/figma-import

import { memo, useId } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.stroke.end.point.diamond
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDgiIGhlaWdodD0iNjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA1MiAxNiI+CiAgPHJlY3Qgd2lkdGg9IjUyIiBoZWlnaHQ9IjE2IiBmaWxsPSIjMDAwIiByeD0iNCIvPgogIDxnIGNsaXAtcGF0aD0idXJsKCNhKSI+CiAgICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik01MC41ODYgNy41IDQ4IDEwLjA4NiA0NS40MTQgNy41IDQ4IDQuOTE0ek00NC41IDhsLjIwNy4yMDcgMi41ODYgMi41ODZhMSAxIDAgMCAwIDEuNDE0IDBsMi41ODYtMi41ODZhMSAxIDAgMCAwIDAtMS40MTRsLTIuNTg2LTIuNTg2YTEgMSAwIDAgMC0xLjQxNCAwbC0yLjU4NiAyLjU4Nkw0NC41IDdILjVhLjUuNSAwIDAgMCAwIDF6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8L2c+CiAgPGRlZnM+CiAgICA8Y2xpcFBhdGggaWQ9ImEiPgogICAgICA8cGF0aCBmaWxsPSIjZmZmIiBkPSJNMCAwaDUydjE2SDB6Ii8+CiAgICA8L2NsaXBQYXRoPgogIDwvZGVmcz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-14194
 */
export const Icon16StrokeEndPointDiamond = memo(function Icon16StrokeEndPointDiamond(
  props: SVGIconProps,
) {
  const ida = useId()

  return (
    <svg width="52" height="16" fill="none" viewBox="0 0 52 16" {...props}>
      <g clipPath={`url(#${ida})`}>
        <path
          fill="var(--color-icon)"
          fillRule="evenodd"
          d="M50.586 7.5 48 10.086 45.414 7.5 48 4.914zM44.5 8l.207.207 2.586 2.586a1 1 0 0 0 1.414 0l2.586-2.586a1 1 0 0 0 0-1.414l-2.586-2.586a1 1 0 0 0-1.414 0l-2.586 2.586L44.5 7H.5a.5.5 0 0 0 0 1z"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id={ida}>
          <path fill="#fff" d="M0 0h52v16H0z" />
        </clipPath>
      </defs>
    </svg>
  )
})
