// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.child
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEuNSA2YS41LjUgMCAwIDEgLjUuNVYxMWExIDEgMCAwIDAgMSAxaDQuNWEuNS41IDAgMCAxIDAgMUgxM2EyIDIgMCAwIDEtMi0yVjYuNWEuNS41IDAgMCAxIC41LS41IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2333
 */
export const Icon24Child = memo(function Icon24Child(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.5 6a.5.5 0 0 1 .5.5V11a1 1 0 0 0 1 1h4.5a.5.5 0 0 1 0 1H13a2 2 0 0 1-2-2V6.5a.5.5 0 0 1 .5-.5"
        clipRule="evenodd"
      />
    </svg>
  )
})
