// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.all.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy4yNiAxMy40MjZhLjUuNSAwIDAgMC0uNTItLjg1M2wtMS4zMDMuNzk2YTEgMSAwIDAgMCAwIDEuNzA2bDUuNTIgMy4zNzNhMiAyIDAgMCAwIDIuMDg2IDBsNS41Mi0zLjM3M2ExIDEgMCAwIDAgMC0xLjcwNmwtMS4zMDItLjc5NmEuNS41IDAgMSAwLS41MjIuODUzbDEuMzAyLjc5Ni01LjUyIDMuMzczYTEgMSAwIDAgMS0xLjA0MyAwbC01LjUyLTMuMzczem00LjI0NC03LjA2N2ExIDEgMCAwIDEgLjk5MiAwbDUuNDk2IDMuMTQtNS40OTYgMy4xNDFhMSAxIDAgMCAxLS45OTIgMEw2LjAwOCA5LjV6bTEuNDg4LS44NjhhMiAyIDAgMCAwLTEuOTg0IDBMNS41MTIgOC42M2ExIDEgMCAwIDAgMCAxLjczN2w1LjQ5NiAzLjE0YTIgMiAwIDAgMCAxLjk4NCAwbDUuNDk2LTMuMTRhMSAxIDAgMCAwIDAtMS43Mzd6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2447
 */
export const Icon24AllSmall = memo(function Icon24AllSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7.26 13.426a.5.5 0 0 0-.52-.853l-1.303.796a1 1 0 0 0 0 1.706l5.52 3.373a2 2 0 0 0 2.086 0l5.52-3.373a1 1 0 0 0 0-1.706l-1.302-.796a.5.5 0 1 0-.522.853l1.302.796-5.52 3.373a1 1 0 0 1-1.043 0l-5.52-3.373zm4.244-7.067a1 1 0 0 1 .992 0l5.496 3.14-5.496 3.141a1 1 0 0 1-.992 0L6.008 9.5zm1.488-.868a2 2 0 0 0-1.984 0L5.512 8.63a1 1 0 0 0 0 1.737l5.496 3.14a2 2 0 0 0 1.984 0l5.496-3.14a1 1 0 0 0 0-1.737z"
        clipRule="evenodd"
      />
    </svg>
  )
})
