// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.border-top-left-bottom.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyA2YTEgMSAwIDAgMC0xIDF2MTBhMSAxIDAgMCAwIDEgMWgxMGExIDEgMCAwIDAgMS0xdi0xYTEgMSAwIDAgMC0xLTFIOVY5aDhhMSAxIDAgMCAwIDEtMVY3YTEgMSAwIDAgMC0xLTF6bTAgMWgxMHYxSDh2OGg5djFIN3ptMTAgM2EuNS41IDAgMCAwLTEgMHYxYS41LjUgMCAwIDAgMSAwem0wIDNhLjUuNSAwIDAgMC0xIDB2MWEuNS41IDAgMCAwIDEgMHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6295
 */
export const Icon24BorderTopLeftBottomSmall = memo(function Icon24BorderTopLeftBottomSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 6a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1H9V9h8a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1zm0 1h10v1H8v8h9v1H7zm10 3a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm0 3a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0z"
        clipRule="evenodd"
      />
    </svg>
  )
})
