// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.backward.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS44OTMgOC43NjJhLjcuNyAwIDAgMSAxLjEwNy41N3Y1LjMzNmEuNy43IDAgMCAxLTEuMTA3LjU3bC0zLjczNS0yLjY2OWEuNy43IDAgMCAxIDAtMS4xMzl6bTIuMTA3LjU3YzAtMS4zODMtMS41NjMtMi4xODctMi42ODgtMS4zODRsLTMuNzM2IDIuNjY5YTEuNyAxLjcgMCAwIDAgMCAyLjc2NmwzLjczNiAyLjY2OGMxLjEyNS44MDQgMi42ODggMCAyLjY4OC0xLjM4M3YtMS4zNDJxLjAzNy4wMy4wNzYuMDU3bDMuNzM2IDIuNjY5YzEuMTI1LjgwMyAyLjY4OC0uMDAxIDIuNjg4LTEuMzg0VjkuMzMyYzAtMS4zODMtMS41NjMtMi4xODctMi42ODgtMS4zODRsLTMuNzM2IDIuNjY5LS4wNzYuMDU3em00LjM5My0uNTdhLjcuNyAwIDAgMSAxLjEwNy41N3Y1LjMzNmEuNy43IDAgMCAxLTEuMTA3LjU3bC0zLjczNS0yLjY2OGEuNy43IDAgMCAxIDAtMS4xNHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1071
 */
export const Icon24BackwardSmall = memo(function Icon24BackwardSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9.893 8.762a.7.7 0 0 1 1.107.57v5.336a.7.7 0 0 1-1.107.57l-3.735-2.669a.7.7 0 0 1 0-1.139zm2.107.57c0-1.383-1.563-2.187-2.688-1.384l-3.736 2.669a1.7 1.7 0 0 0 0 2.766l3.736 2.668c1.125.804 2.688 0 2.688-1.383v-1.342q.037.03.076.057l3.736 2.669c1.125.803 2.688-.001 2.688-1.384V9.332c0-1.383-1.563-2.187-2.688-1.384l-3.736 2.669-.076.057zm4.393-.57a.7.7 0 0 1 1.107.57v5.336a.7.7 0 0 1-1.107.57l-3.735-2.668a.7.7 0 0 1 0-1.14z"
        clipRule="evenodd"
      />
    </svg>
  )
})
