// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.variable.color.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTcuMzEyIDYuODAzYTcgNyAwIDAgMSA5LjYzOS4yNDhsLjI4LjI5OGE3IDcgMCAwIDEgMS43NiA0Ljk5OGwtLjAyOS4zOEMxOC44MDcgMTQuMjIyIDE3LjQ0NiAxNSAxNi4yNDIgMTVIMTMuNWwtLjEwMS4wMWEuNS41IDAgMCAwLS40LjQ5di41YzAgLjgyLS4zMzggMS42MDMtLjkyIDIuMTI3LS42LjU0Mi0xLjQ2OC44LTIuMzcuNDg4YTcgNyAwIDAgMS0yLjM2Mi0xLjM4NWwtLjI5Ny0uMjhhNyA3IDAgMCAxIDAtOS45em04LjkzLjk1NWE2IDYgMCAwIDAtOC40ODUgMGwtLjIxMi4yMjVhNiA2IDAgMCAwIDIuNDkyIDkuNjg5Yy45NzguMzM3IDEuODQ4LS40NTcgMS45NTMtMS40NjdMMTIgMTZ2LS40OTlhMS41IDEuNSAwIDAgMSAxLjUtMS41aDIuNzQzbC4xNTgtLjAwNmMuNzMzLS4wNTcgMS4zOTEtLjUxMyAxLjU0My0xLjIxNmwuMDI0LS4xNTVhNiA2IDAgMCAwLTEuNDg0LTQuNjExek04LjUgMTIuMDAxYTEgMSAwIDEgMSAwIDIgMSAxIDAgMCAxIDAtMm03LTJhMSAxIDAgMSAxLS4wMDEgMiAxIDEgMCAwIDEgMC0ybS02LTEuNWExIDEgMCAxIDEgMCAyLjAwMSAxIDEgMCAwIDEgMC0ybTMuNS0xYTEgMSAwIDEgMSAwIDIgMSAxIDAgMCAxIDAtMiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=4260-8607
 */
export const Icon24VariableColorSmall = memo(function Icon24VariableColorSmall(
  props: SVGIconProps,
) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M7.312 6.803a7 7 0 0 1 9.639.248l.28.298a7 7 0 0 1 1.76 4.998l-.029.38C18.807 14.222 17.446 15 16.242 15H13.5l-.101.01a.5.5 0 0 0-.4.49v.5c0 .82-.338 1.603-.92 2.127-.6.542-1.468.8-2.37.488a7 7 0 0 1-2.362-1.385l-.297-.28a7 7 0 0 1 0-9.9zm8.93.955a6 6 0 0 0-8.485 0l-.212.225a6 6 0 0 0 2.492 9.689c.978.337 1.848-.457 1.953-1.467L12 16v-.499a1.5 1.5 0 0 1 1.5-1.5h2.743l.158-.006c.733-.057 1.391-.513 1.543-1.216l.024-.155a6 6 0 0 0-1.484-4.611zM8.5 12.001a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7-2a1 1 0 1 1-.001 2 1 1 0 0 1 0-2m-6-1.5a1 1 0 1 1 0 2.001 1 1 0 0 1 0-2m3.5-1a1 1 0 1 1 0 2 1 1 0 0 1 0-2"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M7.312 6.803a7 7 0 0 1 9.638.248l.28.298a7 7 0 0 1 1.761 4.999l-.029.38c-.155 1.494-1.516 2.274-2.72 2.274H13.5a.5.5 0 0 0-.5.5V16c0 .82-.34 1.603-.92 2.127-.602.542-1.468.8-2.37.49A7.002 7.002 0 0 1 7.05 7.051zm8.931.956a6 6 0 0 0-8.485 0l-.213.223a6 6 0 0 0 2.491 9.69c.979.338 1.849-.456 1.953-1.467l.011-.204v-.5c0-.775.59-1.415 1.346-1.492l.154-.007h2.742l.159-.007c.733-.057 1.391-.513 1.543-1.217l.024-.154a6 6 0 0 0-1.484-4.611zM9 12a1 1 0 1 1-.001 2A1 1 0 0 1 9 12m6-2a1 1 0 1 1-.002 2.002A1 1 0 0 1 15 10m-5-1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m3-1a1 1 0 1 1 0 2.002 1 1 0 0 1 0-2.001"
      />
    </svg>
  )

  return icon
})
