// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.connected-project
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAuNDk4IDEwLjk1OWMtLjI3Mi4wNDUtLjQ5OC4yNjUtLjQ5OC41NCAwIC4yNzcuMjI1LjUwNC41LjQ3YTQgNCAwIDEgMC00LjQ3LTQuNDY4Yy0uMDM0LjI3NC4xOTMuNDk5LjQ3LjQ5OS4yNzUgMCAuNDk1LS4yMjYuNTQtLjQ5OGEzIDMgMCAxIDEgMy40NTggMy40NTdNNS41IDQuMDNjLjI3NC0uMDM0LjQ5OS4xOTMuNDk5LjQ2OXMtLjIyNi40OTYtLjQ5OC41NDFBMyAzIDAgMSAwIDguOTYgOC40OThDOS4wMDQgOC4yMjYgOS4yMjQgOCA5LjUgOHMuNTAzLjIyNS40Ny40OTlBNCA0IDAgMSAxIDUuNSA0LjAzMSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=2319-32446
 */
export const Icon16ConnectedProject = memo(function Icon16ConnectedProject(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10.498 10.959c-.272.045-.498.265-.498.54 0 .277.225.504.5.47a4 4 0 1 0-4.47-4.468c-.034.274.193.499.47.499.275 0 .495-.226.54-.498a3 3 0 1 1 3.458 3.457M5.5 4.03c.274-.034.499.193.499.469s-.226.496-.498.541A3 3 0 1 0 8.96 8.498C9.004 8.226 9.224 8 9.5 8s.503.225.47.499A4 4 0 1 1 5.5 4.031"
        clipRule="evenodd"
      />
    </svg>
  )
})
