// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.stroke.end.point.round.short
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNDQiIGhlaWdodD0iNjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAzNiAxNiI+CiAgPHJlY3Qgd2lkdGg9IjM2IiBoZWlnaHQ9IjE2IiBmaWxsPSIjMDAwIiByeD0iNCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTAgMTIuNWEuNS41IDAgMCAwIC41LjVIMzFhNSA1IDAgMCAwIDAtMTBILjVhLjUuNSAwIDAgMCAwIDFIMzFhNCA0IDAgMCAxIDAgOEguNWEuNS41IDAgMCAwLS41LjUiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-14349
 */
export const Icon16StrokeEndPointRoundShort = memo(function Icon16StrokeEndPointRoundShort(
  props: SVGIconProps,
) {
  return (
    <svg width="36" height="16" fill="none" viewBox="0 0 36 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M0 12.5a.5.5 0 0 0 .5.5H31a5 5 0 0 0 0-10H.5a.5.5 0 0 0 0 1H31a4 4 0 0 1 0 8H.5a.5.5 0 0 0-.5.5"
        clipRule="evenodd"
      />
    </svg>
  )
})
