// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.32.devmode.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDMyIDMyIj4KICA8cmVjdCB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzE0YWU1YyIgZD0iTTAgNWE1IDUgMCAwIDEgNS01aDIyYTUgNSAwIDAgMSA1IDV2MjJhNSA1IDAgMCAxLTUgNUg1YTUgNSAwIDAgMS01LTV6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE4LjA2OCA4LjI1YS41MDEuNTAxIDAgMCAxIC45MjguMzFsLS4wMjEuMDk5LTUgMTVhLjUwMS41MDEgMCAwIDEtLjk1LS4zMTdsNS0xNXptMi4wNzkgMy4zOTdhLjUuNSAwIDAgMSAuNjI5LS4wNjVsLjA3OC4wNjUgNCA0YS41LjUgMCAwIDEgMCAuNzA3bC00IDRhLjUuNSAwIDAgMS0uNzA3LS43MDdMMjMuNzkzIDE2bC0zLjY0Ni0zLjY0Ni0uMDY1LS4wNzhhLjUuNSAwIDAgMSAuMDY1LS42M20tOSAwYS41LjUgMCAwIDEgLjcwNy43MDdMOC4yMDcgMTZsMy42NDcgMy42NDcuMDY0LjA3OGEuNTAyLjUwMiAwIDAgMS0uNjkzLjY5M2wtLjA3OC0uMDY0LTQtNGEuNS41IDAgMCAxIDAtLjcwN3oiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=7584-16699
 */
export const Icon32DevmodeFavicon = memo(function Icon32DevmodeFavicon(props: SVGIconProps) {
  return (
    <ColorTheme brand="dev-handoff">
      <svg width="32" height="32" fill="none" viewBox="0 0 32 32" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 5a5 5 0 0 1 5-5h22a5 5 0 0 1 5 5v22a5 5 0 0 1-5 5H5a5 5 0 0 1-5-5z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M18.068 8.25a.501.501 0 0 1 .928.31l-.021.099-5 15a.501.501 0 0 1-.95-.317l5-15zm2.079 3.397a.5.5 0 0 1 .629-.065l.078.065 4 4a.5.5 0 0 1 0 .707l-4 4a.5.5 0 0 1-.707-.707L23.793 16l-3.646-3.646-.065-.078a.5.5 0 0 1 .065-.63m-9 0a.5.5 0 0 1 .707.707L8.207 16l3.647 3.647.064.078a.502.502 0 0 1-.693.693l-.078-.064-4-4a.5.5 0 0 1 0-.707z"
        />
      </svg>
    </ColorTheme>
  )
})
