// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.stroke-diamond-arrow
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNS4yOTMgMTAuNzkzYTEgMSAwIDAgMCAwIDEuNDE0bDIuNSAyLjVhMSAxIDAgMCAwIDEuNDE0IDBsMi41LTIuNXEuMDk0LS4wOTUuMTYtLjIwN0gxOC41YS41LjUgMCAwIDAgMC0xaC02LjYzNGExIDEgMCAwIDAtLjE1OS0uMjA3bC0yLjUtMi41YTEgMSAwIDAgMC0xLjQxNCAwek0xMSAxMS41bC0uNzA3LS43MDctMS4wODYtMS4wODZMOC41IDlsLS43MDcuNzA3LTEuMDg2IDEuMDg2TDYgMTEuNWwuNzA3LjcwNyAxLjA4NiAxLjA4Nkw4LjUgMTRsLjcwNy0uNzA3IDEuMDg2LTEuMDg2eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5788
 */
export const Icon24StrokeDiamondArrow = memo(function Icon24StrokeDiamondArrow(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5.293 10.793a1 1 0 0 0 0 1.414l2.5 2.5a1 1 0 0 0 1.414 0l2.5-2.5q.094-.095.16-.207H18.5a.5.5 0 0 0 0-1h-6.634a1 1 0 0 0-.159-.207l-2.5-2.5a1 1 0 0 0-1.414 0zM11 11.5l-.707-.707-1.086-1.086L8.5 9l-.707.707-1.086 1.086L6 11.5l.707.707 1.086 1.086L8.5 14l.707-.707 1.086-1.086z"
        clipRule="evenodd"
      />
    </svg>
  )
})
