// This file was auto-generated by fpl/foundations/figma-import

import { memo, useId } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.stroke.end.point.triangle.arrow-short
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNDQiIGhlaWdodD0iNjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAzNiAxNiI+CiAgPHJlY3Qgd2lkdGg9IjM2IiBoZWlnaHQ9IjE2IiBmaWxsPSIjMDAwIiByeD0iNCIvPgogIDxnIGNsaXAtcGF0aD0idXJsKCNhKSI+CiAgICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yOS41IDUuNWEuNS41IDAgMCAxIC43NC0uNDM5bDUuNSAzYS41LjUgMCAwIDEgMCAuODc4bC01LjUgM2EuNS41IDAgMCAxLS43NC0uNDM5VjlILjVhLjUuNSAwIDAgMSAwLTFoMjl6bTEgM1Y2LjM0MkwzNC40NTYgOC41IDMwLjUgMTAuNjU4eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPC9nPgogIDxkZWZzPgogICAgPGNsaXBQYXRoIGlkPSJhIj4KICAgICAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTAgMGgzNnYxNkgweiIvPgogICAgPC9jbGlwUGF0aD4KICA8L2RlZnM+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-14117
 */
export const Icon16StrokeEndPointTriangleArrowShort = memo(
  function Icon16StrokeEndPointTriangleArrowShort(props: SVGIconProps) {
    const ida = useId()

    return (
      <svg width="36" height="16" fill="none" viewBox="0 0 36 16" {...props}>
        <g clipPath={`url(#${ida})`}>
          <path
            fill="var(--color-icon)"
            fillRule="evenodd"
            d="M29.5 5.5a.5.5 0 0 1 .74-.439l5.5 3a.5.5 0 0 1 0 .878l-5.5 3a.5.5 0 0 1-.74-.439V9H.5a.5.5 0 0 1 0-1h29zm1 3V6.342L34.456 8.5 30.5 10.658z"
            clipRule="evenodd"
          />
        </g>
        <defs>
          <clipPath id={ida}>
            <path fill="#fff" d="M0 0h36v16H0z" />
          </clipPath>
        </defs>
      </svg>
    )
  },
)
