// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.16.download
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC41IDIuNWEuNS41IDAgMCAwLTEgMHY1Ljc5M0w1Ljg1NCA2LjY0NmEuNS41IDAgMSAwLS43MDcuNzA4bDIuNSAyLjVhLjUuNSAwIDAgMCAuNzA3IDBsMi41LTIuNWEuNS41IDAgMCAwLS43MDctLjcwOEw4LjUgOC4yOTN6bS00LjUgOGEuNS41IDAgMCAwLTEgMHYxQTEuNSAxLjUgMCAwIDAgNC41IDEzaDdhMS41IDEuNSAwIDAgMCAxLjUtMS41di0xYS41LjUgMCAwIDAtMSAwdjFhLjUuNSAwIDAgMS0uNS41aC03YS41LjUgMCAwIDEtLjUtLjV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=157-5353
 */
export const Icon16Download = memo(function Icon16Download(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8.5 2.5a.5.5 0 0 0-1 0v5.793L5.854 6.646a.5.5 0 1 0-.707.708l2.5 2.5a.5.5 0 0 0 .707 0l2.5-2.5a.5.5 0 0 0-.707-.708L8.5 8.293zm-4.5 8a.5.5 0 0 0-1 0v1A1.5 1.5 0 0 0 4.5 13h7a1.5 1.5 0 0 0 1.5-1.5v-1a.5.5 0 0 0-1 0v1a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 2.5a.5.5 0 0 0-1 0v5.793L5.354 6.646a.5.5 0 1 0-.707.708l2.5 2.5a.5.5 0 0 0 .707 0l2.5-2.5a.5.5 0 0 0-.707-.708L8 8.293zm-4 8a.5.5 0 0 0-1 0v1A1.5 1.5 0 0 0 4.5 13h6a1.5 1.5 0 0 0 1.5-1.5v-1a.5.5 0 0 0-1 0v1a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
