// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.interaction.delay
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTIgM2EuNS41IDAgMCAwIDAgMSA4IDggMCAxIDEtOCA4IC41LjUgMCAwIDAtMSAwIDkgOSAwIDEgMCA5LTlNNy4wNjcgNS42NzZhMSAxIDAgMCAwLTEuMzkxIDEuMzlsNC40OTggNi41NDRhMi40NyAyLjQ3IDAgMSAwIDMuNDM2LTMuNDM2em01Ljk3NiA1LjMyMkw4LjgwMSA4LjA4MiA2LjUgNi41bDEuNTgyIDIuMzAxIDIuOTE2IDQuMjQyYTEuNDcgMS40NyAwIDEgMCAyLjA0NS0yLjA0NSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-9920
 */
export const Icon24InteractionDelay = memo(function Icon24InteractionDelay(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M12 3a.5.5 0 0 0 0 1 8 8 0 1 1-8 8 .5.5 0 0 0-1 0 9 9 0 1 0 9-9M7.067 5.676a1 1 0 0 0-1.391 1.39l4.498 6.544a2.47 2.47 0 1 0 3.436-3.436zm5.976 5.322L8.801 8.082 6.5 6.5l1.582 2.301 2.916 4.242a1.47 1.47 0 1 0 2.045-2.045"
        clipRule="evenodd"
      />
    </svg>
  )
})
