// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.autolayout-vertical
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTYuNSA3aC05YS41LjUgMCAwIDAtLjUuNXYyYS41LjUgMCAwIDAgLjUuNWg5YS41LjUgMCAwIDAgLjUtLjV2LTJhLjUuNSAwIDAgMC0uNS0uNW0tOS0xQTEuNSAxLjUgMCAwIDAgNiA3LjV2MkExLjUgMS41IDAgMCAwIDcuNSAxMWg5QTEuNSAxLjUgMCAwIDAgMTggOS41di0yQTEuNSAxLjUgMCAwIDAgMTYuNSA2em0yIDhoLTJhLjUuNSAwIDAgMC0uNS41djJhLjUuNSAwIDAgMCAuNS41aDJhLjUuNSAwIDAgMCAuNS0uNXYtMmEuNS41IDAgMCAwLS41LS41bS0yLTFBMS41IDEuNSAwIDAgMCA2IDE0LjV2MkExLjUgMS41IDAgMCAwIDcuNSAxOGgyYTEuNSAxLjUgMCAwIDAgMS41LTEuNXYtMkExLjUgMS41IDAgMCAwIDkuNSAxM3ptMTAuMzg0IDEuMzJhLjUuNSAwIDAgMC0uNzY4LS42NGwtMi4xNSAyLjU4LTEuMTEyLTEuMTE0YS41LjUgMCAwIDAtLjcwOC43MDhsMS41IDEuNWEuNS41IDAgMCAwIC43MzgtLjAzNHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7273
 */
export const Icon24AutolayoutVertical = memo(function Icon24AutolayoutVertical(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M16.5 7h-9a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5m-9-1A1.5 1.5 0 0 0 6 7.5v2A1.5 1.5 0 0 0 7.5 11h9A1.5 1.5 0 0 0 18 9.5v-2A1.5 1.5 0 0 0 16.5 6zm2 8h-2a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5m-2-1A1.5 1.5 0 0 0 6 14.5v2A1.5 1.5 0 0 0 7.5 18h2a1.5 1.5 0 0 0 1.5-1.5v-2A1.5 1.5 0 0 0 9.5 13zm10.384 1.32a.5.5 0 0 0-.768-.64l-2.15 2.58-1.112-1.114a.5.5 0 0 0-.708.708l1.5 1.5a.5.5 0 0 0 .738-.034z"
        clipRule="evenodd"
      />
    </svg>
  )
})
