// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.angle
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS41OTYgMTYuNTk3YS41LjUgMCAxIDAgLjcwNy43MDdsNC45NS00Ljk1YS41LjUgMCAwIDAgMC0uNzA3bC00Ljk1LTQuOTVhLjUuNSAwIDAgMC0uNzA3LjcwN2wyLjE3NSAyLjE3NWE0LjA0IDQuMDQgMCAwIDAgMCA0Ljg0M3ptMi44OTItMi44OTIgMS43MDQtMS43MDQtMS43MDUtMS43MDVhMy4wNCAzLjA0IDAgMCAwIDAgMy40MSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-8290
 */
export const Icon24Angle = memo(function Icon24Angle(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9.596 16.597a.5.5 0 1 0 .707.707l4.95-4.95a.5.5 0 0 0 0-.707l-4.95-4.95a.5.5 0 0 0-.707.707l2.175 2.175a4.04 4.04 0 0 0 0 4.843zm2.892-2.892 1.704-1.704-1.705-1.705a3.04 3.04 0 0 0 0 3.41"
        clipRule="evenodd"
      />
    </svg>
  )
})
