// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.pen
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTMuMzkgMi4yMDdhMSAxIDAgMCAxIC44MzgtLjE4MWw1LjA1OSAxLjE5aC4wMDFsLjIyNy4wNTlhNC44NyA0Ljg3IDAgMCAxIDMuNTIxIDQuODQ1bC42NzIuNjcyYTEgMSAwIDAgMSAwIDEuNDE0bC0zLjUgMy41YTEgMSAwIDAgMS0xLjQxNCAwbC0uNjczLS42NzJhNC44NyA0Ljg3IDAgMCAxLTQuODQ1LTMuNTIxbC0uMDYtLjIyNy0xLjE5LTUuMDU3YTEgMSAwIDAgMSAuMjY3LS45MzdsMS0xem0uNDY0LjkzOCAzLjEzMiAzLjEzMmEyIDIgMCAxIDEtLjcwNy43MDdMMy4xNDcgMy44NTIgMyAzLjk5OWwxLjE5IDUuMDU4YTMuODY3IDMuODY3IDAgMCAwIDQuMzEgMi45NDFMOS41IDEzIDEzIDkuNWwtMS0xYTMuODcgMy44NyAwIDAgMC0yLjk0LTQuMzFMNCAzem00LjE0NyAzLjg1M2ExIDEgMCAxIDAgMCAyIDEgMSAwIDAgMCAwLTIiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12902
 */
export const Icon16Pen = memo(function Icon16Pen(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M3.39 2.207a1 1 0 0 1 .838-.181l5.059 1.19h.001l.227.059a4.87 4.87 0 0 1 3.521 4.845l.672.672a1 1 0 0 1 0 1.414l-3.5 3.5a1 1 0 0 1-1.414 0l-.673-.672a4.87 4.87 0 0 1-4.845-3.521l-.06-.227-1.19-5.057a1 1 0 0 1 .267-.937l1-1zm.464.938 3.132 3.132a2 2 0 1 1-.707.707L3.147 3.852 3 3.999l1.19 5.058a3.867 3.867 0 0 0 4.31 2.941L9.5 13 13 9.5l-1-1a3.87 3.87 0 0 0-2.94-4.31L4 3zm4.147 3.853a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
      />
    </svg>
  )
})
