// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.lock.locked
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOSA4YTMgMyAwIDEgMSA2IDB2Mkg5em0tMSAyVjhhNCA0IDAgMSAxIDggMHYyaC4xMjVDMTcuMTYgMTAgMTggMTAuODQgMTggMTEuODc1djUuMjVDMTggMTguMTYgMTcuMTYgMTkgMTYuMTI1IDE5aC04LjI1QTEuODc1IDEuODc1IDAgMCAxIDYgMTcuMTI1di01LjI1QzYgMTAuODM5IDYuODQgMTAgNy44NzUgMTB6bS0xIDEuODc1YzAtLjQ4My4zOTItLjg3NS44NzUtLjg3NWg4LjI1Yy40ODMgMCAuODc1LjM5Mi44NzUuODc1djUuMjVhLjg3NS44NzUgMCAwIDEtLjg3NS44NzVoLTguMjVBLjg3NS44NzUgMCAwIDEgNyAxNy4xMjV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1456
 */
export const Icon24LockLocked = memo(function Icon24LockLocked(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9 8a3 3 0 1 1 6 0v2H9zm-1 2V8a4 4 0 1 1 8 0v2h.125C17.16 10 18 10.84 18 11.875v5.25C18 18.16 17.16 19 16.125 19h-8.25A1.875 1.875 0 0 1 6 17.125v-5.25C6 10.839 6.84 10 7.875 10zm-1 1.875c0-.483.392-.875.875-.875h8.25c.483 0 .875.392.875.875v5.25a.875.875 0 0 1-.875.875h-8.25A.875.875 0 0 1 7 17.125z"
        clipRule="evenodd"
      />
    </svg>
  )
})
