// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.unsaved.changes
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTcuMDQzIDkuOTI4LS4wNTUtLjc1OWE0LjUgNC41IDAgMCAwLTguNTA0LTEuNzAzbC0uMjU3LjUwNy0uNTY3LjAzOEE1IDUgMCAwIDAgOCAxOGgyYS41LjUgMCAxIDEgMCAxSDhhNiA2IDAgMCAxLS40MDctMTEuOTg2IDUuNSA1LjUgMCAwIDEgMTAuMzkzIDIuMDgzQTUuMDAyIDUuMDAyIDAgMCAxIDE3IDE5aC0zYS41LjUgMCAwIDEgMC0xaDNhNCA0IDAgMCAwIC43OS03LjkyMnptLTQuNjkgMS4yMTlhLjUuNSAwIDAgMC0uNzA3IDBsLTIuNSAyLjVhLjUuNSAwIDEgMCAuNzA4LjcwN2wxLjY0Ni0xLjY0N1YxOWEuNS41IDAgMSAwIDEgMHYtNi4yOTNsMS42NDYgMS42NDdhLjUuNSAwIDAgMCAuNzA4LS43MDd6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-4079
 */
export const Icon24UnsavedChanges = memo(function Icon24UnsavedChanges(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m17.043 9.928-.055-.759a4.5 4.5 0 0 0-8.504-1.703l-.257.507-.567.038A5 5 0 0 0 8 18h2a.5.5 0 1 1 0 1H8a6 6 0 0 1-.407-11.986 5.5 5.5 0 0 1 10.393 2.083A5.002 5.002 0 0 1 17 19h-3a.5.5 0 0 1 0-1h3a4 4 0 0 0 .79-7.922zm-4.69 1.219a.5.5 0 0 0-.707 0l-2.5 2.5a.5.5 0 1 0 .708.707l1.646-1.647V19a.5.5 0 1 0 1 0v-6.293l1.646 1.647a.5.5 0 0 0 .708-.707z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m17.043 9.928-.055-.759a4.5 4.5 0 0 0-8.504-1.703l-.257.507-.567.038A5 5 0 0 0 8 18h1.5a.5.5 0 0 1 0 1H8a6 6 0 0 1-.407-11.986 5.5 5.5 0 0 1 10.393 2.083A5.002 5.002 0 0 1 17 19h-3.5a.5.5 0 0 1 0-1H17a4 4 0 0 0 .79-7.922zm-5.19 1.218a.5.5 0 0 0-.707 0l-3 3a.5.5 0 0 0 .708.708L11 12.707V19.5a.5.5 0 0 0 1 0v-6.793l2.146 2.147a.5.5 0 0 0 .708-.708z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
