// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.send.forward.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy41IDdhLjUuNSAwIDAgMCAwIDFoOGEuNS41IDAgMCAwIDAtMXpNNiA3LjVBMS41IDEuNSAwIDAgMSA3LjUgNmg4YTEuNSAxLjUgMCAwIDEgMCAzaC04QTEuNSAxLjUgMCAwIDEgNiA3LjVtNS4xNDYgMi42NDZhLjUuNSAwIDAgMSAuNzA4IDBsMiAyYS41LjUgMCAwIDEtLjcwOC43MDhMMTIgMTEuNzA3VjE1aDMuNWExLjUgMS41IDAgMCAxIDAgM2gtOGExLjUgMS41IDAgMCAxIDAtM0gxMXYtMy4yOTNsLTEuMTQ2IDEuMTQ3YS41LjUgMCAwIDEtLjcwOC0uNzA4ek03IDE2LjVhLjUuNSAwIDAgMSAuNS0uNWg4YS41LjUgMCAwIDEgMCAxaC04YS41LjUgMCAwIDEtLjUtLjUiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11014
 */
export const Icon24SendForwardSmall = memo(function Icon24SendForwardSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7.5 7a.5.5 0 0 0 0 1h8a.5.5 0 0 0 0-1zM6 7.5A1.5 1.5 0 0 1 7.5 6h8a1.5 1.5 0 0 1 0 3h-8A1.5 1.5 0 0 1 6 7.5m5.146 2.646a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L12 11.707V15h3.5a1.5 1.5 0 0 1 0 3h-8a1.5 1.5 0 0 1 0-3H11v-3.293l-1.146 1.147a.5.5 0 0 1-.708-.708zM7 16.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5"
        clipRule="evenodd"
      />
    </svg>
  )
})
