// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.preview.prototype
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTggNUg2YTEgMSAwIDAgMC0xIDF2MWgxNFY2YTEgMSAwIDAgMC0xLTFtMSAzSDV2MTBhMSAxIDAgMCAwIDEgMWgxMmExIDEgMCAwIDAgMS0xek02IDRhMiAyIDAgMCAwLTIgMnYxMmEyIDIgMCAwIDAgMiAyaDEyYTIgMiAwIDAgMCAyLTJWNmEyIDIgMCAwIDAtMi0yem03LjU2MSAxMC4wODcuMTY1LS4xMDMuNDM1LS4yNzJhLjI1LjI1IDAgMCAwIDAtLjQyNGwtLjQzNS0uMjcyLS4xNjUtLjEwMy0uMDA0LS4wMDMtMi4wNTctMS4yODUtLjAxNy0uMDEtLjI2MS0uMTY0LS4zNC0uMjEyYS4yNS4yNSAwIDAgMC0uMzgyLjIxMnY0LjA5OGEuMjUuMjUgMCAwIDAgLjM4My4yMTJsLjMzOS0uMjEyLjI2LS4xNjMuMDE4LS4wMTEgMi4wNTctMS4yODV6bTEuMTMtMS42NDctMy4yNzktMi4wNDlhMS4yNSAxLjI1IDAgMCAwLTEuOTEyIDEuMDZ2NC4wOThhMS4yNSAxLjI1IDAgMCAwIDEuOTEyIDEuMDZsMy4yNzktMi4wNDlhMS4yNSAxLjI1IDAgMCAwIDAtMi4xMiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10071
 */
export const Icon24PreviewPrototype = memo(function Icon24PreviewPrototype(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M18 5H6a1 1 0 0 0-1 1v1h14V6a1 1 0 0 0-1-1m1 3H5v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1zM6 4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm7.561 10.087.165-.103.435-.272a.25.25 0 0 0 0-.424l-.435-.272-.165-.103-.004-.003-2.057-1.285-.017-.01-.261-.164-.34-.212a.25.25 0 0 0-.382.212v4.098a.25.25 0 0 0 .383.212l.339-.212.26-.163.018-.011 2.057-1.285zm1.13-1.647-3.279-2.049a1.25 1.25 0 0 0-1.912 1.06v4.098a1.25 1.25 0 0 0 1.912 1.06l3.279-2.049a1.25 1.25 0 0 0 0-2.12"
        clipRule="evenodd"
      />
    </svg>
  )
})
