// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.stroke-line-arrow
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC44NTQgOC4xNDdhLjUuNSAwIDAgMSAwIC43MDdsLTIuMTQ3IDIuMTQ1TDE4LjUgMTFhLjUuNSAwIDEgMSAwIDFINi43MDdsMi4xNDcgMi4xNDZhLjUuNSAwIDEgMS0uNzA4LjcwN2wtMy0zYS41LjUgMCAwIDEgMC0uNzA4bDMtMi45OTlhLjUuNSAwIDAgMSAuNzA4IDAiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5750
 */
export const Icon24StrokeLineArrow = memo(function Icon24StrokeLineArrow(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8.854 8.147a.5.5 0 0 1 0 .707l-2.147 2.145L18.5 11a.5.5 0 1 1 0 1H6.707l2.147 2.146a.5.5 0 1 1-.708.707l-3-3a.5.5 0 0 1 0-.708l3-2.999a.5.5 0 0 1 .708 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
