// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.boolean.union
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTQgNUg1djloNXY1aDl2LTloLTV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xMCAxNHY1aDl2LTloLTVWNUg1djl6TTQgNXY5YTEgMSAwIDAgMCAxIDFoNHY0YTEgMSAwIDAgMCAxIDFoOWExIDEgMCAwIDAgMS0xdi05YTEgMSAwIDAgMC0xLTFoLTRWNWExIDEgMCAwIDAtMS0xSDVhMSAxIDAgMCAwLTEgMSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3866
 */
export const Icon24BooleanUnion = memo(function Icon24BooleanUnion(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M14 5H5v9h5v5h9v-9h-5z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 14v5h9v-9h-5V5H5v9zM4 5v9a1 1 0 0 0 1 1h4v4a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-9a1 1 0 0 0-1-1h-4V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1"
        clipRule="evenodd"
      />
    </svg>
  )
})
