// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.pick.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTYuNSA3aC05YS41LjUgMCAwIDAtLjUuNXY5YS41LjUgMCAwIDAgLjUuNWg0YS41LjUgMCAwIDEgMCAxaC00QTEuNSAxLjUgMCAwIDEgNiAxNi41di05QTEuNSAxLjUgMCAwIDEgNy41IDZoOUExLjUgMS41IDAgMCAxIDE4IDcuNXY0YS41LjUgMCAwIDEtMSAwdi00YS41LjUgMCAwIDAtLjUtLjVtLS41ODIgOC45MTcgMS4yMTUtLjM3NC4wNzItLjAyMi4zMDktLjA5NS4yNTEtLjA3N2EuMzMuMzMgMCAwIDAgLjAyNC0uNjIzbC0uMjQ1LS4wOTYtLjMtLjExOC0uMDctLjAyNy0zLjE1OC0xLjI0MS0uMDIyLS4wMDktLjIxMy0uMDgzLS4zMy0uMTNhLjMzLjMzIDAgMCAwLS40MjkuNDI4bC4xMy4zMy4wODQuMjEzLjAwOS4wMjIgMS4yNCAzLjE1OC4wMjguMDcuMTE4LjMuMDk2LjI0NWEuMzMuMzMgMCAwIDAgLjYyMi0uMDIzbC4wNzgtLjI1Mi4wOTUtLjMwOC4wMjItLjA3MnptMi4xNDEuMzg4LTEuMzQxLjQxMi0uNDEzIDEuMzQyYy0uMzcgMS4yMDItMi4wNDkgMS4yNjYtMi41MDkuMDk1bC0xLjcwNC00LjMzOWMtLjQyNS0xLjA4LjY0My0yLjE0OSAxLjcyNC0xLjcyNGw0LjMzOCAxLjcwNGMxLjE3Mi40NiAxLjEwOCAyLjE0LS4wOTUgMi41MSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1499-6124
 */
export const Icon24PickSmall = memo(function Icon24PickSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M16.5 7h-9a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h4a.5.5 0 0 1 0 1h-4A1.5 1.5 0 0 1 6 16.5v-9A1.5 1.5 0 0 1 7.5 6h9A1.5 1.5 0 0 1 18 7.5v4a.5.5 0 0 1-1 0v-4a.5.5 0 0 0-.5-.5m-.582 8.917 1.215-.374.072-.022.309-.095.251-.077a.33.33 0 0 0 .024-.623l-.245-.096-.3-.118-.07-.027-3.158-1.241-.022-.009-.213-.083-.33-.13a.33.33 0 0 0-.429.428l.13.33.084.213.009.022 1.24 3.158.028.07.118.3.096.245a.33.33 0 0 0 .622-.023l.078-.252.095-.308.022-.072zm2.141.388-1.341.412-.413 1.342c-.37 1.202-2.049 1.266-2.509.095l-1.704-4.339c-.425-1.08.643-2.149 1.724-1.724l4.338 1.704c1.172.46 1.108 2.14-.095 2.51"
        clipRule="evenodd"
      />
    </svg>
  )
})
