// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.pause.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy41IDdoMmEuNS41IDAgMCAxIC41LjV2OWEuNS41IDAgMCAxLS41LjVoLTJhLjUuNSAwIDAgMS0uNS0uNXYtOWEuNS41IDAgMCAxIC41LS41TTYgNy41QTEuNSAxLjUgMCAwIDEgNy41IDZoMkExLjUgMS41IDAgMCAxIDExIDcuNXY5QTEuNSAxLjUgMCAwIDEgOS41IDE4aC0yQTEuNSAxLjUgMCAwIDEgNiAxNi41em04LjUtLjVoMmEuNS41IDAgMCAxIC41LjV2OWEuNS41IDAgMCAxLS41LjVoLTJhLjUuNSAwIDAgMS0uNS0uNXYtOWEuNS41IDAgMCAxIC41LS41bS0xLjUuNUExLjUgMS41IDAgMCAxIDE0LjUgNmgyQTEuNSAxLjUgMCAwIDEgMTggNy41djlhMS41IDEuNSAwIDAgMS0xLjUgMS41aC0yYTEuNSAxLjUgMCAwIDEtMS41LTEuNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1119
 */
export const Icon24PauseSmall = memo(function Icon24PauseSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7.5 7h2a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5M6 7.5A1.5 1.5 0 0 1 7.5 6h2A1.5 1.5 0 0 1 11 7.5v9A1.5 1.5 0 0 1 9.5 18h-2A1.5 1.5 0 0 1 6 16.5zm8.5-.5h2a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5m-1.5.5A1.5 1.5 0 0 1 14.5 6h2A1.5 1.5 0 0 1 18 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-2a1.5 1.5 0 0 1-1.5-1.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
