// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.plus
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE0IDNhMiAyIDAgMCAxIDIgMnYzaDNhMiAyIDAgMCAxIDEuOTkgMS43OTZMMjEgMTB2NGEyIDIgMCAwIDEtMS43OTYgMS45OUwxOSAxNmgtM3YzYTIgMiAwIDAgMS0xLjc5NiAxLjk5TDE0IDIxaC00YTIgMiAwIDAgMS0yLTJ2LTNINWEyIDIgMCAwIDEtMS45OS0xLjc5NkwzIDE0di00YTIgMiAwIDAgMSAyLTJoM1Y1YTIgMiAwIDAgMSAyLTJ6bS00IDFhMSAxIDAgMCAwLTEgMXY0SDVsLS4xMDMuMDA1QTEgMSAwIDAgMCA0IDEwdjRsLjAwNS4xMDJhMSAxIDAgMCAwIC44OTIuODkzTDUgMTVoNHY0YTEgMSAwIDAgMCAxIDFoNGExIDEgMCAwIDAgMS0xdi00aDRhMSAxIDAgMCAwIDEtMXYtNGExIDEgMCAwIDAtMS0xaC00VjVhMSAxIDAgMCAwLTEtMXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7978
 */
export const Icon24ShapePlus = memo(function Icon24ShapePlus(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M14 3a2 2 0 0 1 2 2v3h3a2 2 0 0 1 1.99 1.796L21 10v4a2 2 0 0 1-1.796 1.99L19 16h-3v3a2 2 0 0 1-1.796 1.99L14 21h-4a2 2 0 0 1-2-2v-3H5a2 2 0 0 1-1.99-1.796L3 14v-4a2 2 0 0 1 2-2h3V5a2 2 0 0 1 2-2zm-4 1a1 1 0 0 0-1 1v4H5l-.103.005A1 1 0 0 0 4 10v4l.005.102a1 1 0 0 0 .892.893L5 15h4v4a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-4h4a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1h-4V5a1 1 0 0 0-1-1z"
      />
    </svg>
  )
})
