// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.ai.assistant
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTcgMTVhLjUuNSAwIDAgMSAuNS41djFoMWEuNS41IDAgMCAxIDAgMWgtMXYxYS41LjUgMCAwIDEtMSAwdi0xaC0xYS41LjUgMCAxIDEgMC0xaDF2LTFhLjUuNSAwIDAgMSAuNS0uNW0tNi45MzUtOC4zNzljLjM2Mi0xLjQ0OCAyLjM2Ny0xLjQ5MyAyLjgzMi0uMTM2bC4wNC4xMzYuNzg4IDMuMTU0IDMuMTU1Ljc5YzEuNDk0LjM3MyAxLjQ5NCAyLjQ5OCAwIDIuODcybC0zLjE1NS43ODgtLjc4OCAzLjE1NWMtLjM3NCAxLjQ5NC0yLjQ5OCAxLjQ5NC0yLjg3MiAwbC0uNzktMy4xNTUtMy4xNTQtLjc4OGMtMS40OTUtLjM3NC0xLjQ5NS0yLjQ5OSAwLTIuODcybDMuMTU0LS43OXptMS45LjI0MmMtLjEyLS40ODQtLjgwOC0uNDg0LS45MyAwbC0uOTM0IDMuNzM4LTMuNzM4LjkzNGMtLjQ4NC4xMjItLjQ4NC44MSAwIC45M2wzLjczOC45MzUuOTM0IDMuNzM4Yy4xMTQuNDUzLjcyNy40ODIuOTAzLjA4NWwuMDI4LS4wODUuOTM0LTMuNzM4IDMuNzM4LS45MzRjLjQ1My0uMTE0LjQ4MS0uNzI1LjA4NS0uOTAxbC0uMDg1LS4wMy0zLjczOC0uOTM0ek0xNyA1YTIgMiAwIDEgMSAwIDQgMiAyIDAgMCAxIDAtNG0wIDFhMSAxIDAgMSAwIDAgMiAxIDEgMCAwIDAgMC0yIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz48L3N2Zz4=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2533
 */
export const Icon24AiAssistant = memo(function Icon24AiAssistant(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props} data-fpl-icon-size="24">
      <path
        fill="var(--fpl-icon-color, var(--color-icon))"
        fillRule="evenodd"
        d="M17 15a.5.5 0 0 1 .5.5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 1 1 0-1h1v-1a.5.5 0 0 1 .5-.5m-6.935-8.379c.362-1.448 2.367-1.493 2.832-.136l.04.136.788 3.154 3.155.79c1.494.373 1.494 2.498 0 2.872l-3.155.788-.788 3.155c-.374 1.494-2.498 1.494-2.872 0l-.79-3.155-3.154-.788c-1.495-.374-1.495-2.499 0-2.872l3.154-.79zm1.9.242c-.12-.484-.808-.484-.93 0l-.934 3.738-3.738.934c-.484.122-.484.81 0 .93l3.738.935.934 3.738c.114.453.727.482.903.085l.028-.085.934-3.738 3.738-.934c.453-.114.481-.725.085-.901l-.085-.03-3.738-.934zM17 5a2 2 0 1 1 0 4 2 2 0 0 1 0-4m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props} data-fpl-icon-size="24">
      <path
        fill="var(--fpl-icon-color, var(--color-icon))"
        fillRule="evenodd"
        d="M10.065 7.121c.362-1.448 2.367-1.493 2.832-.136l.04.136.788 3.155 3.155.789c1.494.373 1.494 2.498 0 2.872l-3.155.788-.788 3.155c-.374 1.494-2.499 1.494-2.872 0l-.789-3.155-3.155-.788c-1.495-.374-1.495-2.499 0-2.872l3.154-.79zM16.5 16a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 0 1H17v.5a.5.5 0 0 1-1 0V18h-.5a.5.5 0 1 1 0-1h.5v-.5a.5.5 0 0 1 .5-.5m-4.534-8.637c-.122-.484-.81-.484-.93 0l-.935 3.738-3.738.934c-.484.122-.484.81 0 .93l3.738.935.934 3.738c.114.454.727.482.903.085l.028-.085.934-3.738 3.738-.934c.453-.114.482-.725.085-.901l-.085-.03-3.738-.934zM16.5 6a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3m0 1a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
