// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.closed.captioning.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyA3aDEwYTEgMSAwIDAgMSAxIDF2OGExIDEgMCAwIDEtMSAxSDdhMSAxIDAgMCAxLTEtMVY4YTEgMSAwIDAgMSAxLTFNNSA4YTIgMiAwIDAgMSAyLTJoMTBhMiAyIDAgMCAxIDIgMnY4YTIgMiAwIDAgMS0yIDJIN2EyIDIgMCAwIDEtMi0yem00LjUgN2EuNS41IDAgMCAwIDAgMWgyYS41LjUgMCAwIDAgMC0xem00LjUtMS41YS41LjUgMCAwIDEgLjUtLjVoMmEuNS41IDAgMCAxIDAgMWgtMmEuNS41IDAgMCAxLS41LS41bS0zLjUtLjVhLjUuNSAwIDAgMCAwIDFoMmEuNS41IDAgMCAwIDAtMXptMi41IDIuNWEuNS41IDAgMCAxIC41LS41aDFhLjUuNSAwIDAgMSAwIDFoLTFhLjUuNSAwIDAgMS0uNS0uNU03LjUgMTNhLjUuNSAwIDAgMCAwIDFoMWEuNS41IDAgMCAwIDAtMXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-4488
 */
export const Icon24ClosedCaptioningSmall = memo(function Icon24ClosedCaptioningSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 7h10a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1M5 8a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2zm4.5 7a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm4.5-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-3.5-.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm2.5 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5M7.5 13a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  )
})
