// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-align-horizontal-center
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTcuMjUgMTBhLjc1Ljc1IDAgMCAwIC43NS0uNzV2LS41YS43NS43NSAwIDAgMC0uNzUtLjc1aC05LjVhLjc1Ljc1IDAgMCAwLS43NS43NXYuNWMwIC40MTQuMzM2Ljc1Ljc1Ljc1em0tMiA1YS43NS43NSAwIDAgMCAuNzUtLjc1di0uNWEuNzUuNzUgMCAwIDAtLjc1LS43NWgtNS41YS43NS43NSAwIDAgMC0uNzUuNzV2LjVjMCAuNDE0LjMzNi43NS43NS43NXpNMTMgMTcuNWEuNS41IDAgMCAxLTEgMFYxNWgxem0wLTQuNXYtM2gtMXYzem0wLTcuNVY4aC0xVjUuNWEuNS41IDAgMCAxIDEgMCIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6965
 */
export const Icon24LayoutAlignHorizontalCenter = memo(function Icon24LayoutAlignHorizontalCenter(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M17.25 10a.75.75 0 0 0 .75-.75v-.5a.75.75 0 0 0-.75-.75h-9.5a.75.75 0 0 0-.75.75v.5c0 .414.336.75.75.75zm-2 5a.75.75 0 0 0 .75-.75v-.5a.75.75 0 0 0-.75-.75h-5.5a.75.75 0 0 0-.75.75v.5c0 .414.336.75.75.75z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M13 17.5a.5.5 0 0 1-1 0V15h1zm0-4.5v-3h-1v3zm0-7.5V8h-1V5.5a.5.5 0 0 1 1 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
