// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.hexagon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2LjkyNiA1YTIgMiAwIDAgMSAxLjcyOC45OTJsMi45MTcgNSAuMDYzLjExOGMuMjc4LjU2LjI3OCAxLjIyIDAgMS43OGwtLjA2My4xMTgtMi45MTcgNWEyIDIgMCAwIDEtMS43MjguOTkySDcuMDc1YTIgMiAwIDAgMS0xLjcyOC0uOTkybC0yLjkxNy01YTIgMiAwIDAgMSAwLTIuMDE2bDIuOTE3LTUgLjA3LS4xMTJBMiAyIDAgMCAxIDcuMDc1IDV6TTcuMDc1IDZhMSAxIDAgMCAwLS44NjQuNDk2bC0yLjkxNyA1LS4wNi4xMmExIDEgMCAwIDAgLjA2Ljg4OGwyLjkxNyA1YTEgMSAwIDAgMCAuNzMyLjQ4N2wuMTMyLjAwOWg5Ljg1MWExIDEgMCAwIDAgLjc5LS4zODdsLjA3My0uMTEgMi45MTctNWExIDEgMCAwIDAgLjA2LS44ODdsLS4wNi0uMTItMi45MTctNWExIDEgMCAwIDAtLjczMS0uNDg3TDE2LjkyNiA2eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7822
 */
export const Icon24ShapeHexagon = memo(function Icon24ShapeHexagon(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M16.926 5a2 2 0 0 1 1.728.992l2.917 5 .063.118c.278.56.278 1.22 0 1.78l-.063.118-2.917 5a2 2 0 0 1-1.728.992H7.075a2 2 0 0 1-1.728-.992l-2.917-5a2 2 0 0 1 0-2.016l2.917-5 .07-.112A2 2 0 0 1 7.075 5zM7.075 6a1 1 0 0 0-.864.496l-2.917 5-.06.12a1 1 0 0 0 .06.888l2.917 5a1 1 0 0 0 .732.487l.132.009h9.851a1 1 0 0 0 .79-.387l.073-.11 2.917-5a1 1 0 0 0 .06-.887l-.06-.12-2.917-5a1 1 0 0 0-.731-.487L16.926 6z"
      />
    </svg>
  )
})
