// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.adjust.tone.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtOS4zNiA2LjIxNC0uNjc0IDIuNDcyLTIuNDczLjY3NGMtMS42Ny40NTYtMS42NyAyLjgyNSAwIDMuMjhsMi40NzMuNjc1LjY3NCAyLjQ3MmMuNDU1IDEuNjcgMi44MjUgMS42NyAzLjI4IDBsLjY3NS0yLjQ3MiAyLjQ3Mi0uNjc0YzEuNjctLjQ1NiAxLjY3LTIuODI1IDAtMy4yOGwtMi40NzItLjY3NS0uNjc1LTIuNDcyYy0uNDU1LTEuNjctMi44MjUtMS42Ny0zLjI4IDBtLjk2NS4yNjNMOS41IDkuNWwtMy4wMjQuODI0Yy0uNjg3LjE4OC0uNjg3IDEuMTYzIDAgMS4zNUw5LjUgMTIuNWwuODI1IDMuMDI0Yy4xODcuNjg4IDEuMTYzLjY4OCAxLjM1IDBsLjgyNS0zLjAyMyAzLjAyNC0uODI1Yy42ODgtLjE4OC42ODgtMS4xNjMgMC0xLjM1TDEyLjUgOS41bC0uODI1LTMuMDI0Yy0uMTg3LS42ODgtMS4xNjMtLjY4OC0xLjM1IDBNMTQuNSAxNGEuNS41IDAgMCAwLS41LjV2MWEuNS41IDAgMCAwIDEgMFYxNWgxdjNoLS41YS41LjUgMCAwIDAgMCAxaDJhLjUuNSAwIDAgMCAwLTFIMTd2LTNoMXYuNWEuNS41IDAgMCAwIDEgMHYtMWEuNS41IDAgMCAwLS41LS41eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-8120
 */
export const Icon24AdjustToneSmall = memo(function Icon24AdjustToneSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m9.36 6.214-.674 2.472-2.473.674c-1.67.456-1.67 2.825 0 3.28l2.473.675.674 2.472c.455 1.67 2.825 1.67 3.28 0l.675-2.472 2.472-.674c1.67-.456 1.67-2.825 0-3.28l-2.472-.675-.675-2.472c-.455-1.67-2.825-1.67-3.28 0m.965.263L9.5 9.5l-3.024.824c-.687.188-.687 1.163 0 1.35L9.5 12.5l.825 3.024c.187.688 1.163.688 1.35 0l.825-3.023 3.024-.825c.688-.188.688-1.163 0-1.35L12.5 9.5l-.825-3.024c-.187-.688-1.163-.688-1.35 0M14.5 14a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 1 0V15h1v3h-.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1H17v-3h1v.5a.5.5 0 0 0 1 0v-1a.5.5 0 0 0-.5-.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
