// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.template
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMy41IDRoOWEuNS41IDAgMCAxIC41LjVWNkgzVjQuNWEuNS41IDAgMCAxIC41LS41TTMgN3Y0LjVhLjUuNSAwIDAgMCAuNS41SDVWN3ptMyA1aDYuNWEuNS41IDAgMCAwIC41LS41VjdINnpNMiA0LjVBMS41IDEuNSAwIDAgMSAzLjUgM2g5QTEuNSAxLjUgMCAwIDEgMTQgNC41djdhMS41IDEuNSAwIDAgMS0xLjUgMS41aC05QTEuNSAxLjUgMCAwIDEgMiAxMS41eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=606-5823
 */
export const Icon16Template = memo(function Icon16Template(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M3.5 4h9a.5.5 0 0 1 .5.5V6H3V4.5a.5.5 0 0 1 .5-.5M3 7v4.5a.5.5 0 0 0 .5.5H5V7zm3 5h6.5a.5.5 0 0 0 .5-.5V7H6zM2 4.5A1.5 1.5 0 0 1 3.5 3h9A1.5 1.5 0 0 1 14 4.5v7a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 11.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
