// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.custom-cursor.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTYuMjkzIDYuMjkzYTEgMSAwIDAgMSAxLjAxMy0uMjQ1bDEwLjY5OSAzLjQzNmExIDEgMCAwIDEgLjY2NCAxLjE5NiAxMS4wMSAxMS4wMSAwIDAgMS03Ljk5IDcuOTg5IDEgMSAwIDAgMS0xLjE5NS0uNjY0bC0zLjQzNi0xMC43YTEgMSAwIDAgMSAuMjQ1LTEuMDEybTkuNDk0IDMuNTNhOCA4IDAgMCAxLTUuOTY1IDUuOTY1bC42MTUgMS45MTFhMTAuMDEgMTAuMDEgMCAwIDAgNy4yNjItNy4yNjN6TTkuNjgyIDE1LjM1bC0uMTY1LS41MTdhNyA3IDAgMCAwIDUuMzE2LTUuMzE2bC41OTYuMTlMNyA3ek0xMSAxMWExIDEgMCAxIDEgMCAyIDEgMSAwIDAgMSAwLTJNOCA5YTEgMSAwIDAgMSAuMjcyIDEuOTYxbC0uNjEtMS45MDFBMSAxIDAgMCAxIDggOW00Ljk5Ni0uMDc0UTEzIDguOTYyIDEzIDlhMSAxIDAgMSAxLTEuNzY4LS42NHoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=4214-8064
 */
export const Icon24CustomCursorSmall = memo(function Icon24CustomCursorSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M6.293 6.293a1 1 0 0 1 1.013-.245l10.699 3.436a1 1 0 0 1 .664 1.196 11.01 11.01 0 0 1-7.99 7.989 1 1 0 0 1-1.195-.664l-3.436-10.7a1 1 0 0 1 .245-1.012m9.494 3.53a8 8 0 0 1-5.965 5.965l.615 1.911a10.01 10.01 0 0 0 7.262-7.263zM9.682 15.35l-.165-.517a7 7 0 0 0 5.316-5.316l.596.19L7 7zM11 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2M8 9a1 1 0 0 1 .272 1.961l-.61-1.901A1 1 0 0 1 8 9m4.996-.074Q13 8.962 13 9a1 1 0 1 1-1.768-.64z"
      />
    </svg>
  )
})
