// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.stroke.both.points.diamond
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDgiIGhlaWdodD0iNjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA1MiAxNiI+CiAgPHJlY3Qgd2lkdGg9IjUyIiBoZWlnaHQ9IjE2IiBmaWxsPSIjMDAwIiByeD0iNCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTUwLjU4NiA3LjUgNDggMTAuMDg2IDQ1LjQxNCA3LjUgNDggNC45MTR6TTQ0LjUgOGwuMjA3LjIwNyAyLjU4NiAyLjU4NmExIDEgMCAwIDAgMS40MTQgMGwyLjU4Ni0yLjU4NmExIDEgMCAwIDAgMC0xLjQxNGwtMi41ODYtMi41ODZhMSAxIDAgMCAwLTEuNDE0IDBsLTIuNTg2IDIuNTg2TDQ0LjUgN2gtMzdsLS4yMDctLjIwNy0yLjU4Ni0yLjU4NmExIDEgMCAwIDAtMS40MTQgMEwuNzA3IDYuNzkzYTEgMSAwIDAgMCAwIDEuNDE0bDIuNTg2IDIuNTg2YTEgMSAwIDAgMCAxLjQxNCAwbDIuNTg2LTIuNTg2TDcuNSA4ek00IDQuOTE0IDEuNDE0IDcuNSA0IDEwLjA4NiA2LjU4NiA3LjV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-14203
 */
export const Icon16StrokeBothPointsDiamond = memo(function Icon16StrokeBothPointsDiamond(
  props: SVGIconProps,
) {
  return (
    <svg width="52" height="16" fill="none" viewBox="0 0 52 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M50.586 7.5 48 10.086 45.414 7.5 48 4.914zM44.5 8l.207.207 2.586 2.586a1 1 0 0 0 1.414 0l2.586-2.586a1 1 0 0 0 0-1.414l-2.586-2.586a1 1 0 0 0-1.414 0l-2.586 2.586L44.5 7h-37l-.207-.207-2.586-2.586a1 1 0 0 0-1.414 0L.707 6.793a1 1 0 0 0 0 1.414l2.586 2.586a1 1 0 0 0 1.414 0l2.586-2.586L7.5 8zM4 4.914 1.414 7.5 4 10.086 6.586 7.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
