// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.figjam.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2LjUgNkExLjUgMS41IDAgMCAxIDE4IDcuNXY1LjM3OWwtLjAwOC4xNDhhMS41IDEuNSAwIDAgMS0uNDMxLjkxM2wtMy42MjEgMy42Mi0uMTEuMWExLjUgMS41IDAgMCAxLS45NTEuMzRINy41bC0uMTUzLS4wMDhBMS41IDEuNSAwIDAgMSA2IDE2LjV2LTlBMS41IDEuNSAwIDAgMSA3LjUgNnptLTkgMWEuNS41IDAgMCAwLS41LjV2OWEuNS41IDAgMCAwIC41LjVIMTJ2LTMuNWExLjUgMS41IDAgMCAxIDEuNS0xLjVIMTdWNy41YS41LjUgMCAwIDAtLjUtLjV6bTYgNmEuNS41IDAgMCAwLS41LjV2My40ODJhLjUuNSAwIDAgMCAuMjMyLS4xMjhsMy42MjItMy42MjJhLjUuNSAwIDAgMCAuMTMtLjIzMnoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11448
 */
export const Icon24FigjamSmall = memo(function Icon24FigjamSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M16.5 6A1.5 1.5 0 0 1 18 7.5v5.379l-.008.148a1.5 1.5 0 0 1-.431.913l-3.621 3.62-.11.1a1.5 1.5 0 0 1-.951.34H7.5l-.153-.008A1.5 1.5 0 0 1 6 16.5v-9A1.5 1.5 0 0 1 7.5 6zm-9 1a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5H12v-3.5a1.5 1.5 0 0 1 1.5-1.5H17V7.5a.5.5 0 0 0-.5-.5zm6 6a.5.5 0 0 0-.5.5v3.482a.5.5 0 0 0 .232-.128l3.622-3.622a.5.5 0 0 0 .13-.232z"
      />
    </svg>
  )
})
