// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.parallelogram.right-lean
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE5LjIxOCA1YTIgMiAwIDAgMSAxLjk4NiAyLjI0OWwtLjA0NS4yMzYtMi40MDUgOS42MjFBMi41IDIuNSAwIDAgMSAxNi4zMjggMTlINC43OGEyIDIgMCAwIDEtMS45NC0yLjQ4NWwyLjQwNS05LjYyMS4wNi0uMjA1QTIuNSAyLjUgMCAwIDEgNy42NzEgNXpNNy42NzEgNmExLjUgMS41IDAgMCAwLTEuNDU2IDEuMTM2TDMuODEgMTYuNzU4bC0uMDIyLjExN2MtLjA3LjU0OC4zMjQgMS4wNTMuODczIDEuMTE4bC4xMi4wMDdoMTEuNTQ4YTEuNSAxLjUgMCAwIDAgMS40MTktMS4wMTRsLjAzNi0uMTIyIDIuNDA1LTkuNjIyYTEgMSAwIDAgMC0uODUtMS4yMzVMMTkuMjE5IDZ6Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7830
 */
export const Icon24ShapeParallelogramRightLean = memo(function Icon24ShapeParallelogramRightLean(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M19.218 5a2 2 0 0 1 1.986 2.249l-.045.236-2.405 9.621A2.5 2.5 0 0 1 16.328 19H4.78a2 2 0 0 1-1.94-2.485l2.405-9.621.06-.205A2.5 2.5 0 0 1 7.671 5zM7.671 6a1.5 1.5 0 0 0-1.456 1.136L3.81 16.758l-.022.117c-.07.548.324 1.053.873 1.118l.12.007h11.548a1.5 1.5 0 0 0 1.419-1.014l.036-.122 2.405-9.622a1 1 0 0 0-.85-1.235L19.219 6z"
      />
    </svg>
  )
})
