// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-set.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi41IDdoMTBhLjUuNSAwIDAgMSAuNS41LjUuNSAwIDAgMCAuNS41Yy4yNiAwIC41LS4xOTMuNS0uNDUzVjcuNUExLjUgMS41IDAgMCAwIDE2LjUgNmgtMTBBMS41IDEuNSAwIDAgMCA1IDcuNXY5QTEuNSAxLjUgMCAwIDAgNi41IDE4aDUuMDQ3Yy4yNiAwIC40NTMtLjI0LjQ1My0uNWEuNS41IDAgMCAwLS41LS41aC01YS41LjUgMCAwIDEtLjUtLjVWMTBoNS43M2MuMTg2IDAgLjM0NS0uMTM3LjQwNS0uMzEzLjEwNS0uMzA2LS4wOTctLjY4Ny0uNDItLjY4N0g2VjcuNWEuNS41IDAgMCAxIC41LS41bTggM2gzYS41LjUgMCAwIDEgLjUuNXY3YS41LjUgMCAwIDEtLjUuNWgtM2EuNS41IDAgMCAxLS41LS41di03YS41LjUgMCAwIDEgLjUtLjVtLTEuNS41QTEuNSAxLjUgMCAwIDEgMTQuNSA5aDNhMS41IDEuNSAwIDAgMSAxLjUgMS41djdhMS41IDEuNSAwIDAgMS0xLjUgMS41aC0zYTEuNSAxLjUgMCAwIDEtMS41LTEuNXptMyA2LjVhLjUuNSAwIDEgMCAwLTEgLjUuNSAwIDAgMCAwIDEiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10435
 */
export const Icon24LayoutSetSmall = memo(function Icon24LayoutSetSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.5 7h10a.5.5 0 0 1 .5.5.5.5 0 0 0 .5.5c.26 0 .5-.193.5-.453V7.5A1.5 1.5 0 0 0 16.5 6h-10A1.5 1.5 0 0 0 5 7.5v9A1.5 1.5 0 0 0 6.5 18h5.047c.26 0 .453-.24.453-.5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 1-.5-.5V10h5.73c.186 0 .345-.137.405-.313.105-.306-.097-.687-.42-.687H6V7.5a.5.5 0 0 1 .5-.5m8 3h3a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5m-1.5.5A1.5 1.5 0 0 1 14.5 9h3a1.5 1.5 0 0 1 1.5 1.5v7a1.5 1.5 0 0 1-1.5 1.5h-3a1.5 1.5 0 0 1-1.5-1.5zm3 6.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1"
        clipRule="evenodd"
      />
    </svg>
  )
})
