// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.code.connect.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAuNDA5IDYuODc0YTMgMyAwIDEgMSA0LjI0MyA0LjI0MmwtMy41MzYgMy41MzZhLjUuNSAwIDAgMCAuNzA3LjcwN2wzLjUzNi0zLjUzNmE0IDQgMCAxIDAtNS42NTctNS42NTdMNi4xNjYgOS43MDJhLjUuNSAwIDEgMCAuNzA3LjcwN3ptLTEuMDYgNi4wMWEzIDMgMCAwIDAgNC4yNDIgNC4yNDNsMy41MzYtMy41MzZhLjUuNSAwIDAgMSAuNzA3LjcwN2wtMy41MzYgMy41MzZhNCA0IDAgMSAxLTUuNjU3LTUuNjU3bDMuNTM2LTMuNTM2YS41LjUgMCAxIDEgLjcwNy43MDd6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10346
 */
export const Icon24CodeConnectSmall = memo(function Icon24CodeConnectSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10.409 6.874a3 3 0 1 1 4.243 4.242l-3.536 3.536a.5.5 0 0 0 .707.707l3.536-3.536a4 4 0 1 0-5.657-5.657L6.166 9.702a.5.5 0 1 0 .707.707zm-1.06 6.01a3 3 0 0 0 4.242 4.243l3.536-3.536a.5.5 0 0 1 .707.707l-3.536 3.536a4 4 0 1 1-5.657-5.657l3.536-3.536a.5.5 0 1 1 .707.707z"
        clipRule="evenodd"
      />
    </svg>
  )
})
