// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-align-vertical-center-group
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTggMTEuNWEuNS41IDAgMCAwLS41LS41SDE1VjkuNzVhLjc1Ljc1IDAgMCAwLS43NS0uNzVoLS41YS43NS43NSAwIDAgMC0uNzUuNzVWMTFoLTNWNy43NUEuNzUuNzUgMCAwIDAgOS4yNSA3aC0uNWEuNzUuNzUgMCAwIDAtLjc1Ljc1VjExSDUuNWEuNS41IDAgMCAwIDAgMUg4djMuMjVjMCAuNDE0LjMzNi43NS43NS43NWguNWEuNzUuNzUgMCAwIDAgLjc1LS43NVYxMmgzdjEuMjVjMCAuNDE0LjMzNi43NS43NS43NWguNWEuNzUuNzUgMCAwIDAgLjc1LS43NVYxMmgyLjVhLjUuNSAwIDAgMCAuNS0uNSIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi4yNSA1QzUuNTYgNSA1IDUuNTYgNSA2LjI1VjguNWEuNS41IDAgMCAwIDEgMFY2LjI1QS4yNS4yNSAwIDAgMSA2LjI1IDZoMTAuNWEuMjUuMjUgMCAwIDEgLjI1LjI1VjguNWEuNS41IDAgMCAwIDEgMFY2LjI1QzE4IDUuNTYgMTcuNDQgNSAxNi43NSA1em0xMC41IDEzYy42OSAwIDEuMjUtLjU2IDEuMjUtMS4yNVYxNC41YS41LjUgMCAwIDAtMSAwdjIuMjVhLjI1LjI1IDAgMCAxLS4yNS4yNUg2LjI1YS4yNS4yNSAwIDAgMS0uMjUtLjI1VjE0LjVhLjUuNSAwIDAgMC0xIDB2Mi4yNWMwIC42OS41NiAxLjI1IDEuMjUgMS4yNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7059
 */
export const Icon24LayoutAlignVerticalCenterGroup = memo(
  function Icon24LayoutAlignVerticalCenterGroup(props: SVGIconProps) {
    return (
      <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
        <path
          fill="var(--color-icon)"
          fillRule="evenodd"
          d="M18 11.5a.5.5 0 0 0-.5-.5H15V9.75a.75.75 0 0 0-.75-.75h-.5a.75.75 0 0 0-.75.75V11h-3V7.75A.75.75 0 0 0 9.25 7h-.5a.75.75 0 0 0-.75.75V11H5.5a.5.5 0 0 0 0 1H8v3.25c0 .414.336.75.75.75h.5a.75.75 0 0 0 .75-.75V12h3v1.25c0 .414.336.75.75.75h.5a.75.75 0 0 0 .75-.75V12h2.5a.5.5 0 0 0 .5-.5"
          clipRule="evenodd"
        />
        <path
          fill="var(--color-icon-tertiary)"
          fillRule="evenodd"
          d="M6.25 5C5.56 5 5 5.56 5 6.25V8.5a.5.5 0 0 0 1 0V6.25A.25.25 0 0 1 6.25 6h10.5a.25.25 0 0 1 .25.25V8.5a.5.5 0 0 0 1 0V6.25C18 5.56 17.44 5 16.75 5zm10.5 13c.69 0 1.25-.56 1.25-1.25V14.5a.5.5 0 0 0-1 0v2.25a.25.25 0 0 1-.25.25H6.25a.25.25 0 0 1-.25-.25V14.5a.5.5 0 0 0-1 0v2.25c0 .69.56 1.25 1.25 1.25z"
          clipRule="evenodd"
        />
      </svg>
    )
  },
)
