// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.create.variant
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTEuODIzIDQuMDkxLTcuNzMyIDcuNzMyYS4yNS4yNSAwIDAgMCAwIC4zNTRsNy43MzIgNy43MzJhLjI1LjI1IDAgMCAwIC4zNTQgMGw3LjczMi03LjczMmEuMjUuMjUgMCAwIDAgMC0uMzU0bC03LjczMi03LjczMmEuMjUuMjUgMCAwIDAtLjM1NCAwbS0uNzA3LS43MDctNy43MzIgNy43MzJhMS4yNSAxLjI1IDAgMCAwIDAgMS43NjhsNy43MzIgNy43MzJhMS4yNSAxLjI1IDAgMCAwIDEuNzY4IDBsNy43MzItNy43MzJhMS4yNSAxLjI1IDAgMCAwIDAtMS43NjhsLTcuNzMyLTcuNzMyYTEuMjUgMS4yNSAwIDAgMC0xLjc2OCAwTTExLjUgOWEuNS41IDAgMSAxIDEgMHYyLjVIMTVhLjUuNSAwIDAgMSAwIDFoLTIuNVYxNWEuNS41IDAgMCAxLTEgMHYtMi41SDlhLjUuNSAwIDAgMSAwLTFoMi41eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3697
 */
export const Icon24CreateVariant = memo(function Icon24CreateVariant(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m11.823 4.091-7.732 7.732a.25.25 0 0 0 0 .354l7.732 7.732a.25.25 0 0 0 .354 0l7.732-7.732a.25.25 0 0 0 0-.354l-7.732-7.732a.25.25 0 0 0-.354 0m-.707-.707-7.732 7.732a1.25 1.25 0 0 0 0 1.768l7.732 7.732a1.25 1.25 0 0 0 1.768 0l7.732-7.732a1.25 1.25 0 0 0 0-1.768l-7.732-7.732a1.25 1.25 0 0 0-1.768 0M11.5 9a.5.5 0 1 1 1 0v2.5H15a.5.5 0 0 1 0 1h-2.5V15a.5.5 0 0 1-1 0v-2.5H9a.5.5 0 0 1 0-1h2.5z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m11.323 4.091-7.232 7.232a.25.25 0 0 0 0 .354l7.232 7.232a.25.25 0 0 0 .354 0l7.232-7.232a.25.25 0 0 0 0-.354l-7.232-7.232a.25.25 0 0 0-.354 0m-.707-.707-7.232 7.232a1.25 1.25 0 0 0 0 1.768l7.232 7.232a1.25 1.25 0 0 0 1.768 0l7.232-7.232a1.25 1.25 0 0 0 0-1.768l-7.232-7.232a1.25 1.25 0 0 0-1.768 0M11 8.5a.5.5 0 0 1 1 0V11h2.5a.5.5 0 1 1 0 1H12v2.5a.5.5 0 1 1-1 0V12H8.5a.5.5 0 0 1 0-1H11z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
