// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.ungroup.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtNi44NTQgMTcuODU0IDExLTExYS41LjUgMCAwIDAtLjcwOC0uNzA4bC0xMSAxMWEuNS41IDAgMCAwIC43MDguNzA4TTcuNSA2QTEuNSAxLjUgMCAwIDAgNiA3LjVhLjUuNSAwIDAgMCAxIDAgLjUuNSAwIDAgMSAuNS0uNS41LjUgMCAwIDAgMC0xbTIgMGEuNS41IDAgMCAwIDAgMUgxMWEuNS41IDAgMCAwIDAtMXptNSAwSDEzYS41LjUgMCAwIDAgMCAxaDEuNWEuNS41IDAgMCAwIDAtMU03IDExVjkuNWEuNS41IDAgMCAwLTEgMFYxMWEuNS41IDAgMCAwIDEgMG0xMSAwVjkuNWEuNS41IDAgMCAwLTEgMFYxMWEuNS41IDAgMCAwIDEgME03IDE0LjVWMTNhLjUuNSAwIDAgMC0xIDB2MS41YS41LjUgMCAwIDAgMSAwbTExIDBWMTNhLjUuNSAwIDAgMC0xIDB2MS41YS41LjUgMCAwIDAgMSAwTTE2LjUgMThhMS41IDEuNSAwIDAgMCAxLjUtMS41LjUuNSAwIDAgMC0xIDAgLjUuNSAwIDAgMS0uNS41LjUuNSAwIDAgMCAwIDFNMTEgMTdIOS41YS41LjUgMCAwIDAgMCAxSDExYS41LjUgMCAwIDAgMC0xbTMuNSAwSDEzYS41LjUgMCAwIDAgMCAxaDEuNWEuNS41IDAgMCAwIDAtMSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10980
 */
export const Icon24UngroupSmall = memo(function Icon24UngroupSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m6.854 17.854 11-11a.5.5 0 0 0-.708-.708l-11 11a.5.5 0 0 0 .708.708M7.5 6A1.5 1.5 0 0 0 6 7.5a.5.5 0 0 0 1 0 .5.5 0 0 1 .5-.5.5.5 0 0 0 0-1m2 0a.5.5 0 0 0 0 1H11a.5.5 0 0 0 0-1zm5 0H13a.5.5 0 0 0 0 1h1.5a.5.5 0 0 0 0-1M7 11V9.5a.5.5 0 0 0-1 0V11a.5.5 0 0 0 1 0m11 0V9.5a.5.5 0 0 0-1 0V11a.5.5 0 0 0 1 0M7 14.5V13a.5.5 0 0 0-1 0v1.5a.5.5 0 0 0 1 0m11 0V13a.5.5 0 0 0-1 0v1.5a.5.5 0 0 0 1 0M16.5 18a1.5 1.5 0 0 0 1.5-1.5.5.5 0 0 0-1 0 .5.5 0 0 1-.5.5.5.5 0 0 0 0 1M11 17H9.5a.5.5 0 0 0 0 1H11a.5.5 0 0 0 0-1m3.5 0H13a.5.5 0 0 0 0 1h1.5a.5.5 0 0 0 0-1"
        clipRule="evenodd"
      />
    </svg>
  )
})
