// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.radius.bottom.left
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTIuNDc4IDE2SDE1LjVhLjUuNSAwIDAgMCAwLTFoLTNjLS43MDggMC0xLjIxIDAtMS42MDEtLjAzMi0uMzg2LS4wMzItLjYyMi0uMDkyLS44MDctLjE4NmEyIDIgMCAwIDEtLjg3NC0uODc0Yy0uMDk0LS4xODUtLjE1NC0uNDItLjE4Ni0uODA3QzkgMTIuNzEgOSAxMi4yMDggOSAxMS41di0zYS41LjUgMCAwIDAtMSAwdjMuMDIyYzAgLjY4MSAwIDEuMjIzLjAzNiAxLjY2LjAzNi40NDguMTEzLjgzLjI5MSAxLjE4YTMgMyAwIDAgMCAxLjMxMSAxLjMxMWMuMzUuMTc4LjczMi4yNTUgMS4xOC4yOTEuNDM3LjAzNi45NzkuMDM2IDEuNjYuMDM2IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5133
 */
export const Icon24RadiusBottomLeft = memo(function Icon24RadiusBottomLeft(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M12.478 16H15.5a.5.5 0 0 0 0-1h-3c-.708 0-1.21 0-1.601-.032-.386-.032-.622-.092-.807-.186a2 2 0 0 1-.874-.874c-.094-.185-.154-.42-.186-.807C9 12.71 9 12.208 9 11.5v-3a.5.5 0 0 0-1 0v3.022c0 .681 0 1.223.036 1.66.036.448.113.83.291 1.18a3 3 0 0 0 1.311 1.311c.35.178.732.255 1.18.291.437.036.979.036 1.66.036"
        clipRule="evenodd"
      />
    </svg>
  )
})
