// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.mobile.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTQgNmgtNGExIDEgMCAwIDAtMSAxdjEwYTEgMSAwIDAgMCAxIDFoNGExIDEgMCAwIDAgMS0xVjdhMSAxIDAgMCAwLTEtMW0tNC0xYTIgMiAwIDAgMC0yIDJ2MTBhMiAyIDAgMCAwIDIgMmg0YTIgMiAwIDAgMCAyLTJWN2EyIDIgMCAwIDAtMi0yem0yLjUgMTEuNWEuNS41IDAgMSAxLTEgMCAuNS41IDAgMCAxIDEgMG0tMS05LjVhLjUuNSAwIDAgMCAwIDFoMWEuNS41IDAgMCAwIDAtMXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-8625
 */
export const Icon24MobileSmall = memo(function Icon24MobileSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M14 6h-4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1m-4-1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2zm2.5 11.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-1-9.5a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  )
})
