// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.diagram
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMjAgNi41YS41LjUgMCAwIDEtLjE0Ni4zNTRsLTMgM2EuNS41IDAgMSAxLS43MDctLjcwOEwxOC4yOTMgN0g5YTIgMiAwIDAgMCAwIDRoNS43NWEzLjI1IDMuMjUgMCAxIDEgMCA2LjVIMTB2LjVhMiAyIDAgMCAxLTIgMkg2YTIgMiAwIDAgMS0yLTJ2LTJhMiAyIDAgMCAxIDItMmgyYTIgMiAwIDAgMSAyIDJ2LjVoNC43NWEyLjI1IDIuMjUgMCAxIDAgMC00LjVIOWEzIDMgMCAxIDEgMC02aDkuMjkzbC0yLjE0Ny0yLjE0NmEuNS41IDAgMCAxIC43MDgtLjcwOGwzIDNBLjUuNSAwIDAgMSAyMCA2LjVNOSAxN3YtMWExIDEgMCAwIDAtMS0xSDZhMSAxIDAgMCAwLTEgMXYyYTEgMSAwIDAgMCAxIDFoMmExIDEgMCAwIDAgMS0xeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-4261
 */
export const Icon24Diagram = memo(function Icon24Diagram(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M20 6.5a.5.5 0 0 1-.146.354l-3 3a.5.5 0 1 1-.707-.708L18.293 7H9a2 2 0 0 0 0 4h5.75a3.25 3.25 0 1 1 0 6.5H10v.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v.5h4.75a2.25 2.25 0 1 0 0-4.5H9a3 3 0 1 1 0-6h9.293l-2.147-2.146a.5.5 0 0 1 .708-.708l3 3A.5.5 0 0 1 20 6.5M9 17v-1a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1z"
        clipRule="evenodd"
      />
    </svg>
  )
})
