// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.moon.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTUgMTVhNiA2IDAgMCAwIDEuMDctLjA5NUE1IDUgMCAxIDEgOS4wOTUgNy45MyA2IDYgMCAwIDAgMTUgMTVtMi4zMDQtLjE5M2MuMzE1LS41OTQtLjQxLTEuMTI5LTEuMDYzLS45NjJhNSA1IDAgMCAxLTYuMDg2LTYuMDg2Yy4xNjctLjY1My0uMzY4LTEuMzc5LS45NjItMS4wNjNhNiA2IDAgMSAwIDguMTExIDguMTEyTTE2IDcuNWEuNS41IDAgMCAwLTEgMFY4aC0uNWEuNS41IDAgMCAwIDAgMWguNXYuNWEuNS41IDAgMCAwIDEgMFY5aC41YS41LjUgMCAwIDAgMC0xSDE2eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2402
 */
export const Icon24MoonSmall = memo(function Icon24MoonSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M15 15a6 6 0 0 0 1.07-.095A5 5 0 1 1 9.095 7.93 6 6 0 0 0 15 15m2.304-.193c.315-.594-.41-1.129-1.063-.962a5 5 0 0 1-6.086-6.086c.167-.653-.368-1.379-.962-1.063a6 6 0 1 0 8.111 8.112M16 7.5a.5.5 0 0 0-1 0V8h-.5a.5.5 0 0 0 0 1h.5v.5a.5.5 0 0 0 1 0V9h.5a.5.5 0 0 0 0-1H16z"
        clipRule="evenodd"
      />
    </svg>
  )
})
