// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-align-bottom-group
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTggMTcuNWEuNS41IDAgMCAwLS41LS41aC0xMmEuNS41IDAgMCAwIDAgMWgxMmEuNS41IDAgMCAwIC41LS41TTkuMjUgN2EuNzUuNzUgMCAwIDEgLjc1Ljc1djYuNWEuNzUuNzUgMCAwIDEtLjc1Ljc1aC0uNWEuNzUuNzUgMCAwIDEtLjc1LS43NXYtNi41QS43NS43NSAwIDAgMSA4Ljc1IDd6bTUgNGEuNzUuNzUgMCAwIDEgLjc1Ljc1djIuNWEuNzUuNzUgMCAwIDEtLjc1Ljc1aC0uNWEuNzUuNzUgMCAwIDEtLjc1LS43NXYtMi41YS43NS43NSAwIDAgMSAuNzUtLjc1eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNSA2LjI1QzUgNS41NiA1LjU2IDUgNi4yNSA1aDEwLjVjLjY5IDAgMS4yNS41NiAxLjI1IDEuMjV2OC4yNWEuNS41IDAgMCAxLTEgMFY2LjI1YS4yNS4yNSAwIDAgMC0uMjUtLjI1SDYuMjVhLjI1LjI1IDAgMCAwLS4yNS4yNXY4LjI1YS41LjUgMCAwIDEtMSAweiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7071
 */
export const Icon24LayoutAlignBottomGroup = memo(function Icon24LayoutAlignBottomGroup(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M18 17.5a.5.5 0 0 0-.5-.5h-12a.5.5 0 0 0 0 1h12a.5.5 0 0 0 .5-.5M9.25 7a.75.75 0 0 1 .75.75v6.5a.75.75 0 0 1-.75.75h-.5a.75.75 0 0 1-.75-.75v-6.5A.75.75 0 0 1 8.75 7zm5 4a.75.75 0 0 1 .75.75v2.5a.75.75 0 0 1-.75.75h-.5a.75.75 0 0 1-.75-.75v-2.5a.75.75 0 0 1 .75-.75z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M5 6.25C5 5.56 5.56 5 6.25 5h10.5c.69 0 1.25.56 1.25 1.25v8.25a.5.5 0 0 1-1 0V6.25a.25.25 0 0 0-.25-.25H6.25a.25.25 0 0 0-.25.25v8.25a.5.5 0 0 1-1 0z"
        clipRule="evenodd"
      />
    </svg>
  )
})
