// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.sidebars.show.default
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNSA2aDE0YTEgMSAwIDAgMSAxIDF2MTBhMSAxIDAgMCAxLTEgMUg1YTEgMSAwIDAgMS0xLTFWN2ExIDEgMCAwIDEgMS0xTTMgN2EyIDIgMCAwIDEgMi0yaDE0YTIgMiAwIDAgMSAyIDJ2MTBhMiAyIDAgMCAxLTIgMkg1YTIgMiAwIDAgMS0yLTJ6bTMuMTQ2IDMuMTQ2YS41LjUgMCAwIDAgMCAuNzA4TDcuMjkzIDEybC0xLjE0NyAxLjE0NmEuNS41IDAgMCAwIC43MDguNzA4bDEuNS0xLjVhLjUuNSAwIDAgMCAwLS43MDhsLTEuNS0xLjVhLjUuNSAwIDAgMC0uNzA4IDBtMTEuNzA4IDBhLjUuNSAwIDAgMSAwIC43MDhMMTYuNzA3IDEybDEuMTQ3IDEuMTQ2YS41LjUgMCAwIDEtLjcwOC43MDhsLTEuNS0xLjVhLjUuNSAwIDAgMSAwLS43MDhsMS41LTEuNWEuNS41IDAgMCAxIC43MDggMCIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10797
 */
export const Icon24SidebarsShowDefault = memo(function Icon24SidebarsShowDefault(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5 6h14a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1M3 7a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zm3.146 3.146a.5.5 0 0 0 0 .708L7.293 12l-1.147 1.146a.5.5 0 0 0 .708.708l1.5-1.5a.5.5 0 0 0 0-.708l-1.5-1.5a.5.5 0 0 0-.708 0m11.708 0a.5.5 0 0 1 0 .708L16.707 12l1.147 1.146a.5.5 0 0 1-.708.708l-1.5-1.5a.5.5 0 0 1 0-.708l1.5-1.5a.5.5 0 0 1 .708 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
