// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.rename
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2LjUgM2EuNS41IDAgMCAxIDAgMUgxNHYxNmgyLjVhLjUuNSAwIDAgMSAwIDFoLTZhLjUuNSAwIDAgMSAwLTFIMTNWNGgtMi41YS41LjUgMCAwIDEgMC0xem0tNSA0YS41LjUgMCAwIDEgMCAxaC03YS41LjUgMCAwIDAtLjUuNXY3YS41LjUgMCAwIDAgLjUuNWg3YS41LjUgMCAwIDEgMCAxaC03QTEuNSAxLjUgMCAwIDEgMyAxNS41di03QTEuNSAxLjUgMCAwIDEgNC41IDd6bTggMEExLjUgMS41IDAgMCAxIDIxIDguNXY3YTEuNSAxLjUgMCAwIDEtMS41IDEuNWgtNGEuNS41IDAgMCAxIDAtMWg0YS41LjUgMCAwIDAgLjUtLjV2LTdhLjUuNSAwIDAgMC0uNS0uNWgtNGEuNS41IDAgMCAxIDAtMXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7740
 */
export const Icon24Rename = memo(function Icon24Rename(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M16.5 3a.5.5 0 0 1 0 1H14v16h2.5a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1H13V4h-2.5a.5.5 0 0 1 0-1zm-5 4a.5.5 0 0 1 0 1h-7a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h7a.5.5 0 0 1 0 1h-7A1.5 1.5 0 0 1 3 15.5v-7A1.5 1.5 0 0 1 4.5 7zm8 0A1.5 1.5 0 0 1 21 8.5v7a1.5 1.5 0 0 1-1.5 1.5h-4a.5.5 0 0 1 0-1h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.5-.5h-4a.5.5 0 0 1 0-1z"
      />
    </svg>
  )
})
