// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.page.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE5IDExLjQxNGExIDEgMCAwIDAtLjI5My0uNzA3bC0zLjQxNC0zLjQxNEExIDEgMCAwIDAgMTQuNTg2IDdINi41QTEuNSAxLjUgMCAwIDAgNSA4LjV2N2wuMDA4LjE1M0ExLjUgMS41IDAgMCAwIDYuNSAxN2gxMWExLjUgMS41IDAgMCAwIDEuNS0xLjV6TTE4IDE1LjVhLjUuNSAwIDAgMS0uNS41aC0xMWEuNS41IDAgMCAxLS41LS41di03YS41LjUgMCAwIDEgLjUtLjVIMTR2Mi41YTEuNSAxLjUgMCAwIDAgMS41IDEuNUgxOHpNMTUuNSAxMWEuNS41IDAgMCAxLS41LS41VjguNDE0TDE3LjU4NiAxMXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7957
 */
export const Icon24ShapePageSmall = memo(function Icon24ShapePageSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M19 11.414a1 1 0 0 0-.293-.707l-3.414-3.414A1 1 0 0 0 14.586 7H6.5A1.5 1.5 0 0 0 5 8.5v7l.008.153A1.5 1.5 0 0 0 6.5 17h11a1.5 1.5 0 0 0 1.5-1.5zM18 15.5a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5H14v2.5a1.5 1.5 0 0 0 1.5 1.5H18zM15.5 11a.5.5 0 0 1-.5-.5V8.414L17.586 11z"
      />
    </svg>
  )
})
