// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.mention
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCAzYTUgNSAwIDAgMCAwIDEwIC41LjUgMCAwIDEgMCAxIDYgNiAwIDEgMSA2LTZ2MWEyIDIgMCAwIDEtMy43NDUuOTc4QTMgMyAwIDEgMSAxMCA1Ljc2M1Y1LjVhLjUuNSAwIDAgMSAxIDBWOWExIDEgMCAxIDAgMiAwVjhhNSA1IDAgMCAwLTUtNW0yIDVhMiAyIDAgMSAwLTQgMCAyIDIgMCAwIDAgNCAwIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13030
 */
export const Icon16Mention = memo(function Icon16Mention(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 3a5 5 0 0 0 0 10 .5.5 0 0 1 0 1 6 6 0 1 1 6-6v1a2 2 0 0 1-3.745.978A3 3 0 1 1 10 5.763V5.5a.5.5 0 0 1 1 0V9a1 1 0 1 0 2 0V8a5 5 0 0 0-5-5m2 5a2 2 0 1 0-4 0 2 2 0 0 0 4 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
