// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.bind.xsmall
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTIuMzc0IDcuNjE4IDMuMjUgMS44N2EuNzUuNzUgMCAwIDEgLjM3Ni42NXYzLjcyNWEuNzUuNzUgMCAwIDEtLjM3Ni42NWwtMy4yNSAxLjg2OGEuNzUuNzUgMCAwIDEtLjc0OCAwbC0zLjI1LTEuODY4YS44LjggMCAwIDEtLjE2Ni0uMTNjLS4xNzYtLjE4Mi0uMzgtLjM4My0uNjM1LS4zODMtLjMwNyAwLS41NTUuMjY4LS40MzQuNTUuMTQ3LjM0NC40MDIuNjM3LjczNy44M2wzLjI1IDEuODY4Yy41NC4zMSAxLjIwNC4zMSAxLjc0NCAwbDMuMjUtMS44NjlBMS43NSAxLjc1IDAgMCAwIDE3IDEzLjg2NHYtMy43MjZhMS43NSAxLjc1IDAgMCAwLS44NzgtMS41MTdsLTMuMjUtMS44NjlhMS43NSAxLjc1IDAgMCAwLTEuNzQ0IDBsLTMuMjUgMS44N2ExLjc1IDEuNzUgMCAwIDAtLjczNy44MjhjLS4xMi4yODIuMTI3LjU1LjQzNC41NS4yNTQgMCAuNDYtLjIuNjM2LS4zODNhLjguOCAwIDAgMSAuMTY1LS4xMjlsMy4yNS0xLjg2OWEuNzUuNzUgMCAwIDEgLjc0OCAwbS0yLjMxIDQuODgyYTIgMiAwIDEgMC0uMDAxLTFINi41YS41LjUgMCAwIDAgMCAxek0xMSAxMmExIDEgMCAxIDEgMiAwIDEgMSAwIDAgMS0yIDAiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5628
 */
export const Icon24BindXsmall = memo(function Icon24BindXsmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m12.374 7.618 3.25 1.87a.75.75 0 0 1 .376.65v3.725a.75.75 0 0 1-.376.65l-3.25 1.868a.75.75 0 0 1-.748 0l-3.25-1.868a.8.8 0 0 1-.166-.13c-.176-.182-.38-.383-.635-.383-.307 0-.555.268-.434.55.147.344.402.637.737.83l3.25 1.868c.54.31 1.204.31 1.744 0l3.25-1.869A1.75 1.75 0 0 0 17 13.864v-3.726a1.75 1.75 0 0 0-.878-1.517l-3.25-1.869a1.75 1.75 0 0 0-1.744 0l-3.25 1.87a1.75 1.75 0 0 0-.737.828c-.12.282.127.55.434.55.254 0 .46-.2.636-.383a.8.8 0 0 1 .165-.129l3.25-1.869a.75.75 0 0 1 .748 0m-2.31 4.882a2 2 0 1 0-.001-1H6.5a.5.5 0 0 0 0 1zM11 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
