// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.shadows
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC41IDJhLjUuNSAwIDAgMSAuNS41di42YTUuMDAyIDUuMDAyIDAgMCAxIDAgOS44di42YS41LjUgMCAwIDEtLjUuNUg4QTYgNiAwIDAgMSA4IDJ6TTggMTJ2MUE1IDUgMCAwIDEgOCAzem0xLTcuODc0djcuNzQ4YTQuMDAyIDQuMDAyIDAgMCAwIDAtNy43NDgiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13606
 */
export const Icon16Shadows = memo(function Icon16Shadows(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8.5 2a.5.5 0 0 1 .5.5v.6a5.002 5.002 0 0 1 0 9.8v.6a.5.5 0 0 1-.5.5H8A6 6 0 0 1 8 2zM8 12v1A5 5 0 0 1 8 3zm1-7.874v7.748a4.002 4.002 0 0 0 0-7.748"
        clipRule="evenodd"
      />
    </svg>
  )
})
