// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.comment
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNC41IDEyaDRBNC41IDQuNSAwIDEgMCA0IDcuNXY0YS41LjUgMCAwIDAgLjUuNW00LTEwQTUuNSA1LjUgMCAwIDAgMyA3LjV2NEExLjUgMS41IDAgMCAwIDQuNSAxM2g0YTUuNSA1LjUgMCAxIDAgMC0xMSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12781
 */
export const Icon16Comment = memo(function Icon16Comment(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M4.5 12h4A4.5 4.5 0 1 0 4 7.5v4a.5.5 0 0 0 .5.5m4-10A5.5 5.5 0 0 0 3 7.5v4A1.5 1.5 0 0 0 4.5 13h4a5.5 5.5 0 1 0 0-11"
        clipRule="evenodd"
      />
    </svg>
  )
})
