// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.variable.mode
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtNy41MDcgMy4yNjkgMi41MzIgMS40OTRhMiAyIDAgMCAxIC45ODMgMS43MjN2My4wMjhhMiAyIDAgMCAxLS45ODMgMS43MjNMNy41MDcgMTIuNzNhMiAyIDAgMCAxLTIuMDM0IDBsLTIuNTMxLTEuNDk0YTIgMiAwIDAgMS0uOTgzLTEuNzIzVjYuNDg2YTIgMiAwIDAgMSAuOTgzLTEuNzIzTDUuNDczIDMuMjdhMiAyIDAgMCAxIDIuMDM0IDBNNyA0LjEyOWExIDEgMCAwIDAtMS4wMTcgMEwzLjQ1IDUuNjI1YTEgMSAwIDAgMC0uNDkxLjg2MnYzLjAyOGExIDEgMCAwIDAgLjQ5MS44NjJsMi41MzIgMS40OTRhMSAxIDAgMCAwIDEuMDE3IDBsMi41MzEtMS40OTRhMSAxIDAgMCAwIC40OTItLjg2MlY2LjQ4NmExIDEgMCAwIDAtLjQ5Mi0uODYyem0zLjUwOCA4LjYwM2EyIDIgMCAwIDEtMi4wMjUuMDA1bDEuMzExLS43NzRhMSAxIDAgMCAwIC4yMDYtLjA5MmwyLjUzMS0xLjQ5NWExIDEgMCAwIDAgLjQ5Mi0uODYxdi0zLjAzYTEgMSAwIDAgMC0uNDkyLS44NkwxMCA0LjEzYTEgMSAwIDAgMC0uMjA2LS4wOTJsLTEuMzExLS43NzRhMiAyIDAgMCAxIDIuMDI1LjAwNWwyLjUzMiAxLjQ5NWEyIDIgMCAwIDEgLjk4MyAxLjcyMnYzLjAyOWEyIDIgMCAwIDEtLjk4MyAxLjcyMnpNNy45OSA0LjcxNWwtLjk4My0uNTh6TTYuNSA5YTEgMSAwIDEgMCAwLTIgMSAxIDAgMCAwIDAgMiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13416
 */
export const Icon16VariableMode = memo(function Icon16VariableMode(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m7.507 3.269 2.532 1.494a2 2 0 0 1 .983 1.723v3.028a2 2 0 0 1-.983 1.723L7.507 12.73a2 2 0 0 1-2.034 0l-2.531-1.494a2 2 0 0 1-.983-1.723V6.486a2 2 0 0 1 .983-1.723L5.473 3.27a2 2 0 0 1 2.034 0M7 4.129a1 1 0 0 0-1.017 0L3.45 5.625a1 1 0 0 0-.491.862v3.028a1 1 0 0 0 .491.862l2.532 1.494a1 1 0 0 0 1.017 0l2.531-1.494a1 1 0 0 0 .492-.862V6.486a1 1 0 0 0-.492-.862zm3.508 8.603a2 2 0 0 1-2.025.005l1.311-.774a1 1 0 0 0 .206-.092l2.531-1.495a1 1 0 0 0 .492-.861v-3.03a1 1 0 0 0-.492-.86L10 4.13a1 1 0 0 0-.206-.092l-1.311-.774a2 2 0 0 1 2.025.005l2.532 1.495a2 2 0 0 1 .983 1.722v3.029a2 2 0 0 1-.983 1.722zM7.99 4.715l-.983-.58zM6.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2"
        clipRule="evenodd"
      />
    </svg>
  )
})
