// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.pages.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTUuMjkzIDUuMjkzQTEgMSAwIDAgMCAxNC41ODYgNUgxMS41QTEuNSAxLjUgMCAwIDAgMTAgNi41djFhLjUuNSAwIDAgMCAxIDB2LTFhLjUuNSAwIDAgMSAuNS0uNUgxNHYxLjVBMS41IDEuNSAwIDAgMCAxNS41IDlIMTd2NC41YS41LjUgMCAwIDEtLjUuNWgtMWEuNS41IDAgMCAwIDAgMWgxYTEuNSAxLjUgMCAwIDAgMS41LTEuNVY4LjQxNGExIDEgMCAwIDAtLjI5My0uNzA3ek0xNi41ODYgOCAxNSA2LjQxNFY3LjVhLjUuNSAwIDAgMCAuNS41ek0xMSAxMS41di0xLjA4NkwxMi41ODYgMTJIMTEuNWEuNS41IDAgMCAxLS41LS41bS0xIDBWMTBINy41YS41LjUgMCAwIDAtLjUuNXY3YS41LjUgMCAwIDAgLjUuNWg1YS41LjUgMCAwIDAgLjUtLjVWMTNoLTEuNWExLjUgMS41IDAgMCAxLTEuNS0xLjVtMS4yOTMtMi4yMDdBMSAxIDAgMCAwIDEwLjU4NiA5SDcuNUExLjUgMS41IDAgMCAwIDYgMTAuNXY3QTEuNSAxLjUgMCAwIDAgNy41IDE5aDVhMS41IDEuNSAwIDAgMCAxLjUtMS41di01LjA4NmExIDEgMCAwIDAtLjI5My0uNzA3eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1616
 */
export const Icon24PagesSmall = memo(function Icon24PagesSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M15.293 5.293A1 1 0 0 0 14.586 5H11.5A1.5 1.5 0 0 0 10 6.5v1a.5.5 0 0 0 1 0v-1a.5.5 0 0 1 .5-.5H14v1.5A1.5 1.5 0 0 0 15.5 9H17v4.5a.5.5 0 0 1-.5.5h-1a.5.5 0 0 0 0 1h1a1.5 1.5 0 0 0 1.5-1.5V8.414a1 1 0 0 0-.293-.707zM16.586 8 15 6.414V7.5a.5.5 0 0 0 .5.5zM11 11.5v-1.086L12.586 12H11.5a.5.5 0 0 1-.5-.5m-1 0V10H7.5a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h5a.5.5 0 0 0 .5-.5V13h-1.5a1.5 1.5 0 0 1-1.5-1.5m1.293-2.207A1 1 0 0 0 10.586 9H7.5A1.5 1.5 0 0 0 6 10.5v7A1.5 1.5 0 0 0 7.5 19h5a1.5 1.5 0 0 0 1.5-1.5v-5.086a1 1 0 0 0-.293-.707z"
        clipRule="evenodd"
      />
    </svg>
  )
})
