// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.ai.outline.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTcgN0g3YTEgMSAwIDAgMC0xIDF2NmExIDEgMCAwIDAgMSAxaDEwYTEgMSAwIDAgMCAxLTFWOGExIDEgMCAwIDAtMS0xTTcgMTZoMS42OGwtLjY2MSAyLjM2NWEuNS41IDAgMCAwIC45NjIuMjdMOS43MiAxNmg0LjU2MmwuNzM3IDIuNjM1YS41LjUgMCAwIDAgLjk2My0uMjdMMTUuMzIgMTZIMTdhMiAyIDAgMCAwIDItMlY4YTIgMiAwIDAgMC0yLTJIN2EyIDIgMCAwIDAtMiAydjZhMiAyIDAgMCAwIDIgMm0xLjUxNS02LjU2LS4yMTUuODYtLjg2LjIxNWMtLjUwNS4xMjYtLjUwNS44NDQgMCAuOTdsLjg2LjIxNS4yMTUuODZjLjEyNi41MDUuODQ0LjUwNS45NyAwbC4yMTUtLjg2Ljg2LS4yMTVjLjUwNS0uMTI2LjUwNS0uODQ0IDAtLjk3TDkuNyAxMC4zbC0uMjE1LS44NmMtLjEyNi0uNTA1LS44NDQtLjUwNS0uOTcgME0xMiA5LjQ5OEEuNS41IDAgMCAxIDEyLjUwMiA5bDMgLjAxNGEuNS41IDAgMSAxLS4wMDQgMWwtMy0uMDE0QS41LjUgMCAwIDEgMTIgOS40OThNMTIuNSAxMmEuNS41IDAgMCAwIDAgMUgxNWEuNS41IDAgMCAwIDAtMXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-8084
 */
export const Icon24AiOutlineSmall = memo(function Icon24AiOutlineSmall(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M17 7H7a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1M7 16h1.68l-.661 2.365a.5.5 0 0 0 .962.27L9.72 16h4.562l.737 2.635a.5.5 0 0 0 .963-.27L15.32 16H17a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2m1.515-6.56-.215.86-.86.215c-.505.126-.505.844 0 .97l.86.215.215.86c.126.505.844.505.97 0l.215-.86.86-.215c.505-.126.505-.844 0-.97L9.7 10.3l-.215-.86c-.126-.505-.844-.505-.97 0M12 9.498A.5.5 0 0 1 12.502 9l3 .014a.5.5 0 1 1-.004 1l-3-.014A.5.5 0 0 1 12 9.498M12.5 12a.5.5 0 0 0 0 1H15a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 8h9a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1M5 9a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-1.409l.39 1.363a.5.5 0 0 1-.962.274L13.551 16H9.45l-.468 1.637a.5.5 0 0 1-.962-.274L8.41 16H7a2 2 0 0 1-2-2zm6 1.498a.5.5 0 0 1 .502-.498l3 .014a.5.5 0 1 1-.004 1l-3-.014a.5.5 0 0 1-.498-.502m-3.1.402.115-.46c.126-.505.844-.505.97 0l.115.46.46.115c.505.126.505.844 0 .97l-.46.115-.115.46c-.126.505-.844.505-.97 0L7.9 12.1l-.46-.115c-.505-.126-.505-.844 0-.97zm3.6 1.114a.5.5 0 1 0 0 1h2a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
