// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.multi.edit
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTQuNSA3LjVBLjUuNSAwIDAgMSAxNSA3aDEuNWEuNS41IDAgMCAxIC41LjVWOWEuNS41IDAgMCAxLTEgMFY4aC0xYS41LjUgMCAwIDEtLjUtLjVNNyA3LjVhLjUuNSAwIDAgMSAuNS0uNUg5YS41LjUgMCAxIDEgMCAxSDh2MWEuNS41IDAgMCAxLTEgMHptLjUgN2EuNS41IDAgMCAxIC41LjV2MWgxYS41LjUgMCAwIDEgMCAxSDcuNWEuNS41IDAgMCAxLS41LS41VjE1YS41LjUgMCAwIDEgLjUtLjVtOSAwYS41LjUgMCAwIDEgLjUuNXYxLjVhLjUuNSAwIDAgMS0uNS41SDE1YS41LjUgMCAwIDEgMC0xaDF2LTFhLjUuNSAwIDAgMSAuNS0uNW0tNi00LjVoLTF2NGgxem0tMS0xYTEgMSAwIDAgMC0xIDF2NGExIDEgMCAwIDAgMSAxaDFhMSAxIDAgMCAwIDEtMXYtNGExIDEgMCAwIDAtMS0xem00IDFoMXY0aC0xem0tMSAwYTEgMSAwIDAgMSAxLTFoMWExIDEgMCAwIDEgMSAxdjRhMSAxIDAgMCAxLTEgMWgtMWExIDEgMCAwIDEtMS0xeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12889
 */
export const Icon16MultiEdit = memo(function Icon16MultiEdit(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M14.5 7.5A.5.5 0 0 1 15 7h1.5a.5.5 0 0 1 .5.5V9a.5.5 0 0 1-1 0V8h-1a.5.5 0 0 1-.5-.5M7 7.5a.5.5 0 0 1 .5-.5H9a.5.5 0 1 1 0 1H8v1a.5.5 0 0 1-1 0zm.5 7a.5.5 0 0 1 .5.5v1h1a.5.5 0 0 1 0 1H7.5a.5.5 0 0 1-.5-.5V15a.5.5 0 0 1 .5-.5m9 0a.5.5 0 0 1 .5.5v1.5a.5.5 0 0 1-.5.5H15a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 .5-.5m-6-4.5h-1v4h1zm-1-1a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1zm4 1h1v4h-1zm-1 0a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-1a1 1 0 0 1-1-1z"
        clipRule="evenodd"
      />
    </svg>
  )
})
