// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.boolean.subtract.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgMTV2Mmg3di03aC0ydjRhMSAxIDAgMCAxLTEgMXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTE3IDE3aC03di0yaDRhMSAxIDAgMCAwIDEtMXYtNGgyem0tNy0zaDRWN0g3djd6bS0zIDFoMnYyYTEgMSAwIDAgMCAxIDFoN2ExIDEgMCAwIDAgMS0xdi03YTEgMSAwIDAgMC0xLTFoLTJWN2ExIDEgMCAwIDAtMS0xSDdhMSAxIDAgMCAwLTEgMXY3YTEgMSAwIDAgMCAxIDEiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3887
 */
export const Icon24BooleanSubtractSmall = memo(function Icon24BooleanSubtractSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M10 15v2h7v-7h-2v4a1 1 0 0 1-1 1z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M17 17h-7v-2h4a1 1 0 0 0 1-1v-4h2zm-7-3h4V7H7v7zm-3 1h2v2a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1v-7a1 1 0 0 0-1-1h-2V7a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1"
        clipRule="evenodd"
      />
    </svg>
  )
})
