// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.frame.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC41IDZhLjUuNSAwIDAgMC0uNS41VjhINi41YS41LjUgMCAwIDAgMCAxSDh2Nkg2LjVhLjUuNSAwIDAgMCAwIDFIOHYxLjVhLjUuNSAwIDAgMCAxIDBWMTZoNnYxLjVhLjUuNSAwIDAgMCAxIDBWMTZoMS41YS41LjUgMCAwIDAgMC0xSDE2VjloMS41YS41LjUgMCAwIDAgMC0xSDE2VjYuNWEuNS41IDAgMCAwLTEgMFY4SDlWNi41YS41LjUgMCAwIDAtLjUtLjVNMTUgOUg5djZoNnoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2703
 */
export const Icon24FrameSmall = memo(function Icon24FrameSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8.5 6a.5.5 0 0 0-.5.5V8H6.5a.5.5 0 0 0 0 1H8v6H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V16h6v1.5a.5.5 0 0 0 1 0V16h1.5a.5.5 0 0 0 0-1H16V9h1.5a.5.5 0 0 0 0-1H16V6.5a.5.5 0 0 0-1 0V8H9V6.5a.5.5 0 0 0-.5-.5M15 9H9v6h6z"
        clipRule="evenodd"
      />
    </svg>
  )
})
