// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.link-connected
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyLjQ0NSAxMC4zNzJhMyAzIDAgMCAxIC42NzcgNC43NDlsLTIgMmEzIDMgMCAwIDEtNC4yNDMtNC4yNDJsMS4yNjktMS4yN2MuMjYyLS4yNjIuNzQ1LS4wNjguODI2LjI5NGEuNDQuNDQgMCAwIDEtLjExMS40MDVsLTEuMjc3IDEuMjc4YTIgMiAwIDEgMCAyLjgyOCAyLjgyOGwyLTJhMiAyIDAgMCAwLS4wMjgtMi44NTZjLS4wOTMtLjA4OC0uMTg2LS4xODItLjIyNC0uMzA1YS44OC44OCAwIDAgMSAuMjItLjg3Mi4wNS4wNSAwIDAgMSAuMDYzLS4wMW0uNTQ0LTMuNmEzIDMgMCAwIDEgNC4xMzEgNC4zNDlsLTEuMjcgMS4yN2MtLjI2MS4yNjItLjc0NS4wNjgtLjgyNS0uMjk0YS40NC40NCAwIDAgMSAuMTExLS40MDRsMS4yNzctMS4yOGEyIDIgMCAxIDAtMi44MjgtMi44MjdsLTIgMmEyIDIgMCAwIDAgMCAyLjgyOGwuMDI4LjAyNmMuMDkyLjA4OC4xODYuMTgzLjIyMy4zMDVhLjg4Ljg4IDAgMCAxLS4xNTkuODA4bC0uMDYuMDY2YS4wNS4wNSAwIDAgMS0uMDYuMDA5IDMgMyAwIDAgMS0uNjc5LTQuNzQ5bDItMnoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5096
 */
export const Icon24LinkConnected = memo(function Icon24LinkConnected(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12.445 10.372a3 3 0 0 1 .677 4.749l-2 2a3 3 0 0 1-4.243-4.242l1.269-1.27c.262-.262.745-.068.826.294a.44.44 0 0 1-.111.405l-1.277 1.278a2 2 0 1 0 2.828 2.828l2-2a2 2 0 0 0-.028-2.856c-.093-.088-.186-.182-.224-.305a.88.88 0 0 1 .22-.872.05.05 0 0 1 .063-.01m.544-3.6a3 3 0 0 1 4.131 4.349l-1.27 1.27c-.261.262-.745.068-.825-.294a.44.44 0 0 1 .111-.404l1.277-1.28a2 2 0 1 0-2.828-2.827l-2 2a2 2 0 0 0 0 2.828l.028.026c.092.088.186.183.223.305a.88.88 0 0 1-.159.808l-.06.066a.05.05 0 0 1-.06.009 3 3 0 0 1-.679-4.749l2-2z"
      />
    </svg>
  )
})
