// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.mask.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTggMTJhNiA2IDAgMCAxLTguNSA1LjQ1NiA2LjAwMSA2LjAwMSAwIDAgMCAwLTEwLjkxMkE2IDYgMCAwIDEgMTggMTJNNiAxMmE1Ljk5IDUuOTkgMCAwIDEgMi40MDEtNC44MDEgNS4wMDMgNS4wMDMgMCAwIDEgMCA5LjYwMkE1Ljk5IDUuOTkgMCAwIDEgNiAxMm0yLjItNS44OGE3IDcgMCAxIDAgNy42IDExLjc2QTcgNyAwIDAgMCA4LjIgNi4xMiIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC40IDE2LjhhNS4wMDIgNS4wMDIgMCAwIDAgLjAwMS05LjYwMkE1Ljk5IDUuOTkgMCAwIDAgNiAxMmE1Ljk5IDUuOTkgMCAwIDAgMi40IDQuOCIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3826
 */
export const Icon24MaskSmall = memo(function Icon24MaskSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M18 12a6 6 0 0 1-8.5 5.456 6.001 6.001 0 0 0 0-10.912A6 6 0 0 1 18 12M6 12a5.99 5.99 0 0 1 2.401-4.801 5.003 5.003 0 0 1 0 9.602A5.99 5.99 0 0 1 6 12m2.2-5.88a7 7 0 1 0 7.6 11.76A7 7 0 0 0 8.2 6.12"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M8.4 16.8a5.002 5.002 0 0 0 .001-9.602A5.99 5.99 0 0 0 6 12a5.99 5.99 0 0 0 2.4 4.8"
        clipRule="evenodd"
      />
    </svg>
  )
})
