// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-align-top
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgMTcuMjVhLjc1Ljc1IDAgMCAxLS43NS43NWgtLjVhLjc1Ljc1IDAgMCAxLS43NS0uNzV2LTguNUEuNzUuNzUgMCAwIDEgOC43NSA4aC41YS43NS43NSAwIDAgMSAuNzUuNzV6bTUtNGEuNzUuNzUgMCAwIDEtLjc1Ljc1aC0uNWEuNzUuNzUgMCAwIDEtLjc1LS43NXYtNC41YS43NS43NSAwIDAgMSAuNzUtLjc1aC41YS43NS43NSAwIDAgMSAuNzUuNzV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBkPSJNMTcuNSA2YS41LjUgMCAwIDAgMC0xaC0xMmEuNS41IDAgMCAwIDAgMXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6984
 */
export const Icon24LayoutAlignTop = memo(function Icon24LayoutAlignTop(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 17.25a.75.75 0 0 1-.75.75h-.5a.75.75 0 0 1-.75-.75v-8.5A.75.75 0 0 1 8.75 8h.5a.75.75 0 0 1 .75.75zm5-4a.75.75 0 0 1-.75.75h-.5a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 1 .75-.75h.5a.75.75 0 0 1 .75.75z"
        clipRule="evenodd"
      />
      <path fill="var(--color-icon-tertiary)" d="M17.5 6a.5.5 0 0 0 0-1h-12a.5.5 0 0 0 0 1z" />
    </svg>
  )
})
