// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.animate
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy41IDdhLjUuNSAwIDAgMCAwIDFoNGEuNS41IDAgMCAwIDAtMXptLTQgM2EuNS41IDAgMCAwIDAgMWg2YS41LjUgMCAwIDAgMC0xem0wIDNhLjUuNSAwIDAgMCAwIDFoNmEuNS41IDAgMCAwIDAtMXptNCAzYS41LjUgMCAwIDAgMCAxaDRhLjUuNSAwIDAgMCAwLTF6TTIwIDEyYTQgNCAwIDEgMS04IDAgNCA0IDAgMCAxIDggMG0xIDBhNSA1IDAgMSAxLTEwIDAgNSA1IDAgMCAxIDEwIDAiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2105
 */
export const Icon24Animate = memo(function Icon24Animate(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7.5 7a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm-4 3a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1zm4 3a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zM20 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0m1 0a5 5 0 1 1-10 0 5 5 0 0 1 10 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
