// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.32.design.new.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDMyIDMyIj4KICA8cmVjdCB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzBkOTlmZiIgZD0iTTAgNWE1IDUgMCAwIDEgNS01aDIyYTUgNSAwIDAgMSA1IDV2MjJhNSA1IDAgMCAxLTUgNUg1YTUgNSAwIDAgMS01LTV6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2LjExIDE4LjA1MmMtLjQ2My0xLjE4My42NTQtMi4zNDcgMS44MzEtMS45ODRsLjExNS4wNCA1Ljk4MSAyLjM1LjEyLjA1MmMxLjE5NC41ODMgMS4wODggMi4zNzEtLjIyNSAyLjc3N2gtLjAwMWwtMi4wMi42MjEtLjYyMSAyLjAyYy0uNDE5IDEuMzU3LTIuMzEgMS40MjUtMi44My4xMDZ6bTYuNTQzLTEwLjA0NEExLjUgMS41IDAgMCAxIDI0IDkuNXYybC0uMDA4LjE1M2ExLjUgMS41IDAgMCAxLTEuMzM5IDEuMzRMMjIuNSAxM0gxM3Y5LjVsLS4wMDguMTUzYTEuNSAxLjUgMCAwIDEtMS4zMzkgMS4zNEwxMS41IDI0aC0ybC0uMTUzLS4wMDhhMS41IDEuNSAwIDAgMS0xLjM0LTEuMzM5TDggMjIuNXYtMTNhMS41IDEuNSAwIDAgMSAxLjM0Ny0xLjQ5Mkw5LjUgOGgxM3ptLTQuOTYzIDkuMDMxYS41LjUgMCAwIDAtLjY0OC42NDdsMi4zNSA1Ljk4M2EuNS41IDAgMCAwIC45MS4wNDRsLjAzMy0uMDguNzc3LTIuNTI0IDIuNTI1LS43NzdhLjUwMS41MDEgMCAwIDAgLjExMi0uOTA2bC0uMDc3LS4wMzd6TTkgMjIuNWEuNS41IDAgMCAwIC41LjVoMmEuNS41IDAgMCAwIC41LS41VjIwaC0xYS41LjUgMCAwIDEgMC0xaDF2LTJoLTFhLjUuNSAwIDAgMSAwLTFoMXYtM0g5ek05LjUgOWEuNS41IDAgMCAwLS41LjVWMTJoM1Y5em0zLjUgM2gzdi0xYS41LjUgMCAwIDEgMSAwdjFoMnYtMWEuNS41IDAgMCAxIDEgMHYxaDIuNWEuNS41IDAgMCAwIC41LS41di0yYS41LjUgMCAwIDAtLjUtLjVIMTN6Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=7584-16694
 */
export const Icon32DesignNewFavicon = memo(function Icon32DesignNewFavicon(props: SVGIconProps) {
  return (
    <ColorTheme brand="design">
      <svg width="32" height="32" fill="none" viewBox="0 0 32 32" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 5a5 5 0 0 1 5-5h22a5 5 0 0 1 5 5v22a5 5 0 0 1-5 5H5a5 5 0 0 1-5-5z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M16.11 18.052c-.463-1.183.654-2.347 1.831-1.984l.115.04 5.981 2.35.12.052c1.194.583 1.088 2.371-.225 2.777h-.001l-2.02.621-.621 2.02c-.419 1.357-2.31 1.425-2.83.106zm6.543-10.044A1.5 1.5 0 0 1 24 9.5v2l-.008.153a1.5 1.5 0 0 1-1.339 1.34L22.5 13H13v9.5l-.008.153a1.5 1.5 0 0 1-1.339 1.34L11.5 24h-2l-.153-.008a1.5 1.5 0 0 1-1.34-1.339L8 22.5v-13a1.5 1.5 0 0 1 1.347-1.492L9.5 8h13zm-4.963 9.031a.5.5 0 0 0-.648.647l2.35 5.983a.5.5 0 0 0 .91.044l.033-.08.777-2.524 2.525-.777a.501.501 0 0 0 .112-.906l-.077-.037zM9 22.5a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5V20h-1a.5.5 0 0 1 0-1h1v-2h-1a.5.5 0 0 1 0-1h1v-3H9zM9.5 9a.5.5 0 0 0-.5.5V12h3V9zm3.5 3h3v-1a.5.5 0 0 1 1 0v1h2v-1a.5.5 0 0 1 1 0v1h2.5a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5H13z"
        />
      </svg>
    </ColorTheme>
  )
})
