// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.typewriter.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTkuNTggNy4wMDZjLjE4Mi4wMy4zMzUuMTU3LjM5NS4zMzZsMyA5IC4wMjEuMDk4YS41LjUgMCAwIDEtLjkyOC4zMWwtLjA0Mi0uMDkyTDExLjE0IDE0SDYuODZsLS44ODUgMi42NThhLjUuNSAwIDAgMS0uOTUtLjMxNmwzLjAwMi05IC4wMy0uMDczQS41LjUgMCAwIDEgOC41IDdoMXpNMTguNSAxNmEuNS41IDAgMCAxIDAgMWgtNGEuNS41IDAgMSAxIDAtMXpNNy4xOTUgMTNoMy42MTJMOS4xNCA4aC0uMjh6Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=4214-7879
 */
export const Icon24TypewriterSmall = memo(function Icon24TypewriterSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M9.58 7.006c.182.03.335.157.395.336l3 9 .021.098a.5.5 0 0 1-.928.31l-.042-.092L11.14 14H6.86l-.885 2.658a.5.5 0 0 1-.95-.316l3.002-9 .03-.073A.5.5 0 0 1 8.5 7h1zM18.5 16a.5.5 0 0 1 0 1h-4a.5.5 0 1 1 0-1zM7.195 13h3.612L9.14 8h-.28z"
      />
    </svg>
  )
})
