// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.wand.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS41IDVhLjUuNSAwIDAgMC0uNS41VjlINS41YS41LjUgMCAwIDAgMCAxSDl2My41YS41LjUgMCAwIDAgMSAwVjEwaDMuNWEuNS41IDAgMCAwIDAtMUgxMFY1LjVhLjUuNSAwIDAgMC0uNS0uNU0xNCA2YTEgMSAwIDEgMS0yIDAgMSAxIDAgMCAxIDIgME02IDdhMSAxIDAgMSAwIDAtMiAxIDEgMCAwIDAgMCAybTEgNmExIDEgMCAxIDEtMiAwIDEgMSAwIDAgMSAyIDBtMTEuODU0IDUuMTQ2LTYuNS02LjVhLjUuNSAwIDAgMC0uNzA4LjcwOGw2LjUgNi41YS41LjUgMCAwIDAgLjcwOC0uNzA4IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7820
 */
export const Icon24WandSmall = memo(function Icon24WandSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9.5 5a.5.5 0 0 0-.5.5V9H5.5a.5.5 0 0 0 0 1H9v3.5a.5.5 0 0 0 1 0V10h3.5a.5.5 0 0 0 0-1H10V5.5a.5.5 0 0 0-.5-.5M14 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0M6 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2m1 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0m11.854 5.146-6.5-6.5a.5.5 0 0 0-.708.708l6.5 6.5a.5.5 0 0 0 .708-.708"
        clipRule="evenodd"
      />
    </svg>
  )
})
