// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.mic.mute
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTQgNnYxLjg3OWwxLTFWNmEzIDMgMCAxIDAtNiAwdjVjMCAuNTQuMTQzIDEuMDQ4LjM5MyAxLjQ4NmwuNzQ4LS43NDhBMiAyIDAgMCAxIDEwIDExVjZhMiAyIDAgMSAxIDQgMG0uOTk4IDUuMTI0LTIuODc0IDIuODc0YTMgMyAwIDAgMCAyLjg3NC0yLjg3NE03IDExLjE2N2MwIDEuMDQ4LjMzNCAyLjAxOS45MDEgMi44MWwtLjcxNS43MTZBNS44IDUuOCAwIDAgMSA2IDExLjE2N1YxMWEuNS41IDAgMCAxIDEgMHptMy4zNTIgNC42MDItLjc3Ny43NzhhNS44IDUuOCAwIDAgMCAxLjkyNS40NDRWMjBoLTNhLjUuNSAwIDAgMCAwIDFoN2EuNS41IDAgMCAwIDAtMWgtM3YtMy4wMWE1LjgzMyA1LjgzMyAwIDAgMCA1LjUtNS44MjNWMTFhLjUuNSAwIDAgMC0xIDB2LjE2N0E0LjgzMyA0LjgzMyAwIDAgMSAxMi4xNjcgMTZoLS4zMzRhNC44IDQuOCAwIDAgMS0xLjQ4LS4yMzFtOS41MDItMTAuOTE1YS41LjUgMCAwIDAtLjcwOC0uNzA4bC0xNSAxNWEuNS41IDAgMCAwIC43MDguNzA4eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-4441
 */
export const Icon24MicMute = memo(function Icon24MicMute(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M14 6v1.879l1-1V6a3 3 0 1 0-6 0v5c0 .54.143 1.048.393 1.486l.748-.748A2 2 0 0 1 10 11V6a2 2 0 1 1 4 0m.998 5.124-2.874 2.874a3 3 0 0 0 2.874-2.874M7 11.167c0 1.048.334 2.019.901 2.81l-.715.716A5.8 5.8 0 0 1 6 11.167V11a.5.5 0 0 1 1 0zm3.352 4.602-.777.778a5.8 5.8 0 0 0 1.925.444V20h-3a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-3v-3.01a5.833 5.833 0 0 0 5.5-5.823V11a.5.5 0 0 0-1 0v.167A4.833 4.833 0 0 1 12.167 16h-.334a4.8 4.8 0 0 1-1.48-.231m9.502-10.915a.5.5 0 0 0-.708-.708l-15 15a.5.5 0 0 0 .708.708z"
        clipRule="evenodd"
      />
    </svg>
  )
})
