// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.manual-input.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0ibTcuNjIxIDUuMTE1LjE3My4wMjQgOSAxLjguMTI5LjAzMkExLjUgMS41IDAgMCAxIDE4IDguNDExdjguMDlhMS41IDEuNSAwIDAgMS0xLjUgMS41aC05QTEuNSAxLjUgMCAwIDEgNiAxNi41VjYuNjFhMS41IDEuNSAwIDAgMSAxLjYyMS0xLjQ5Nm0tLjAyMyAxLjAwNEEuNS41IDAgMCAwIDcgNi42MTF2OS44OWMwIC4yNC4xNzIuNDQzLjQuNDlsLjEuMDFoOWEuNS41IDAgMCAwIC40OS0uNGwuMDEtLjFWOC40MWEuNS41IDAgMCAwLS4zMTctLjQ2NmwtLjA4NS0uMDI1eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7818
 */
export const Icon24ShapeManualInputSmall = memo(function Icon24ShapeManualInputSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="m7.621 5.115.173.024 9 1.8.129.032A1.5 1.5 0 0 1 18 8.411v8.09a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 6 16.5V6.61a1.5 1.5 0 0 1 1.621-1.496m-.023 1.004A.5.5 0 0 0 7 6.611v9.89c0 .24.172.443.4.49l.1.01h9a.5.5 0 0 0 .49-.4l.01-.1V8.41a.5.5 0 0 0-.317-.466l-.085-.025z"
      />
    </svg>
  )
})
