// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.h2
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyA2LjVhLjUuNSAwIDAgMC0xIDB2MTFhLjUuNSAwIDAgMCAxIDBWMTJoNnY1LjVhLjUuNSAwIDAgMCAxIDB2LTExYS41LjUgMCAwIDAtMSAwVjExSDd6bTkuMDM0IDEwLjk1MmMwIC4zMDMuMjQ1LjU0OC41NDguNTQ4aDIuOTdhLjQ0OC40NDggMCAwIDAgMC0uODk2SDE3LjQ4di0uMDRsLjk5Ny0xLjAzOHEuNTYyLS41NTUuODczLS45NDUuMzE0LS4zOS40MzgtLjcxMXQuMTI0LS42NTNxMC0uNDk3LS4yNDUtLjg4NWExLjcgMS43IDAgMCAwLS42ODQtLjYxQTIuMjQgMi4yNCAwIDAgMCAxNy45NiAxMmEyLjIgMi4yIDAgMCAwLTEuMDE3LjIyOCAxLjcxIDEuNzEgMCAwIDAtLjg4OCAxLjEzYy0uMDY0LjI2OC4xNjguNDk1LjQ0NC40OTUuMjc1IDAgLjQ3OS0uMjM2LjU5NS0uNDg1bC4wMTktLjAzOXEuMTItLjIyLjMzMy0uMzM4YTEgMSAwIDAgMSAuNS0uMTIxcS4yNzggMCAuNDk1LjExYS44My44MyAwIDAgMSAuMzQxLjMxMi45LjkgMCAwIDEgLjEyNS40OHEwIC4yNDUtLjA5Ni40NjJ0LS4yODguNDQ4LS40OC41MjlsLTEuODUgMS44NTRhLjU1LjU1IDAgMCAwLS4xNi4zODciIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6787
 */
export const Icon24H2 = memo(function Icon24H2(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 6.5a.5.5 0 0 0-1 0v11a.5.5 0 0 0 1 0V12h6v5.5a.5.5 0 0 0 1 0v-11a.5.5 0 0 0-1 0V11H7zm9.034 10.952c0 .303.245.548.548.548h2.97a.448.448 0 0 0 0-.896H17.48v-.04l.997-1.038q.562-.555.873-.945.314-.39.438-.711t.124-.653q0-.497-.245-.885a1.7 1.7 0 0 0-.684-.61A2.24 2.24 0 0 0 17.96 12a2.2 2.2 0 0 0-1.017.228 1.71 1.71 0 0 0-.888 1.13c-.064.268.168.495.444.495.275 0 .479-.236.595-.485l.019-.039q.12-.22.333-.338a1 1 0 0 1 .5-.121q.278 0 .495.11a.83.83 0 0 1 .341.312.9.9 0 0 1 .125.48q0 .245-.096.462t-.288.448-.48.529l-1.85 1.854a.55.55 0 0 0-.16.387"
        clipRule="evenodd"
      />
    </svg>
  )
})
