// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.pentagon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEwLjI0NyA0LjAzYTMgMyAwIDAgMSAzLjUwNSAwbDUuMjE2IDMuNzU1YTMgMyAwIDAgMSAxLjEwOSAzLjMzOGwtMS44MjYgNS43OGEzIDMgMCAwIDEtMi44NiAyLjA5OEg4LjYwOGEzIDMgMCAwIDEtMi43NzgtMS44NjhsLS4wODItLjIzLTEuODI2LTUuNzhBMyAzIDAgMCAxIDUuMDMgNy43ODV6bTIuOTIuODExYTIgMiAwIDAgMC0yLjMzNiAwTDUuNjE1IDguNTk2bC0uMTI3LjFhMiAyIDAgMCAwLS42MTIgMi4xMjZMNi43IDE2LjYwM2EyIDIgMCAwIDAgMS43NDUgMS4zOWwuMTYyLjAwOGg2Ljc4M2wuMTYyLS4wMDdhMiAyIDAgMCAwIDEuNjktMS4yMzhsLjA1NS0uMTUzIDEuODI2LTUuNzgxYTIgMiAwIDAgMC0uNjEzLTIuMTI2bC0uMTI3LS4xeiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7962
 */
export const Icon24ShapePentagon = memo(function Icon24ShapePentagon(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M10.247 4.03a3 3 0 0 1 3.505 0l5.216 3.755a3 3 0 0 1 1.109 3.338l-1.826 5.78a3 3 0 0 1-2.86 2.098H8.608a3 3 0 0 1-2.778-1.868l-.082-.23-1.826-5.78A3 3 0 0 1 5.03 7.785zm2.92.811a2 2 0 0 0-2.336 0L5.615 8.596l-.127.1a2 2 0 0 0-.612 2.126L6.7 16.603a2 2 0 0 0 1.745 1.39l.162.008h6.783l.162-.007a2 2 0 0 0 1.69-1.238l.055-.153 1.826-5.781a2 2 0 0 0-.613-2.126l-.127-.1z"
      />
    </svg>
  )
})
