// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.edit-object
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS44NyAyLjcyNGExIDEgMCAwIDEgMS4zMzcuMDY5bDIgMiAuMDY4LjA3NmExIDEgMCAwIDEtLjA2OCAxLjMzOGwtNi41IDYuNUExIDEgMCAwIDEgNiAxM0g0YTEgMSAwIDAgMS0xLTF2LTJhMSAxIDAgMCAxIC4yOTMtLjcwN2w2LjUtNi41ek00IDEyaDJsLjY0Ni0uNjQ3LTItMiAuNzA4LS43MDcgMiAyIDMuMjkyLTMuMjkzLTItMkw0IDEwem04LjUtNi41LTEuMTQ2IDEuMTQ2LTItMkwxMC41IDMuNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3286-10367
 */
export const Icon16EditObject = memo(function Icon16EditObject(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9.87 2.724a1 1 0 0 1 1.337.069l2 2 .068.076a1 1 0 0 1-.068 1.338l-6.5 6.5A1 1 0 0 1 6 13H4a1 1 0 0 1-1-1v-2a1 1 0 0 1 .293-.707l6.5-6.5zM4 12h2l.646-.647-2-2 .708-.707 2 2 3.292-3.293-2-2L4 10zm8.5-6.5-1.146 1.146-2-2L10.5 3.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
