// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.branch
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTYuNSA1QTMuNSAzLjUgMCAwIDEgMTAgOC41djZhMi41IDIuNSAwIDAgMCAyLjUgMi41aDUuNzkzbC0xLjE0Ni0xLjE0Ni0uMDY1LS4wNzlhLjUuNSAwIDAgMSAuNjkzLS42OTNsLjA3OS4wNjQgMiAyIC4wNjQuMDc5YS41LjUgMCAwIDEtLjA2NC42MjhsLTIgMmEuNS41IDAgMSAxLS43MDctLjcwN0wxOC4yOTMgMThIMTIuNUEzLjUgMy41IDAgMCAxIDkgMTQuNXYtNkEyLjUgMi41IDAgMCAwIDYuNSA2aC0zYS41LjUgMCAwIDEgMC0xem0xMyAwYS41LjUgMCAwIDEgMCAxaC01YS41LjUgMCAwIDEgMC0xeiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=7584-16935
 */
export const Icon24Branch = memo(function Icon24Branch(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M6.5 5A3.5 3.5 0 0 1 10 8.5v6a2.5 2.5 0 0 0 2.5 2.5h5.793l-1.146-1.146-.065-.079a.5.5 0 0 1 .693-.693l.079.064 2 2 .064.079a.5.5 0 0 1-.064.628l-2 2a.5.5 0 1 1-.707-.707L18.293 18H12.5A3.5 3.5 0 0 1 9 14.5v-6A2.5 2.5 0 0 0 6.5 6h-3a.5.5 0 0 1 0-1zm13 0a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1z"
      />
    </svg>
  )
})
