// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.sites.viewer.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzRkNDlmYyIgZD0iTTAgNWE1IDUgMCAwIDEgNS01aDE0YTUgNSAwIDAgMSA1IDV2MTRhNSA1IDAgMCAxLTUgNUg1YTUgNSAwIDAgMS01LTV6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTggNy44MDRjMC0xLjM4OSAxLjU0LTIuMjI1IDIuNzA0LTEuNDY4bDYuNjUgNC4zMjJhMS42IDEuNiAwIDAgMSAwIDIuNjg0bC02LjY1IDQuMzIyQzkuNTQgMTguNDIgOCAxNy41ODQgOCAxNi4xOTZ6bTIuMTYtLjYzYS43NS43NSAwIDAgMC0xLjE2LjYzdjguMzkyYS43NS43NSAwIDAgMCAxLjE2LjYzbDYuNjQ5LTQuMzIzYS42LjYgMCAwIDAgMC0xLjAwNnoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=7584-9529
 */
export const Icon24SitesViewerFavicon = memo(function Icon24SitesViewerFavicon(
  props: SVGIconProps,
) {
  return (
    <ColorTheme brand="seascape">
      <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 5a5 5 0 0 1 5-5h14a5 5 0 0 1 5 5v14a5 5 0 0 1-5 5H5a5 5 0 0 1-5-5z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M8 7.804c0-1.389 1.54-2.225 2.704-1.468l6.65 4.322a1.6 1.6 0 0 1 0 2.684l-6.65 4.322C9.54 18.42 8 17.584 8 16.196zm2.16-.63a.75.75 0 0 0-1.16.63v8.392a.75.75 0 0 0 1.16.63l6.649-4.323a.6.6 0 0 0 0-1.006z"
        />
      </svg>
    </ColorTheme>
  )
})
