// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.ai.summarize.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtNi4xOCA0Ljc4MS0uMjggMS4xMi0xLjEyLjI4Yy0uMzMzLjA4My0uMzMzLjU1NiAwIC42NGwxLjEyLjI4LjI4IDEuMTE5Yy4wODMuMzMzLjU1Ny4zMzMuNjQgMEw3LjEgNy4xbDEuMTItLjI4Yy4zMzMtLjA4My4zMzMtLjU1NiAwLS42NEw3LjEgNS45bC0uMjgtMS4xMTljLS4wODMtLjMzMy0uNTU3LS4zMzMtLjY0IDBtNC4zMiAxLjIyYS41LjUgMCAxIDAgMCAxaDhhLjUuNSAwIDAgMCAwLTF6bTAgNWEuNS41IDAgMSAwIDAgMWg4YS41LjUgMCAwIDAgMC0xem0wIDVhLjUuNSAwIDEgMCAwIDFoOGEuNS41IDAgMCAwIDAtMXpNNi4xOCA5Ljc4IDUuOSAxMC45bC0xLjEyLjI4Yy0uMzMzLjA4My0uMzMzLjU1NiAwIC42NGwxLjEyLjI4LjI4IDEuMTE5Yy4wODMuMzMzLjU1Ny4zMzMuNjQgMGwuMjgtMS4xMiAxLjEyLS4yOGMuMzMzLS4wODMuMzMzLS41NTYgMC0uNjRMNy4xIDEwLjlsLS4yOC0xLjExOWMtLjA4My0uMzMzLS41NTctLjMzMy0uNjQgMG0tLjI4IDYuMTIuMjgtMS4xMmMuMDgzLS4zMzMuNTU3LS4zMzMuNjQgMGwuMjggMS4xMiAxLjEyLjI4Yy4zMzMuMDgzLjMzMy41NTYgMCAuNjRsLTEuMTIuMjgtLjI4IDEuMTE5Yy0uMDgzLjMzMy0uNTU3LjMzMy0uNjQgMEw1LjkgMTcuMWwtMS4xMi0uMjhjLS4zMzMtLjA4My0uMzMzLS41NTYgMC0uNjR6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7752
 */
export const Icon24AiSummarizeSmall = memo(function Icon24AiSummarizeSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m6.18 4.781-.28 1.12-1.12.28c-.333.083-.333.556 0 .64l1.12.28.28 1.119c.083.333.557.333.64 0L7.1 7.1l1.12-.28c.333-.083.333-.556 0-.64L7.1 5.9l-.28-1.119c-.083-.333-.557-.333-.64 0m4.32 1.22a.5.5 0 1 0 0 1h8a.5.5 0 0 0 0-1zm0 5a.5.5 0 1 0 0 1h8a.5.5 0 0 0 0-1zm0 5a.5.5 0 1 0 0 1h8a.5.5 0 0 0 0-1zM6.18 9.78 5.9 10.9l-1.12.28c-.333.083-.333.556 0 .64l1.12.28.28 1.119c.083.333.557.333.64 0l.28-1.12 1.12-.28c.333-.083.333-.556 0-.64L7.1 10.9l-.28-1.119c-.083-.333-.557-.333-.64 0m-.28 6.12.28-1.12c.083-.333.557-.333.64 0l.28 1.12 1.12.28c.333.083.333.556 0 .64l-1.12.28-.28 1.119c-.083.333-.557.333-.64 0L5.9 17.1l-1.12-.28c-.333-.083-.333-.556 0-.64z"
        clipRule="evenodd"
      />
    </svg>
  )
})
