// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.autolayout.absolute.position
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMCAxYTEgMSAwIDAgMSAxLTFoMi41YS41LjUgMCAwIDEgMCAxSDF2Mi41YS41LjUgMCAwIDEtMSAwem0xNiAwYTEgMSAwIDAgMC0xLTFoLTIuNWEuNS41IDAgMCAwIDAgMUgxNXYyLjVhLjUuNSAwIDAgMCAxIDB6TTEgMTZhMSAxIDAgMCAxLTEtMXYtMi41YS41LjUgMCAwIDEgMSAwVjE1aDIuNWEuNS41IDAgMCAxIDAgMXptMTUtMWExIDEgMCAwIDEtMSAxaC0yLjVhLjUuNSAwIDAgMSAwLTFIMTV2LTIuNWEuNS41IDAgMCAxIDEgMHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12512
 */
export const Icon16AutolayoutAbsolutePosition = memo(function Icon16AutolayoutAbsolutePosition(
  props: SVGIconProps,
) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M0 1a1 1 0 0 1 1-1h2.5a.5.5 0 0 1 0 1H1v2.5a.5.5 0 0 1-1 0zm16 0a1 1 0 0 0-1-1h-2.5a.5.5 0 0 0 0 1H15v2.5a.5.5 0 0 0 1 0zM1 16a1 1 0 0 1-1-1v-2.5a.5.5 0 0 1 1 0V15h2.5a.5.5 0 0 1 0 1zm15-1a1 1 0 0 1-1 1h-2.5a.5.5 0 0 1 0-1H15v-2.5a.5.5 0 0 1 1 0z"
        clipRule="evenodd"
      />
    </svg>
  )
})
