// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.sound.mid
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyLjI5MyAzLjI5M0ExIDEgMCAwIDEgMTQgNHYxNmExIDEgMCAwIDEtMS43MDcuNzA3TDguNTg2IDE3SDQuNUExLjUgMS41IDAgMCAxIDMgMTUuNXYtN0ExLjUgMS41IDAgMCAxIDQuNSA3aDQuMDg2ek05IDhINC41YS41LjUgMCAwIDAtLjUuNXY3YS41LjUgMCAwIDAgLjUuNUg5bDQgNFY0em02LjUwMS0uMDljMC0uMzM3LjMyOS0uNTc4LjYzNC0uNDMzYTUuMDAyIDUuMDAyIDAgMCAxIDAgOS4wNDZjLS4zMDUuMTQ0LS42MzQtLjA5Ni0uNjM0LS40MzN2LS4wNDZjMC0uMjAzLjEyNC0uMzg1LjMwNi0uNDc3YTMuOTk4IDMuOTk4IDAgMCAwIDAtNy4xMzYuNTQuNTQgMCAwIDEtLjMwNi0uNDc3em0wIDIuMzYxYzAtLjM4NS40MTMtLjYxMS42NzgtLjMzMmEyLjk5NiAyLjk5NiAwIDAgMSAwIDQuMTJjLS4yNjUuMjgtLjY3OC4wNTQtLjY3OC0uMzMydi0uMjJjMC0uMTIuMDQ2LS4yMzcuMTE3LS4zMzVhMS45OSAxLjk5IDAgMCAwIDAtMi4zNDUuNi42IDAgMCAxLS4xMTctLjMzNnoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1758
 */
export const Icon24SoundMid = memo(function Icon24SoundMid(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12.293 3.293A1 1 0 0 1 14 4v16a1 1 0 0 1-1.707.707L8.586 17H4.5A1.5 1.5 0 0 1 3 15.5v-7A1.5 1.5 0 0 1 4.5 7h4.086zM9 8H4.5a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5H9l4 4V4zm6.501-.09c0-.337.329-.578.634-.433a5.002 5.002 0 0 1 0 9.046c-.305.144-.634-.096-.634-.433v-.046c0-.203.124-.385.306-.477a3.998 3.998 0 0 0 0-7.136.54.54 0 0 1-.306-.477zm0 2.361c0-.385.413-.611.678-.332a2.996 2.996 0 0 1 0 4.12c-.265.28-.678.054-.678-.332v-.22c0-.12.046-.237.117-.335a1.99 1.99 0 0 0 0-2.345.6.6 0 0 1-.117-.336z"
      />
    </svg>
  )
})
