// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.community.new
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE4LjMyIDkuMjQ0QTEuMjUgMS4yNSAwIDAgMSAyMCAxMC40MTh2NS4yODVhMS44MyAxLjgzIDAgMCAxLS45NjggMS42MTVsLTYuNzk2IDMuNjI0YS41LjUgMCAwIDEtLjQxNC4wMjdsLS4wNTYtLjAyNy02Ljc5Ni0zLjYyNEExLjgzIDEuODMgMCAwIDEgNCAxNS43MDN2LTUuMjg1YTEuMjUgMS4yNSAwIDAgMSAxLjgzOS0xLjEwNEwxMiAxMi42MDFsNi4xNjItMy4yODZ6bS0xMi45NTIuOTUzYS4yNS4yNSAwIDAgMC0uMzY3LjIyMXY1LjI4NWEuODMuODMgMCAwIDAgLjQ0LjczM2w2LjA2IDMuMjMydi02LjJ6bTEzLjYzMy4yMjFhLjI1LjI1IDAgMCAwLS4zNjctLjIybC02LjEzMyAzLjI3djYuMmw2LjA2LTMuMjMyYS44My44MyAwIDAgMCAuNDQtLjczM3pNMTIgM2EzLjUgMy41IDAgMSAxLS4wMDIgNy4wMDJBMy41IDMuNSAwIDAgMSAxMi4wMDEgM20wIDFhMi41IDIuNSAwIDEgMCAwIDUgMi41IDIuNSAwIDAgMCAwLTUiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=4398-12080
 */
export const Icon24CommunityNew = memo(function Icon24CommunityNew(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M18.32 9.244A1.25 1.25 0 0 1 20 10.418v5.285a1.83 1.83 0 0 1-.968 1.615l-6.796 3.624a.5.5 0 0 1-.414.027l-.056-.027-6.796-3.624A1.83 1.83 0 0 1 4 15.703v-5.285a1.25 1.25 0 0 1 1.839-1.104L12 12.601l6.162-3.286zm-12.952.953a.25.25 0 0 0-.367.221v5.285a.83.83 0 0 0 .44.733l6.06 3.232v-6.2zm13.633.221a.25.25 0 0 0-.367-.22l-6.133 3.27v6.2l6.06-3.232a.83.83 0 0 0 .44-.733zM12 3a3.5 3.5 0 1 1-.002 7.002A3.5 3.5 0 0 1 12.001 3m0 1a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M17.288 9.299A1.25 1.25 0 0 1 19 10.46v5.268c0 .616-.31 1.187-.817 1.525l-.105.064-6.33 3.617a.5.5 0 0 1-.496 0l-6.33-3.617A1.83 1.83 0 0 1 4 15.73v-5.27a1.25 1.25 0 0 1 1.87-1.085l5.63 3.217 5.63-3.217zm-11.914.944A.25.25 0 0 0 5 10.46v5.27c0 .297.16.572.418.72L11 19.64v-6.182zM18 10.461a.25.25 0 0 0-.374-.218L12 13.458v6.182l5.582-3.19.092-.061a.83.83 0 0 0 .326-.66zM11.5 3a3.5 3.5 0 1 1-.002 7.002A3.5 3.5 0 0 1 11.5 3m0 1a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5"
      />
    </svg>
  )

  return icon
})
