// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.home
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgMTlhMSAxIDAgMCAxLTEgMUg1YTEgMSAwIDAgMS0xLTF2LTlhMSAxIDAgMCAxIC4zNS0uNzZsNy02YTEgMSAwIDAgMSAxLjMgMGw3IDZBMSAxIDAgMCAxIDIwIDEwdjlhMSAxIDAgMCAxLTEgMWgtNGExIDEgMCAwIDEtMS0xdi02aC00em0tNCAwSDV2LTlsNy02IDcgNnY5aC00di02YTEgMSAwIDAgMC0xLTFoLTRhMSAxIDAgMCAwLTEgMXY2eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1704
 */
export const Icon24Home = memo(function Icon24Home(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 19a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-9a1 1 0 0 1 .35-.76l7-6a1 1 0 0 1 1.3 0l7 6A1 1 0 0 1 20 10v9a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1v-6h-4zm-4 0H5v-9l7-6 7 6v9h-4v-6a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v6z"
        clipRule="evenodd"
      />
    </svg>
  )
})
