// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.measure.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNS4yOTMgMTAuMjA3YTEgMSAwIDAgMSAwLTEuNDE0bDMuNS0zLjVhMSAxIDAgMCAxIDEuNDE0IDBsOC41IDguNWExIDEgMCAwIDEgMCAxLjQxNGwtMy41IDMuNWExIDEgMCAwIDEtMS40MTQgMHptMS40MTQgMEw2IDkuNWwuNzA3LS43MDcgMi4wODYtMi4wODZMOS41IDZsLjcwNy43MDcgNy4wODYgNy4wODYuNzA3LjcwNy0uNzA3LjcwNy0yLjA4NiAyLjA4NkwxNC41IDE4bC0uNzA3LS43MDctMy42OS0zLjY5IDEuNzUtMS43NWEuNS41IDAgMCAwLS43MDctLjcwN2wtMS43NSAxLjc1LTEuMjkyLTEuMjkyLjc1LS43NWEuNS41IDAgMCAwLS43MDgtLjcwOGwtLjc1Ljc1ek0xMy41IDE0LjVhMSAxIDAgMSAwIDIgMCAxIDEgMCAwIDAtMiAwIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-4312
 */
export const Icon24MeasureSmall = memo(function Icon24MeasureSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5.293 10.207a1 1 0 0 1 0-1.414l3.5-3.5a1 1 0 0 1 1.414 0l8.5 8.5a1 1 0 0 1 0 1.414l-3.5 3.5a1 1 0 0 1-1.414 0zm1.414 0L6 9.5l.707-.707 2.086-2.086L9.5 6l.707.707 7.086 7.086.707.707-.707.707-2.086 2.086L14.5 18l-.707-.707-3.69-3.69 1.75-1.75a.5.5 0 0 0-.707-.707l-1.75 1.75-1.292-1.292.75-.75a.5.5 0 0 0-.708-.708l-.75.75zM13.5 14.5a1 1 0 1 0 2 0 1 1 0 0 0-2 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
