// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.boolean.exclude.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyA3aDd2MmgtNGExIDEgMCAwIDAtMSAxdjRIN3ptMyA4djJoN3YtN2gtMnY0YTEgMSAwIDAgMS0xIDF6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xMC41IDE1SDEwdjJoN3YtN2gtMnY0YTEgMSAwIDAgMS0xIDF6bTAtMUgxMHYtNGg0djR6TTkgMTRIN1Y3aDd2MmgtNGExIDEgMCAwIDAtMSAxem0tMSAxSDdhMSAxIDAgMCAxLTEtMVY3YTEgMSAwIDAgMSAxLTFoN2ExIDEgMCAwIDEgMSAxdjJoMmExIDEgMCAwIDEgMSAxdjdhMSAxIDAgMCAxLTEgMWgtN2ExIDEgMCAwIDEtMS0xdi0yeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3949
 */
export const Icon24BooleanExcludeSmall = memo(function Icon24BooleanExcludeSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M7 7h7v2h-4a1 1 0 0 0-1 1v4H7zm3 8v2h7v-7h-2v4a1 1 0 0 1-1 1z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10.5 15H10v2h7v-7h-2v4a1 1 0 0 1-1 1zm0-1H10v-4h4v4zM9 14H7V7h7v2h-4a1 1 0 0 0-1 1zm-1 1H7a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v2h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-7a1 1 0 0 1-1-1v-2z"
        clipRule="evenodd"
      />
    </svg>
  )
})
