// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.meeting.template.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyA2YTEgMSAwIDAgMC0xIDF2NmExIDEgMCAwIDAgMS40NDcuODk0TDkgMTMuMTE4VjE2YTEgMSAwIDAgMCAxIDFoNC43NjRsMS43ODkuODk0QTEgMSAwIDAgMCAxOCAxN3YtNmExIDEgMCAwIDAtMS0xaC0yVjdhMSAxIDAgMCAwLTEtMXptOCA1djFhMSAxIDAgMCAxLTEgMWgtNHYzaDVsMSAuNSAxIC41di02em0tMiAxSDlsLTEgLjUtMSAuNVY3aDd2NXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPjwvc3ZnPg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10729
 */
export const Icon24MeetingTemplateSmall = memo(function Icon24MeetingTemplateSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 6a1 1 0 0 0-1 1v6a1 1 0 0 0 1.447.894L9 13.118V16a1 1 0 0 0 1 1h4.764l1.789.894A1 1 0 0 0 18 17v-6a1 1 0 0 0-1-1h-2V7a1 1 0 0 0-1-1zm8 5v1a1 1 0 0 1-1 1h-4v3h5l1 .5 1 .5v-6zm-2 1H9l-1 .5-1 .5V7h7v5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
