// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.version.merged
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEuNjQ2IDYuMTQ2YS41LjUgMCAwIDEgLjcwOCAwbDIgMmEuNS41IDAgMCAxLS43MDguNzA4TDEyLjUgNy43MDd2My44MjRBNCA0IDAgMCAxIDE2IDE1LjV2MmEuNS41IDAgMCAxLTEgMHYtMmEzIDMgMCAxIDAtNiAwdjJhLjUuNSAwIDAgMS0xIDB2LTJhNCA0IDAgMCAxIDMuNS0zLjk3VjcuNzA4bC0xLjE0NiAxLjE0N2EuNS41IDAgMCAxLS43MDgtLjcwOHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-8646
 */
export const Icon24VersionMerged = memo(function Icon24VersionMerged(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.646 6.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L12.5 7.707v3.824A4 4 0 0 1 16 15.5v2a.5.5 0 0 1-1 0v-2a3 3 0 1 0-6 0v2a.5.5 0 0 1-1 0v-2a4 4 0 0 1 3.5-3.97V7.708l-1.146 1.147a.5.5 0 0 1-.708-.708z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.146 6.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L12 7.707v3.828c1.696.243 3 1.702 3 3.465v2.5a.5.5 0 0 1-1 0V15a2.5 2.5 0 0 0-5 0v2.5a.5.5 0 0 1-1 0V15a3.5 3.5 0 0 1 3-3.465V7.707L9.854 8.854a.5.5 0 1 1-.708-.708z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
