// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.text.large
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE5LjUgNGEuNS41IDAgMCAxIC41LjV2M2EuNS41IDAgMCAxLTEgMFY1aC02LjV2MTRIMTVhLjUuNSAwIDAgMSAwIDFIOWEuNS41IDAgMCAxIDAtMWgyLjVWNUg1djIuNWEuNS41IDAgMCAxLTEgMHYtM2EuNS41IDAgMCAxIC41LS41eiIvPjwvc3ZnPg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3095
 */
export const Icon24TextLarge = memo(function Icon24TextLarge(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props} data-fpl-icon-size="24L">
      <path
        fill="var(--fpl-icon-color, var(--color-icon))"
        d="M19.5 4a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0V5h-6.5v14H15a.5.5 0 0 1 0 1H9a.5.5 0 0 1 0-1h2.5V5H5v2.5a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props} data-fpl-icon-size="24L">
      <path
        fill="var(--fpl-icon-color, var(--color-icon))"
        fillRule="evenodd"
        d="M4 5.5a.5.5 0 0 1 .5-.5h14a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0V6h-6v12h2.5a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1H11V6H5v2.5a.5.5 0 0 1-1 0z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
