// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.border-bottom.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCA3YTEgMSAwIDAgMC0xIDEgLjUuNSAwIDAgMCAxIDAgLjUuNSAwIDAgMCAwLTFtMiAwYS41LjUgMCAwIDAgMCAxaDFhLjUuNSAwIDAgMCAwLTF6bTMgMGEuNS41IDAgMCAwIDAgMWgxYS41LjUgMCAwIDAgMC0xem0zIDBhLjUuNSAwIDAgMCAwIDEgLjUuNSAwIDAgMCAxIDAgMSAxIDAgMCAwLTEtMW0tOCAzYS41LjUgMCAwIDAtMSAwdjFhLjUuNSAwIDAgMCAxIDB6bTkgMGEuNS41IDAgMCAwLTEgMHYxYS41LjUgMCAwIDAgMSAwem0tOSAzYS41LjUgMCAwIDAtMSAwdjFhLjUuNSAwIDAgMCAxIDB6bTkgMGEuNS41IDAgMCAwLTEgMHYxYS41LjUgMCAwIDAgMSAwek03IDE1YTEgMSAwIDAgMC0xIDF2MWExIDEgMCAwIDAgMSAxaDEwYTEgMSAwIDAgMCAxLTF2LTFhMSAxIDAgMCAwLTEtMXptMCAxaDEwdjFIN3oiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6234
 */
export const Icon24BorderBottomSmall = memo(function Icon24BorderBottomSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 7a1 1 0 0 0-1 1 .5.5 0 0 0 1 0 .5.5 0 0 0 0-1m2 0a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1zm3 0a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1zm3 0a.5.5 0 0 0 0 1 .5.5 0 0 0 1 0 1 1 0 0 0-1-1m-8 3a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm9 0a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm-9 3a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm9 0a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zM7 15a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1zm0 1h10v1H7z"
        clipRule="evenodd"
      />
    </svg>
  )
})
