// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.chevron.right
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi43NjggNS41MjVhLjUuNSAwIDAgMSAuNzA3IDBsMi4xMjEgMi4xMjFMOS45NSA4bC0uMzU0LjM1NC0yLjEyMSAyLjEyYS41LjUgMCAwIDEtLjcwNy0uNzA2TDguNTM2IDggNi43NjggNi4yMzJhLjUuNSAwIDAgMSAwLS43MDciIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11746
 */
export const Icon16ChevronRight = memo(function Icon16ChevronRight(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.768 5.525a.5.5 0 0 1 .707 0l2.121 2.121L9.95 8l-.354.354-2.121 2.12a.5.5 0 0 1-.707-.706L8.536 8 6.768 6.232a.5.5 0 0 1 0-.707"
        clipRule="evenodd"
      />
    </svg>
  )
})
