// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.scatter-brush.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyAxMGExIDEgMCAxIDEtMiAwIDEgMSAwIDAgMSAyIDBtMCA0YTEgMSAwIDEgMS0yIDAgMSAxIDAgMCAxIDIgMG0xLTFhMSAxIDAgMSAwIDAtMiAxIDEgMCAwIDAgMCAybTMtM2ExIDEgMCAxIDEtMiAwIDEgMSAwIDAgMSAyIDBtLTEgNWExIDEgMCAxIDAgMC0yIDEgMSAwIDAgMCAwIDJtMy0zYTEgMSAwIDEgMS0yIDAgMSAxIDAgMCAxIDIgMG0xLTFhMSAxIDAgMSAwIDAtMiAxIDEgMCAwIDAgMCAybTUtMWExIDEgMCAxIDEtMiAwIDEgMSAwIDAgMSAyIDBtLTUgNWExIDEgMCAxIDAgMC0yIDEgMSAwIDAgMCAwIDJtNS0xYTEgMSAwIDEgMS0yIDAgMSAxIDAgMCAxIDIgMG0tMy0xYTEgMSAwIDEgMCAwLTIgMSAxIDAgMCAwIDAgMiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3633-8739
 */
export const Icon24ScatterBrushSmall = memo(function Icon24ScatterBrushSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 10a1 1 0 1 1-2 0 1 1 0 0 1 2 0m0 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0m1-1a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3-3a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-1 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3-3a1 1 0 1 1-2 0 1 1 0 0 1 2 0m1-1a1 1 0 1 0 0-2 1 1 0 0 0 0 2m5-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-5 5a1 1 0 1 0 0-2 1 1 0 0 0 0 2m5-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-3-1a1 1 0 1 0 0-2 1 1 0 0 0 0 2"
        clipRule="evenodd"
      />
    </svg>
  )
})
