// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.stroke.dashed.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0ibTYuODY2IDE3LjEzNC4zNTUuMzU0LS4zNjguMzY2YS41LjUgMCAxIDEtLjcwNy0uNzA3bC4zNjctLjM2N3ptLS4zNTMtLjM1NWEuNTAxLjUwMSAwIDAgMSAuNzA4LjcwOXptMi4yLTIuMTk5YS41LjUgMCAxIDEgLjcwNy43MDdsLS43MzQuNzM0YS41LjUgMCAwIDEtLjcwNy0uNzA3em0yLjItMi4yYS41LjUgMCAxIDEgLjcwNy43MDdsLS43MzMuNzMzYS41LjUgMCAwIDEtLjcwNy0uNzA3em0yLjItMi4yYS41LjUgMCAwIDEgLjcwNy43MDdsLS43MzMuNzMzYS41LjUgMCAxIDEtLjcwNy0uNzA3em0yLjItMi4yYS41LjUgMCAwIDEgLjcwNy43MDdsLS43MzMuNzMzYS41LjUgMCAwIDEtLjcwNy0uNzA3em0yLjE3NC0uNzZhLjUwMS41MDEgMCAwIDEtLjcwOC0uNzA3em0tLjI2Mi0xLjEzOGEuNS41IDAgMCAxIC42OTMuNjk0bC0uMDY0LjA3OC0uMzY3LjM2Ny0uMzUzLS4zNTUtLjM1NS0uMzUzLjM2Ny0uMzY2eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7640
 */
export const Icon24StrokeDashedSmall = memo(function Icon24StrokeDashedSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="m6.866 17.134.355.354-.368.366a.5.5 0 1 1-.707-.707l.367-.367zm-.353-.355a.501.501 0 0 1 .708.709zm2.2-2.199a.5.5 0 1 1 .707.707l-.734.734a.5.5 0 0 1-.707-.707zm2.2-2.2a.5.5 0 1 1 .707.707l-.733.733a.5.5 0 0 1-.707-.707zm2.2-2.2a.5.5 0 0 1 .707.707l-.733.733a.5.5 0 1 1-.707-.707zm2.2-2.2a.5.5 0 0 1 .707.707l-.733.733a.5.5 0 0 1-.707-.707zm2.174-.76a.501.501 0 0 1-.708-.707zm-.262-1.138a.5.5 0 0 1 .693.694l-.064.078-.367.367-.353-.355-.355-.353.367-.366z"
      />
    </svg>
  )
})
