// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.page-number
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTIgMjBhOCA4IDAgMSAwIDAtMTYgOCA4IDAgMCAwIDAgMTZtMCAxYTkgOSAwIDEgMCAwLTE4IDkgOSAwIDAgMCAwIDE4TTEwLjQ5NyA3LjU1NWEuNS41IDAgMSAwLS45OTQtLjExTDkuMzMgOUg3LjVhLjUuNSAwIDAgMCAwIDFoMS43MmwtLjQ0NSA0SDcuNWEuNS41IDAgMCAwIDAgMWgxLjE2NGwtLjE2MSAxLjQ0NWEuNS41IDAgMSAwIC45OTQuMTFMOS42NyAxNWgzLjk5NGwtLjE2MSAxLjQ0NWEuNS41IDAgMSAwIC45OTQuMTFMMTQuNjcgMTVoMS44M2EuNS41IDAgMSAwIDAtMWgtMS43MmwuNDQ1LTRIMTYuNWEuNS41IDAgMCAwIDAtMWgtMS4xNjRsLjE2LTEuNDQ1YS41LjUgMCAxIDAtLjk5My0uMTFMMTQuMzMgOWgtMy45OTR6TTEwLjIyNSAxMGgzLjk5NGwtLjQ0NCA0SDkuNzh6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=961-5686
 */
export const Icon24PageNumber = memo(function Icon24PageNumber(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16m0 1a9 9 0 1 0 0-18 9 9 0 0 0 0 18M10.497 7.555a.5.5 0 1 0-.994-.11L9.33 9H7.5a.5.5 0 0 0 0 1h1.72l-.445 4H7.5a.5.5 0 0 0 0 1h1.164l-.161 1.445a.5.5 0 1 0 .994.11L9.67 15h3.994l-.161 1.445a.5.5 0 1 0 .994.11L14.67 15h1.83a.5.5 0 1 0 0-1h-1.72l.445-4H16.5a.5.5 0 0 0 0-1h-1.164l.16-1.445a.5.5 0 1 0-.993-.11L14.33 9h-3.994zM10.225 10h3.994l-.444 4H9.78z"
        clipRule="evenodd"
      />
    </svg>
  )
})
