// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.inner.shadow.top.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2LjIwNCA2LjAxQTIgMiAwIDAgMSAxOCA4djhsLS4wMS4yMDRhMiAyIDAgMCAxLTEuNzg2IDEuNzg1TDE2IDE4SDhsLS4yMDQtLjAxYTIgMiAwIDAgMS0xLjc4NS0xLjc4Nkw2IDE2VjhhMiAyIDAgMCAxIDEuNzk2LTEuOTlMOCA2aDh6TTggN2ExIDEgMCAwIDAtMSAxdjhhMSAxIDAgMCAwIDEgMWg4YTEgMSAwIDAgMCAxLTFWOGExIDEgMCAwIDAtMS0xeiIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0xNiA3YTEgMSAwIDAgMSAxIDF2M2ExIDEgMCAwIDAtMS0xSDhhMSAxIDAgMCAwLTEgMVY4YTEgMSAwIDAgMSAxLTF6Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-8782
 */
export const Icon24InnerShadowTopSmall = memo(function Icon24InnerShadowTopSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M16.204 6.01A2 2 0 0 1 18 8v8l-.01.204a2 2 0 0 1-1.786 1.785L16 18H8l-.204-.01a2 2 0 0 1-1.785-1.786L6 16V8a2 2 0 0 1 1.796-1.99L8 6h8zM8 7a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1z"
      />
      <path
        fill="var(--color-icon-tertiary)"
        d="M16 7a1 1 0 0 1 1 1v3a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1V8a1 1 0 0 1 1-1z"
      />
    </svg>
  )
})
