// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.seat-collab.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEuMjUgMTUuMzA4YTQgNCAwIDEgMSAwLTYuNjE1QTQuOTggNC45OCAwIDAgMCAxMCAxMmE0Ljk4IDQuOTggMCAwIDAgMS4yNSAzLjMwN00xMiAxNmE1IDUgMCAxIDEgMC04IDUgNSAwIDEgMSAwIDhtLjc1LTcuMzA4YTQgNCAwIDEgMSAwIDYuNjE1QTQuOTggNC45OCAwIDAgMCAxNCAxMmE0Ljk4IDQuOTggMCAwIDAtMS4yNS0zLjMwOG0tLjc1LjY2MmMuNjIyLjcwNSAxIDEuNjMyIDEgMi42NDZzLS4zNzggMS45NC0xIDIuNjQ2QTQgNCAwIDAgMSAxMSAxMmE0IDQgMCAwIDEgMS0yLjY0NiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10903
 */
export const Icon24SeatCollabSmall = memo(function Icon24SeatCollabSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.25 15.308a4 4 0 1 1 0-6.615A4.98 4.98 0 0 0 10 12a4.98 4.98 0 0 0 1.25 3.307M12 16a5 5 0 1 1 0-8 5 5 0 1 1 0 8m.75-7.308a4 4 0 1 1 0 6.615A4.98 4.98 0 0 0 14 12a4.98 4.98 0 0 0-1.25-3.308m-.75.662c.622.705 1 1.632 1 2.646s-.378 1.94-1 2.646A4 4 0 0 1 11 12a4 4 0 0 1 1-2.646"
        clipRule="evenodd"
      />
    </svg>
  )
})
