// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.lock.locked
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHJlY3Qgd2lkdGg9IjYiIGhlaWdodD0iNCIgeD0iNSIgeT0iOCIgZmlsbD0iI2ZmZiIgcng9Ii4yNSIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTEwLjc3NiA4SDUuMjI0bC0uMDI1LjAwNUEuMjUuMjUgMCAwIDAgNSA4LjI1djMuNWMwIC4xMzguMTEyLjI1LjI1LjI1aDUuNWEuMjUuMjUgMCAwIDAgLjI1LS4yNXYtMy41YS4yNS4yNSAwIDAgMC0uMTk5LS4yNDV6TTcgN0g2VjZhMiAyIDAgMSAxIDQgMHYxek01IDZhMyAzIDAgMCAxIDYgMHYxLjAyNWMuNTcuMTE2IDEgLjYyIDEgMS4yMjV2My41YzAgLjY5LS41NiAxLjI1LTEuMjUgMS4yNWgtNS41QzQuNTYgMTMgNCAxMi40NCA0IDExLjc1di0zLjVjMC0uNjA1LjQzLTEuMTEgMS0xLjIyNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12223
 */
export const Icon16LockLocked = memo(function Icon16LockLocked(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <rect width="6" height="4" x="5" y="8" fill="var(--color-icon-tertiary)" rx=".25" />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10.776 8H5.224l-.025.005A.25.25 0 0 0 5 8.25v3.5c0 .138.112.25.25.25h5.5a.25.25 0 0 0 .25-.25v-3.5a.25.25 0 0 0-.199-.245zM7 7H6V6a2 2 0 1 1 4 0v1zM5 6a3 3 0 0 1 6 0v1.025c.57.116 1 .62 1 1.225v3.5c0 .69-.56 1.25-1.25 1.25h-5.5C4.56 13 4 12.44 4 11.75v-3.5c0-.605.43-1.11 1-1.225z"
        clipRule="evenodd"
      />
    </svg>
  )
})
