// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.all
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMi40ODYgNS4xNDNhMSAxIDAgMCAwIDAgMS43MTVMNC4zOSA4IDIuNDg2IDkuMTQzYTEgMSAwIDAgMCAwIDEuNzE1bDQuNDg1IDIuNjlhMiAyIDAgMCAwIDIuMDU4IDBsNC40ODYtMi42OWExIDEgMCAwIDAgMC0xLjcxNUwxMS42MSA4bDEuOTA1LTEuMTQyYTEgMSAwIDAgMCAwLTEuNzE1TDkuMDI5IDIuNDVhMiAyIDAgMCAwLTIuMDU4IDB6TTkuNjY2IDhsLjk3My0uNTgzIDEuMzktLjgzNEwxMyA2bC0uOTcyLS41ODMtMy41MTQtMi4xMDhhMSAxIDAgMCAwLTEuMDI4IDBMMy45NzIgNS40MTcgMyA2bC45NzIuNTgzIDEuMzkuODM0Ljk3MS41ODMgMS4xNTIuNjkxYTEgMSAwIDAgMCAxLjAzIDB6bS00LjMwNC41ODMgMS42MDkuOTY2YTIgMiAwIDAgMCAyLjA1OCAwbDEuNjEtLjk2NiAxLjM5LjgzNEwxMyAxMGwtLjk3Mi41ODMtMy41MTQgMi4xMDhhMSAxIDAgMCAxLTEuMDI4IDBsLTMuNTE0LTIuMTA4TDMgMTBsLjk3Mi0uNTgzeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12492
 */
export const Icon16All = memo(function Icon16All(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M2.486 5.143a1 1 0 0 0 0 1.715L4.39 8 2.486 9.143a1 1 0 0 0 0 1.715l4.485 2.69a2 2 0 0 0 2.058 0l4.486-2.69a1 1 0 0 0 0-1.715L11.61 8l1.905-1.142a1 1 0 0 0 0-1.715L9.029 2.45a2 2 0 0 0-2.058 0zM9.666 8l.973-.583 1.39-.834L13 6l-.972-.583-3.514-2.108a1 1 0 0 0-1.028 0L3.972 5.417 3 6l.972.583 1.39.834.971.583 1.152.691a1 1 0 0 0 1.03 0zm-4.304.583 1.609.966a2 2 0 0 0 2.058 0l1.61-.966 1.39.834L13 10l-.972.583-3.514 2.108a1 1 0 0 1-1.028 0l-3.514-2.108L3 10l.972-.583z"
        clipRule="evenodd"
      />
    </svg>
  )
})
