// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.16.community.new
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyLjQ1OCA1LjI1YS43NS43NSAwIDAgMSAxLjA0MS42OTF2NC4yNzZhMSAxIDAgMCAxLS40ODUuODU3TDguMjU4IDEzLjkzYS41LjUgMCAwIDEtLjUxNSAwbC00Ljc1OC0yLjg1NWExIDEgMCAwIDEtLjQ3Ni0uNzI2bC0uMDA5LS4xMzFWNS45NGEuNzUuNzUgMCAwIDEgMS4wNDEtLjY5MWwuMDk1LjA0OUw4IDcuOTE3bDQuMzYzLTIuNjE4ek0zLjUgMTAuMjE3bDQgMi40VjguNzgxbC00LTIuNHptNS0xLjQzNXYzLjgzNGwzLjk5OS0yLjRWNi4zODR6TTguMDAxIDJhMiAyIDAgMSAxLS4wMDIgNC4wMDJBMiAyIDAgMCAxIDguMDAxIDJtMCAxYTEgMSAwIDEgMCAwIDIgMSAxIDAgMCAwIDAtMiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=4403-12621
 */
export const Icon16CommunityNew = memo(function Icon16CommunityNew(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12.458 5.25a.75.75 0 0 1 1.041.691v4.276a1 1 0 0 1-.485.857L8.258 13.93a.5.5 0 0 1-.515 0l-4.758-2.855a1 1 0 0 1-.476-.726l-.009-.131V5.94a.75.75 0 0 1 1.041-.691l.095.049L8 7.917l4.363-2.618zM3.5 10.217l4 2.4V8.781l-4-2.4zm5-1.435v3.834l3.999-2.4V6.384zM8.001 2a2 2 0 1 1-.002 4.002A2 2 0 0 1 8.001 2m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
      />
    </svg>
  ) : (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12.01 5.694a.75.75 0 0 1 .991.71v4.287c0 .379-.215.724-.553.894l-4.723 2.362a.5.5 0 0 1-.448 0l-4.723-2.362A1 1 0 0 1 2 10.691V6.404a.75.75 0 0 1 .991-.71l.094.04L7.5 7.94l4.414-2.207zM3 10.691l4 2V8.808l-4-2zm5-1.882v3.881l4-1.999V6.81zM7.501 2a2 2 0 1 1-.002 4.002A2 2 0 0 1 7.501 2m0 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
      />
    </svg>
  )

  return icon
})
