// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.import
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCA2YTIgMiAwIDAgMC0yIDJ2OGEyIDIgMCAwIDAgMiAyaDhhMiAyIDAgMCAwIDItMlY5LjVhLjUuNSAwIDAgMC0xIDBWMTZhMSAxIDAgMCAxLTEgMUg4YTEgMSAwIDAgMS0xLTFWOGExIDEgMCAwIDEgMS0xaDNhLjUuNSAwIDAgMCAwLTF6bTkgMGE1LjUgNS41IDAgMCAwLTUuNSA1LjV2MS43OTNsLTEuNjQ2LTEuNjQ3YS41LjUgMCAwIDAtLjcwOC43MDhsMi41IDIuNWEuNS41IDAgMCAwIC43MDggMGwyLjUtMi41YS41LjUgMCAwIDAtLjcwOC0uNzA4TDEyLjUgMTMuMjkzVjExLjVBNC41IDQuNSAwIDAgMSAxNyA3aC41YS41LjUgMCAwIDAgMC0xeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2090
 */
export const Icon24Import = memo(function Icon24Import(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V9.5a.5.5 0 0 0-1 0V16a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h3a.5.5 0 0 0 0-1zm9 0a5.5 5.5 0 0 0-5.5 5.5v1.793l-1.646-1.647a.5.5 0 0 0-.708.708l2.5 2.5a.5.5 0 0 0 .708 0l2.5-2.5a.5.5 0 0 0-.708-.708L12.5 13.293V11.5A4.5 4.5 0 0 1 17 7h.5a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  )
})
