// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.replace.text.style
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMy41IDVhLjUuNSAwIDAgMC0uNS41djFhLjUuNSAwIDAgMCAxIDBWNmgzdjdoLS41YS41LjUgMCAwIDAgMCAxaDJhLjUuNSAwIDAgMCAwLTFIOFY2aDN2LjVhLjUuNSAwIDAgMCAxIDB2LTFhLjUuNSAwIDAgMC0uNS0uNXptOS41IDVhMSAxIDAgMCAwLTEgMXYxYTEgMSAwIDAgMCAxIDFoMnY1YTEgMSAwIDAgMCAxIDFoMWExIDEgMCAwIDAgMS0xdi01aDJhMSAxIDAgMCAwIDEtMXYtMWExIDEgMCAwIDAtMS0xem0wIDFoN3YxaC0zdjZoLTF2LTZoLTN6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6845
 */
export const Icon24ReplaceTextStyle = memo(function Icon24ReplaceTextStyle(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M3.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 1 0V6h3v7h-.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1H8V6h3v.5a.5.5 0 0 0 1 0v-1a.5.5 0 0 0-.5-.5zm9.5 5a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h2v5a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1v-5h2a1 1 0 0 0 1-1v-1a1 1 0 0 0-1-1zm0 1h7v1h-3v6h-1v-6h-3z"
        clipRule="evenodd"
      />
    </svg>
  )
})
