// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.actual.size.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi41IDdoMTFhLjUuNSAwIDAgMSAuNS41djlhLjUuNSAwIDAgMS0uNS41aC0xMWEuNS41IDAgMCAxLS41LS41di05YS41LjUgMCAwIDEgLjUtLjVNNSA3LjVBMS41IDEuNSAwIDAgMSA2LjUgNmgxMUExLjUgMS41IDAgMCAxIDE5IDcuNXY5YTEuNSAxLjUgMCAwIDEtMS41IDEuNWgtMTFBMS41IDEuNSAwIDAgMSA1IDE2LjV6bTQuNSAyYS41LjUgMCAwIDAtLjcyNC0uNDQ3bC0xIC41YS41LjUgMCAxIDAgLjQ0OC44OTRsLjI3Ni0uMTM4VjE0SDhhLjUuNSAwIDAgMCAwIDFoMmEuNS41IDAgMCAwIDAtMWgtLjV6bTYgMGEuNS41IDAgMCAwLS43MjQtLjQ0N2wtMSAuNWEuNS41IDAgMSAwIC40NDguODk0bC4yNzYtLjEzOFYxNEgxNGEuNS41IDAgMCAwIDAgMWgyYS41LjUgMCAwIDAgMC0xaC0uNXptLTMgMWEuNS41IDAgMSAwLTEgMCAuNS41IDAgMCAwIDEgME0xMiAxM2EuNS41IDAgMSAxIDAgMSAuNS41IDAgMCAxIDAtMSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10199
 */
export const Icon24ActualSizeSmall = memo(function Icon24ActualSizeSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.5 7h11a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5M5 7.5A1.5 1.5 0 0 1 6.5 6h11A1.5 1.5 0 0 1 19 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 5 16.5zm4.5 2a.5.5 0 0 0-.724-.447l-1 .5a.5.5 0 1 0 .448.894l.276-.138V14H8a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-.5zm6 0a.5.5 0 0 0-.724-.447l-1 .5a.5.5 0 1 0 .448.894l.276-.138V14H14a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-.5zm-3 1a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0M12 13a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1"
        clipRule="evenodd"
      />
    </svg>
  )
})
