// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.number-list
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEgN2EuNS41IDAgMCAxIC41LS41aDZhLjUuNSAwIDAgMSAwIDFoLTZBLjUuNSAwIDAgMSAxMSA3TTYgN2EuNS41IDAgMCAxIC41LS41aDFBLjUuNSAwIDAgMSA4IDd2My41YS41LjUgMCAxIDEtMSAwdi0zaC0uNUEuNS41IDAgMCAxIDYgN20wIDYuNWEuNS41IDAgMCAxIC41LS41aDJhLjUuNSAwIDAgMSAuNS41VjE1YS41LjUgMCAwIDEtLjI3Ni40NDdMNyAxNi4zMXYuMTkxaDEuNWEuNS41IDAgMCAxIDAgMWgtMkEuNS41IDAgMCAxIDYgMTd2LTFhLjUuNSAwIDAgMSAuMjc2LS40NDdMOCAxNC42OVYxNEg2LjVhLjUuNSAwIDAgMS0uNS0uNW01LjUgM2EuNS41IDAgMSAwIDAgMWg2YS41LjUgMCAwIDAgMC0xem0wLTVhLjUuNSAwIDEgMCAwIDFoNmEuNS41IDAgMCAwIDAtMXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6795
 */
export const Icon24NumberList = memo(function Icon24NumberList(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11 7a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6A.5.5 0 0 1 11 7M6 7a.5.5 0 0 1 .5-.5h1A.5.5 0 0 1 8 7v3.5a.5.5 0 1 1-1 0v-3h-.5A.5.5 0 0 1 6 7m0 6.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15a.5.5 0 0 1-.276.447L7 16.31v.191h1.5a.5.5 0 0 1 0 1h-2A.5.5 0 0 1 6 17v-1a.5.5 0 0 1 .276-.447L8 14.69V14H6.5a.5.5 0 0 1-.5-.5m5.5 3a.5.5 0 1 0 0 1h6a.5.5 0 0 0 0-1zm0-5a.5.5 0 1 0 0 1h6a.5.5 0 0 0 0-1z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M8.5 13a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.276.447L7 15.81V16h1.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .276-.447L8 14.19V14H6.5a.5.5 0 0 1 0-1zm9 3a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1zm0-5a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1zM7.6 6.01a.5.5 0 0 1 .4.49v3a.5.5 0 0 1-1 0V7h-.5a.5.5 0 0 1 0-1h1zM17.5 6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1z"
      />
    </svg>
  )

  return icon
})
