// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.send
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTEuNjQ2IDUuNjQ2YS41LjUgMCAwIDEgLjcwOCAwbDQuNSA0LjVhLjUuNSAwIDAgMS0uNzA4LjcwOEwxMi41IDcuMjA3VjE4YS41LjUgMCAwIDEtMSAwVjcuMjA3bC0zLjY0NiAzLjY0N2EuNS41IDAgMCAxLS43MDgtLjcwOHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1278
 */
export const Icon24Send = memo(function Icon24Send(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.646 5.646a.5.5 0 0 1 .708 0l4.5 4.5a.5.5 0 0 1-.708.708L12.5 7.207V18a.5.5 0 0 1-1 0V7.207l-3.646 3.647a.5.5 0 0 1-.708-.708z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.146 5.146a.5.5 0 0 1 .708 0l5 5a.5.5 0 0 1-.708.708L12 6.707V17.5a.5.5 0 0 1-1 0V6.707l-4.146 4.147a.5.5 0 0 1-.708-.708z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
