// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.scale.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCA3YTEgMSAwIDAgMC0xIDF2Mi41YS41LjUgMCAwIDEtMSAwVjhhMiAyIDAgMCAxIDItMmg4YTIgMiAwIDAgMSAyIDJ2OGEyIDIgMCAwIDEtMiAyaC0yLjVhLjUuNSAwIDAgMSAwLTFIMTZhMSAxIDAgMCAwIDEtMVY4YTEgMSAwIDAgMC0xLTF6bS0yIDYuNUExLjUgMS41IDAgMCAxIDcuNSAxMmgzYy4yMzIgMCAuNDUuMDUzLjY0Ny4xNDZMMTMuMjkzIDEwSDExLjVhLjUuNSAwIDAgMSAwLTFoM2EuNS41IDAgMCAxIC41LjV2M2EuNS41IDAgMCAxLTEgMHYtMS43OTNsLTIuMTQ2IDIuMTQ2Yy4wOTQuMTk2LjE0Ni40MTUuMTQ2LjY0N3YzYTEuNSAxLjUgMCAwIDEtMS41IDEuNWgtM0ExLjUgMS41IDAgMCAxIDYgMTYuNXptMS41LS41YS41LjUgMCAwIDAtLjUuNXYzYS41LjUgMCAwIDAgLjUuNWgzYS41LjUgMCAwIDAgLjUtLjV2LTNhLjUuNSAwIDAgMC0uNS0uNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2670
 */
export const Icon24ScaleSmall = memo(function Icon24ScaleSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 7a1 1 0 0 0-1 1v2.5a.5.5 0 0 1-1 0V8a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.5a.5.5 0 0 1 0-1H16a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1zm-2 6.5A1.5 1.5 0 0 1 7.5 12h3c.232 0 .45.053.647.146L13.293 10H11.5a.5.5 0 0 1 0-1h3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-1.793l-2.146 2.146c.094.196.146.415.146.647v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 6 16.5zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
