// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-grid-columns
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTcuMTAzIDUuMDA1QTEgMSAwIDAgMSA4IDZ2MTJsLS4wMDUuMTAyYTEgMSAwIDAgMS0uODkyLjg5M0w3IDE5SDZsLS4xMDMtLjAwNWExIDEgMCAwIDEtLjg5Mi0uODkzTDUgMThWNmExIDEgMCAwIDEgLjg5Ny0uOTk1TDYgNWgxem02IDBBMSAxIDAgMCAxIDE0IDZ2MTJsLS4wMDUuMTAyYTEgMSAwIDAgMS0uODkzLjg5M0wxMyAxOWgtMWwtLjEwMi0uMDA1YTEgMSAwIDAgMS0uODkzLS44OTNMMTEgMThWNmExIDEgMCAwIDEgLjg5OC0uOTk1TDEyIDVoMXptNiAwQTEgMSAwIDAgMSAyMCA2djEybC0uMDA1LjEwMmExIDEgMCAwIDEtLjg5My44OTNMMTkgMTloLTFsLS4xMDItLjAwNWExIDEgMCAwIDEtLjg5My0uODkzTDE3IDE4VjZhMSAxIDAgMCAxIC44OTgtLjk5NUwxOCA1aDF6TTE4IDE4aDFWNmgtMXpNNiAxOGgxVjZINnptNiAwaDFWNmgtMXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7172
 */
export const Icon24LayoutGridColumns = memo(function Icon24LayoutGridColumns(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M7.103 5.005A1 1 0 0 1 8 6v12l-.005.102a1 1 0 0 1-.892.893L7 19H6l-.103-.005a1 1 0 0 1-.892-.893L5 18V6a1 1 0 0 1 .897-.995L6 5h1zm6 0A1 1 0 0 1 14 6v12l-.005.102a1 1 0 0 1-.893.893L13 19h-1l-.102-.005a1 1 0 0 1-.893-.893L11 18V6a1 1 0 0 1 .898-.995L12 5h1zm6 0A1 1 0 0 1 20 6v12l-.005.102a1 1 0 0 1-.893.893L19 19h-1l-.102-.005a1 1 0 0 1-.893-.893L17 18V6a1 1 0 0 1 .898-.995L18 5h1zM18 18h1V6h-1zM6 18h1V6H6zm6 0h1V6h-1z"
      />
    </svg>
  )
})
