// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.reset.instance.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNS4zNTQgMTAuOTM5YTEuNSAxLjUgMCAwIDAgMCAyLjEyMWwyLjc5MiAyLjc5My4wMS4wMSAxLjg4NCAxLjg4M2EzLjY1IDMuNjUgMCAwIDAgNS41MzMtLjQzM2wuMDU5LS4wODEtLjQwNS0uMjk1LjQxNy4yNzdjMS41OTktMi40MTMtLjA4NC01LjcxNS0zLjAxLTUuNzE1aC0xLjQyNmwxLjY0Ni0xLjY0NmEuNS41IDAgMSAwLS43MDgtLjcwN2wtMi40OTkgMi41YS41LjUgMCAwIDAgMCAuNzA3bDIuNSAyLjVhLjUuNSAwIDEgMCAuNzA3LS43MDdsLTEuNjQ2LTEuNjQ3aDEuNDI1YzIuMDk0IDAgMy4zNSAyLjM4IDIuMTgzIDQuMTUzbC0uMDUyLjA3MmEyLjY1IDIuNjUgMCAwIDEtNC4wMTcuMzE1bC0yLjg5My0yLjg5My0xLjc5My0xLjc5M2EuNS41IDAgMCAxIDAtLjcwN2w1LjU4NS01LjU4NWEuNS41IDAgMCAxIC43MDcgMGw1LjU4NiA1LjU4NWEuNS41IDAgMCAxIDAgLjcwN2wtLjc5My43OTNhLjUuNSAwIDEgMCAuNzA3LjcwN2wuNzkzLS43OTNhMS41IDEuNSAwIDAgMCAwLTIuMTIxbC01LjU4NS01LjU4NmExLjUgMS41IDAgMCAwLTIuMTIyIDB6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=78-5393
 */
export const Icon24ResetInstanceSmall = memo(function Icon24ResetInstanceSmall(
  props: SVGIconProps,
) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5.354 10.939a1.5 1.5 0 0 0 0 2.121l2.792 2.793.01.01 1.884 1.883a3.65 3.65 0 0 0 5.533-.433l.059-.081-.405-.295.417.277c1.599-2.413-.084-5.715-3.01-5.715h-1.426l1.646-1.646a.5.5 0 1 0-.708-.707l-2.499 2.5a.5.5 0 0 0 0 .707l2.5 2.5a.5.5 0 1 0 .707-.707l-1.646-1.647h1.425c2.094 0 3.35 2.38 2.183 4.153l-.052.072a2.65 2.65 0 0 1-4.017.315l-2.893-2.893-1.793-1.793a.5.5 0 0 1 0-.707l5.585-5.585a.5.5 0 0 1 .707 0l5.586 5.585a.5.5 0 0 1 0 .707l-.793.793a.5.5 0 1 0 .707.707l.793-.793a1.5 1.5 0 0 0 0-2.121l-5.585-5.586a1.5 1.5 0 0 0-2.122 0z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5.854 10.439a1.5 1.5 0 0 0 0 2.121l2.792 2.793.011.01 1.883 1.883a3.65 3.65 0 0 0 5.533-.433l.058-.081-.404-.295.417.277c1.599-2.413-.084-5.715-3.01-5.715h-1.926l1.646-1.646a.5.5 0 1 0-.708-.707l-2.499 2.5a.5.5 0 0 0 0 .707l2.5 2.5a.5.5 0 1 0 .707-.707l-1.646-1.647h1.925c2.094 0 3.35 2.38 2.183 4.153l-.052.072a2.65 2.65 0 0 1-4.017.315l-2.893-2.893-1.793-1.793a.5.5 0 0 1 0-.707l5.085-5.086a.5.5 0 0 1 .707 0l5.086 5.086a.5.5 0 0 1 0 .707l-.293.293a.5.5 0 1 0 .707.707l.293-.293a1.5 1.5 0 0 0 0-2.121l-5.085-5.086a1.5 1.5 0 0 0-2.122 0z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
