// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.fill.screen.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi41IDdoMTFhLjUuNSAwIDAgMSAuNS41djlhLjUuNSAwIDAgMS0uNS41aC0xMWEuNS41IDAgMCAxLS41LS41di05YS41LjUgMCAwIDEgLjUtLjVNNSA3LjVBMS41IDEuNSAwIDAgMSA2LjUgNmgxMUExLjUgMS41IDAgMCAxIDE5IDcuNXY5YTEuNSAxLjUgMCAwIDEtMS41IDEuNWgtMTFBMS41IDEuNSAwIDAgMSA1IDE2LjV6bTIuNS41YS41LjUgMCAwIDAtLjUuNXYyYS41LjUgMCAwIDAgMSAwVjloMS41YS41LjUgMCAwIDAgMC0xem03IDBhLjUuNSAwIDAgMCAwIDFIMTZ2MS41YS41LjUgMCAwIDAgMSAwdi0yYS41LjUgMCAwIDAtLjUtLjV6TTggMTMuNWEuNS41IDAgMCAwLTEgMHYyYS41LjUgMCAwIDAgLjUuNWgyYS41LjUgMCAwIDAgMC0xSDh6bTkgMGEuNS41IDAgMCAwLTEgMFYxNWgtMS41YS41LjUgMCAwIDAgMCAxaDJhLjUuNSAwIDAgMCAuNS0uNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10239
 */
export const Icon24FillScreenSmall = memo(function Icon24FillScreenSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.5 7h11a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5M5 7.5A1.5 1.5 0 0 1 6.5 6h11A1.5 1.5 0 0 1 19 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 5 16.5zm2.5.5a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 1 0V9h1.5a.5.5 0 0 0 0-1zm7 0a.5.5 0 0 0 0 1H16v1.5a.5.5 0 0 0 1 0v-2a.5.5 0 0 0-.5-.5zM8 13.5a.5.5 0 0 0-1 0v2a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 0-1H8zm9 0a.5.5 0 0 0-1 0V15h-1.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 .5-.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
