// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.al.height-minmax
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTggNS41YS41LjUgMCAwIDEtLjUuNWgtMTFhLjUuNSAwIDAgMSAwLTFoMTFhLjUuNSAwIDAgMSAuNS41bTAgMTNhLjUuNSAwIDAgMS0uNS41aC0xMWEuNS41IDAgMCAxIDAtMWgxMWEuNS41IDAgMCAxIC41LjVNOC44NDUgOHY4aDEuMDl2LTMuNTMxaDQuMTI5VjE2aDEuMDg2VjhoLTEuMDg2djMuNTJIOS45MzVWOHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7550
 */
export const Icon24AlHeightMinmax = memo(function Icon24AlHeightMinmax(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M18 5.5a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1 0-1h11a.5.5 0 0 1 .5.5m0 13a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1 0-1h11a.5.5 0 0 1 .5.5M8.845 8v8h1.09v-3.531h4.129V16h1.086V8h-1.086v3.52H9.935V8z"
        clipRule="evenodd"
      />
    </svg>
  )
})
