// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.stroke-reversed-triangle
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi41MyA4LjE1MkExIDEgMCAwIDAgNSA5djVhMSAxIDAgMCAwIDEuNTMuODQ4bDQtMi41LjU1Ny0uMzQ4SDE4LjVhLjUuNSAwIDAgMCAwLTFoLTcuNDEzbC0uNTU3LS4zNDh6TTYgMTAuMTc5VjlsMSAuNjI1IDIuMDU3IDEuMjg1Ljk0My41OS0uOTQzLjU5TDcgMTMuMzc1IDYgMTR6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5766
 */
export const Icon24StrokeReversedTriangle = memo(function Icon24StrokeReversedTriangle(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.53 8.152A1 1 0 0 0 5 9v5a1 1 0 0 0 1.53.848l4-2.5.557-.348H18.5a.5.5 0 0 0 0-1h-7.413l-.557-.348zM6 10.179V9l1 .625 2.057 1.285.943.59-.943.59L7 13.375 6 14z"
        clipRule="evenodd"
      />
    </svg>
  )
})
