// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.layout-align-horizontal-center-group
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTIuNSAxOGEuNS41IDAgMCAwIC41LS41VjE1aDIuMjVhLjc1Ljc1IDAgMCAwIC43NS0uNzV2LS41YS43NS43NSAwIDAgMC0uNzUtLjc1SDEzdi0zaDQuMjVhLjc1Ljc1IDAgMCAwIC43NS0uNzV2LS41YS43NS43NSAwIDAgMC0uNzUtLjc1SDEzVjUuNWEuNS41IDAgMCAwLTEgMFY4SDcuNzVhLjc1Ljc1IDAgMCAwLS43NS43NXYuNWMwIC40MTQuMzM2Ljc1Ljc1Ljc1SDEydjNIOS43NWEuNzUuNzUgMCAwIDAtLjc1Ljc1di41YzAgLjQxNC4zMzYuNzUuNzUuNzVIMTJ2Mi41YS41LjUgMCAwIDAgLjUuNSIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS41IDE4YS41LjUgMCAwIDAgMC0xSDYuMjVhLjI1LjI1IDAgMCAxLS4yNS0uMjVWNi4yNUEuMjUuMjUgMCAwIDEgNi4yNSA2SDkuNWEuNS41IDAgMCAwIDAtMUg2LjI1QzUuNTYgNSA1IDUuNTYgNSA2LjI1djEwLjVjMCAuNjkuNTYgMS4yNSAxLjI1IDEuMjV6bTYtMTNhLjUuNSAwIDAgMCAwIDFoMy4yNWEuMjUuMjUgMCAwIDEgLjI1LjI1djEwLjVhLjI1LjI1IDAgMCAxLS4yNS4yNUgxNS41YS41LjUgMCAwIDAgMCAxaDMuMjVjLjY5IDAgMS4yNS0uNTYgMS4yNS0xLjI1VjYuMjVDMjAgNS41NiAxOS40NCA1IDE4Ljc1IDV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7024
 */
export const Icon24LayoutAlignHorizontalCenterGroup = memo(
  function Icon24LayoutAlignHorizontalCenterGroup(props: SVGIconProps) {
    return (
      <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
        <path
          fill="var(--color-icon)"
          fillRule="evenodd"
          d="M12.5 18a.5.5 0 0 0 .5-.5V15h2.25a.75.75 0 0 0 .75-.75v-.5a.75.75 0 0 0-.75-.75H13v-3h4.25a.75.75 0 0 0 .75-.75v-.5a.75.75 0 0 0-.75-.75H13V5.5a.5.5 0 0 0-1 0V8H7.75a.75.75 0 0 0-.75.75v.5c0 .414.336.75.75.75H12v3H9.75a.75.75 0 0 0-.75.75v.5c0 .414.336.75.75.75H12v2.5a.5.5 0 0 0 .5.5"
          clipRule="evenodd"
        />
        <path
          fill="var(--color-icon-tertiary)"
          fillRule="evenodd"
          d="M9.5 18a.5.5 0 0 0 0-1H6.25a.25.25 0 0 1-.25-.25V6.25A.25.25 0 0 1 6.25 6H9.5a.5.5 0 0 0 0-1H6.25C5.56 5 5 5.56 5 6.25v10.5c0 .69.56 1.25 1.25 1.25zm6-13a.5.5 0 0 0 0 1h3.25a.25.25 0 0 1 .25.25v10.5a.25.25 0 0 1-.25.25H15.5a.5.5 0 0 0 0 1h3.25c.69 0 1.25-.56 1.25-1.25V6.25C20 5.56 19.44 5 18.75 5z"
          clipRule="evenodd"
        />
      </svg>
    )
  },
)
