// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.component.set
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAuNjQ3IDMuMTQ2YS41LjUgMCAwIDEgLjcwNyAwbDEuNSAxLjVhLjUuNSAwIDAgMSAwIC43MDhsLTEuNSAxLjVhLjUuNSAwIDAgMS0uNzA3IDBsLTEuNS0xLjVhLjUuNSAwIDAgMSAwLS43MDh6TTEwLjIwNyA1bC43OTMuNzkzLjc5My0uNzkzTDExIDQuMjA3em0tNS41Ni0xLjg1NGEuNS41IDAgMCAxIC43MDcgMGwxLjUgMS41YS41LjUgMCAwIDEgMCAuNzA4bC0xLjUgMS41YS41LjUgMCAwIDEtLjcwOCAwbC0xLjUtMS41YS41LjUgMCAwIDEgMC0uNzA4ek00LjIwNiA1IDUgNS43OTMgNS43OTMgNSA1IDQuMjA3em0zLjQ0IDEuMTQ2YS41LjUgMCAwIDEgLjcwNyAwbDEuNSAxLjVhLjUuNSAwIDAgMSAwIC43MDhsLTEuNSAxLjVhLjUuNSAwIDAgMS0uNzA4IDBsLTEuNS0xLjVhLjUuNSAwIDAgMSAwLS43MDh6TTcuMjA2IDggOCA4Ljc5MyA4Ljc5MyA4IDggNy4yMDd6TTUuMzU0IDkuMTQ2YS41LjUgMCAwIDAtLjcwOCAwbC0xLjUgMS41YS41LjUgMCAwIDAgMCAuNzA3bDEuNSAxLjVhLjUuNSAwIDAgMCAuNzA4IDBsMS41LTEuNWEuNS41IDAgMCAwIDAtLjcwN3pNNSAxMS43OTMgNC4yMDcgMTEgNSAxMC4yMDdsLjc5My43OTN6bTYuMzU0LTIuNjQ3YS41LjUgMCAwIDAtLjcwOCAwbC0xLjUgMS41YS41LjUgMCAwIDAgMCAuNzA3bDEuNSAxLjVhLjUuNSAwIDAgMCAuNzA4IDBsMS41LTEuNWEuNS41IDAgMCAwIDAtLjcwN3pNMTEgMTEuNzkzIDEwLjIwNyAxMWwuNzkzLS43OTMuNzkzLjc5M3oiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-12166
 */
export const Icon16ComponentSet = memo(function Icon16ComponentSet(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10.647 3.146a.5.5 0 0 1 .707 0l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.707 0l-1.5-1.5a.5.5 0 0 1 0-.708zM10.207 5l.793.793.793-.793L11 4.207zm-5.56-1.854a.5.5 0 0 1 .707 0l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 0-.708zM4.206 5 5 5.793 5.793 5 5 4.207zm3.44 1.146a.5.5 0 0 1 .707 0l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 0-.708zM7.206 8 8 8.793 8.793 8 8 7.207zM5.354 9.146a.5.5 0 0 0-.708 0l-1.5 1.5a.5.5 0 0 0 0 .707l1.5 1.5a.5.5 0 0 0 .708 0l1.5-1.5a.5.5 0 0 0 0-.707zM5 11.793 4.207 11 5 10.207l.793.793zm6.354-2.647a.5.5 0 0 0-.708 0l-1.5 1.5a.5.5 0 0 0 0 .707l1.5 1.5a.5.5 0 0 0 .708 0l1.5-1.5a.5.5 0 0 0 0-.707zM11 11.793 10.207 11l.793-.793.793.793z"
        clipRule="evenodd"
      />
    </svg>
  )
})
