// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shapes.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTMuNzYyIDguNjM2LjAzNi4wNzZhLjU1LjU1IDAgMCAwIC40NzQuMjg4Yy4zMjUgMCAuNTY5LS4yOTkuNDY0LS42MDZhNSA1IDAgMCAwLTIuNzYtMi45ODggNSA1IDAgMSAwLTMuNTgyIDkuMzNjLjMwNy4xMDUuNjA2LS4xNC42MDYtLjQ2NGEuNTUuNTUgMCAwIDAtLjM2NC0uNTFsLS4wMTYtLjAwNkE0IDQgMCAwIDEgNi40MjggMTEuOGE0IDQgMCAxIDEgNy4zMjgtMy4xODF6TTExLjUgMTFoNmEuNS41IDAgMCAxIC41LjV2NmEuNS41IDAgMCAxLS41LjVoLTZhLjUuNSAwIDAgMS0uNS0uNXYtNmEuNS41IDAgMCAxIC41LS41bS0xLjUuNWExLjUgMS41IDAgMCAxIDEuNS0xLjVoNmExLjUgMS41IDAgMCAxIDEuNSAxLjV2NmExLjUgMS41IDAgMCAxLTEuNSAxLjVoLTZhMS41IDEuNSAwIDAgMS0xLjUtMS41eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-4795
 */
export const Icon24ShapesSmall = memo(function Icon24ShapesSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m13.762 8.636.036.076a.55.55 0 0 0 .474.288c.325 0 .569-.299.464-.606a5 5 0 0 0-2.76-2.988 5 5 0 1 0-3.582 9.33c.307.105.606-.14.606-.464a.55.55 0 0 0-.364-.51l-.016-.006A4 4 0 0 1 6.428 11.8a4 4 0 1 1 7.328-3.181zM11.5 11h6a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5v-6a.5.5 0 0 1 .5-.5m-1.5.5a1.5 1.5 0 0 1 1.5-1.5h6a1.5 1.5 0 0 1 1.5 1.5v6a1.5 1.5 0 0 1-1.5 1.5h-6a1.5 1.5 0 0 1-1.5-1.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
