// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.comment.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy44OTUgMTdIMTJhNSA1IDAgMSAwLTUtNXY0LjEwNWMwIC4xOSAwIC4zMDcuMDAzLjM5NmExIDEgMCAwIDAgLjAwOC4xMDIuNS41IDAgMCAwIC4zODYuMzg2IDEgMSAwIDAgMCAuMTAyLjAwOGMuMDg5LjAwMy4yMDUuMDAzLjM5Ni4wMDNNMTIgNmE2IDYgMCAwIDAtNiA2djQuMTA1YzAgLjM2NyAwIC41NS4wMzIuNzAzYTEuNSAxLjUgMCAwIDAgMS4xNiAxLjE2Yy4xNTIuMDMyLjMzNi4wMzIuNzAzLjAzMkgxMmE2IDYgMCAwIDAgMC0xMiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3151
 */
export const Icon24CommentSmall = memo(function Icon24CommentSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7.895 17H12a5 5 0 1 0-5-5v4.105c0 .19 0 .307.003.396a1 1 0 0 0 .008.102.5.5 0 0 0 .386.386 1 1 0 0 0 .102.008c.089.003.205.003.396.003M12 6a6 6 0 0 0-6 6v4.105c0 .367 0 .55.032.703a1.5 1.5 0 0 0 1.16 1.16c.152.032.336.032.703.032H12a6 6 0 0 0 0-12"
        clipRule="evenodd"
      />
    </svg>
  )
})
