// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.spacing.horizontal.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTIgNmEuNS41IDAgMCAxIC41LjV2MTFhLjUuNSAwIDAgMS0xIDB2LTExQS41LjUgMCAwIDEgMTIgNk05IDhhMSAxIDAgMCAxIDEgMXY2YTEgMSAwIDAgMS0xIDFIN2ExIDEgMCAwIDEtMS0xVjlhMSAxIDAgMCAxIDEtMXptMCAyVjlIN3Y2aDJ6bTktMWExIDEgMCAwIDAtMS0xaC0yYTEgMSAwIDAgMC0xIDF2NmExIDEgMCAwIDAgMSAxaDJhMSAxIDAgMCAwIDEtMXptLTEgMHY2aC0yVjl6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-6149
 */
export const Icon24SpacingHorizontalSmall = memo(function Icon24SpacingHorizontalSmall(
  props: SVGIconProps,
) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M12 6a.5.5 0 0 1 .5.5v11a.5.5 0 0 1-1 0v-11A.5.5 0 0 1 12 6M9 8a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1zm0 2V9H7v6h2zm9-1a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm-1 0v6h-2V9z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M11.5 6a.5.5 0 0 1 .5.5v11a.5.5 0 0 1-1 0v-11a.5.5 0 0 1 .5-.5M9 8a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1zm0 2V9H7v6h2zm8-1a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm-1 0v6h-2V9z"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
