// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.radius.top.left
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTIuNDc4IDhIMTUuNWEuNS41IDAgMCAxIDAgMWgtM2MtLjcwOCAwLTEuMjEgMC0xLjYwMS4wMzItLjM4Ni4wMzItLjYyMi4wOTItLjgwNy4xODZhMiAyIDAgMCAwLS44NzQuODc0Yy0uMDk0LjE4NS0uMTU0LjQyLS4xODYuODA3QzkgMTEuMjkgOSAxMS43OTIgOSAxMi41djNhLjUuNSAwIDAgMS0xIDB2LTMuMDIyYzAtLjY4MSAwLTEuMjIzLjAzNi0xLjY2LjAzNi0uNDQ4LjExMy0uODMuMjkxLTEuMThhMyAzIDAgMCAxIDEuMzExLTEuMzExYy4zNS0uMTc4LjczMi0uMjU1IDEuMTgtLjI5MUMxMS4yNTQgOCAxMS43OTYgOCAxMi40NzcgOCIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5119
 */
export const Icon24RadiusTopLeft = memo(function Icon24RadiusTopLeft(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M12.478 8H15.5a.5.5 0 0 1 0 1h-3c-.708 0-1.21 0-1.601.032-.386.032-.622.092-.807.186a2 2 0 0 0-.874.874c-.094.185-.154.42-.186.807C9 11.29 9 11.792 9 12.5v3a.5.5 0 0 1-1 0v-3.022c0-.681 0-1.223.036-1.66.036-.448.113-.83.291-1.18a3 3 0 0 1 1.311-1.311c.35-.178.732-.255 1.18-.291C11.254 8 11.796 8 12.477 8"
        clipRule="evenodd"
      />
    </svg>
  )
})
