// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.star.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyIDVhMSAxIDAgMCAxIC44Ny41MDlsMS44MzkgMy4yNiAzLjY3Ljc0Mi4xMy4wMzZhMSAxIDAgMCAxIC40OTMgMS41MTZsLS4wODQuMTA1LTIuNTM0IDIuNzU2LjQzIDMuNzJhMSAxIDAgMCAxLTEuNDEgMS4wMjRMMTIgMTcuMTA5bC0zLjQwNSAxLjU1OWExIDEgMCAwIDEtMS40MS0xLjAyNGwuNDMtMy43Mi0yLjUzMy0yLjc1NmExIDEgMCAwIDEgLjUzOC0xLjY1N2wzLjY3LS43NDEgMS44MzktMy4yNjEuMDczLS4xMTNDMTEuMzg5IDUuMTUgMTEuNjg0IDUgMTIgNU05LjkzNiA5LjY2bC00LjExOC44MzEgMi44NDQgMy4wOTQtLjQ4MyA0LjE3NCAzLjgyLTEuNzUgMy44MjEgMS43NS0uNDgyLTQuMTc0IDIuODQzLTMuMDk0LTQuMTE4LS44M0wxMiA2eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-8021
 */
export const Icon24ShapeStarSmall = memo(function Icon24ShapeStarSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12 5a1 1 0 0 1 .87.509l1.839 3.26 3.67.742.13.036a1 1 0 0 1 .493 1.516l-.084.105-2.534 2.756.43 3.72a1 1 0 0 1-1.41 1.024L12 17.109l-3.405 1.559a1 1 0 0 1-1.41-1.024l.43-3.72-2.533-2.756a1 1 0 0 1 .538-1.657l3.67-.741 1.839-3.261.073-.113C11.389 5.15 11.684 5 12 5M9.936 9.66l-4.118.831 2.844 3.094-.483 4.174 3.82-1.75 3.821 1.75-.482-4.174 2.843-3.094-4.118-.83L12 6z"
      />
    </svg>
  )
})
