// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shorten.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0ibTkuNCAxNi41LjI4LTEuMTJjLjA4My0uMzMzLjU1Ny0uMzMzLjY0IDBsLjI4IDEuMTIgMS4xMi4yOGMuMzMzLjA4My4zMzMuNTU3IDAgLjY0bC0xLjEyLjI4LS4yOCAxLjEyYy0uMDgzLjMzMy0uNTU3LjMzMy0uNjQgMEw5LjQgMTcuN2wtMS4xMi0uMjhjLS4zMzMtLjA4My0uMzMzLS41NTcgMC0uNjR6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi4yMjQgMTUuNDQ4YS41LjUgMCAxIDEtLjQ0OC0uODk0bDQtMmEuNS41IDAgMCAxIC40NDcuODk0ek0xMiAxMS40NDIgNi4yMjQgOC41NTRhLjUuNSAwIDAgMC0uNDQ4Ljg5NGw1Ljk5NSAyLjk5OC4wMS4wMDUgMS42NzMuODM2LS4yNSAxLjc1MmEyLjQ1IDIuNDUgMCAwIDAgMS4zMjkgMi41MzdsLjI0My4xMjJhMi4xNzcgMi4xNzcgMCAwIDAgMS45NDgtMy44OTRsLTIuNDktMS4yNDUtLjAyLS4wMUwxMy4xMTcgMTJsMS4wOTUtLjU0OC4wMjEtLjAxIDIuNDktMS4yNDVhMi4xNzcgMi4xNzcgMCAwIDAtMS45NDctMy44OTRsLS4yNDQuMTIyYTIuNDUgMi40NSAwIDAgMC0xLjMzIDIuNTM4bC4yNTEgMS43NTF6bTIuMTk0LTIuNjIuMjAzIDEuNDIyIDEuODgtLjk0YTEuMTc3IDEuMTc3IDAgMSAwLTEuMDUzLTIuMTA1bC0uMjQ0LjEyMmExLjQ1IDEuNDUgMCAwIDAtLjc4NiAxLjUwMW0wIDYuMzU5LjIwMy0xLjQyMiAxLjg4Ljk0YTEuMTc3IDEuMTc3IDAgMSAxLTEuMDU0IDIuMTA1bC0uMjQzLS4xMjJhMS40NSAxLjQ1IDAgMCAxLS43ODYtMS41MDEiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7981
 */
export const Icon24ShortenSmall = memo(function Icon24ShortenSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="m9.4 16.5.28-1.12c.083-.333.557-.333.64 0l.28 1.12 1.12.28c.333.083.333.557 0 .64l-1.12.28-.28 1.12c-.083.333-.557.333-.64 0L9.4 17.7l-1.12-.28c-.333-.083-.333-.557 0-.64z"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.224 15.448a.5.5 0 1 1-.448-.894l4-2a.5.5 0 0 1 .447.894zM12 11.442 6.224 8.554a.5.5 0 0 0-.448.894l5.995 2.998.01.005 1.673.836-.25 1.752a2.45 2.45 0 0 0 1.329 2.537l.243.122a2.177 2.177 0 0 0 1.948-3.894l-2.49-1.245-.02-.01L13.117 12l1.095-.548.021-.01 2.49-1.245a2.177 2.177 0 0 0-1.947-3.894l-.244.122a2.45 2.45 0 0 0-1.33 2.538l.251 1.751zm2.194-2.62.203 1.422 1.88-.94a1.177 1.177 0 1 0-1.053-2.105l-.244.122a1.45 1.45 0 0 0-.786 1.501m0 6.359.203-1.422 1.88.94a1.177 1.177 0 1 1-1.054 2.105l-.243-.122a1.45 1.45 0 0 1-.786-1.501"
        clipRule="evenodd"
      />
    </svg>
  )
})
