// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.blendmode.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTQuNzgzIDE2LjA1OEMxNS40NzkgMTUuNDU0IDE2IDE0LjQ5IDE2IDEzYzAtMS4wMzctLjU5Ny0yLjMyOC0xLjQ5My0zLjYzMS0uODQ0LTEuMjI3LTEuODUtMi4zMTYtMi41MDctMi45OC0uNjU4LjY2NC0xLjY2MiAxLjc1My0yLjUwNyAyLjk4QzguNTk3IDEwLjY3MyA4IDExLjk2NCA4IDEzYzAgMS40OTEuNTIxIDIuNDU0IDEuMjE3IDMuMDU4LjcyLjYyMyAxLjcyMS45NDMgMi43ODMuOTQzczIuMDYzLS4zMiAyLjc4My0uOTQ0TTEyIDE4YzIuNSAwIDUtMS41IDUtNSAwLTIuNzEyLTMtNi4wMjMtNC4zNTMtNy4zNzhhLjkwNy45MDcgMCAwIDAtMS4yOTQgMEMxMCA2Ljk3OCA3IDEwLjI5IDcgMTMuMDAxYzAgMy41IDIuNSA1IDUgNSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-9488
 */
export const Icon24BlendmodeSmall = memo(function Icon24BlendmodeSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M14.783 16.058C15.479 15.454 16 14.49 16 13c0-1.037-.597-2.328-1.493-3.631-.844-1.227-1.85-2.316-2.507-2.98-.658.664-1.662 1.753-2.507 2.98C8.597 10.673 8 11.964 8 13c0 1.491.521 2.454 1.217 3.058.72.623 1.721.943 2.783.943s2.063-.32 2.783-.944M12 18c2.5 0 5-1.5 5-5 0-2.712-3-6.023-4.353-7.378a.907.907 0 0 0-1.294 0C10 6.978 7 10.29 7 13.001c0 3.5 2.5 5 5 5"
        clipRule="evenodd"
      />
    </svg>
  )
})
