// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.sound.mid
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtNyAxMS0xLTFINC41YS41LjUgMCAwIDEtLjUtLjV2LTNhLjUuNSAwIDAgMSAuNS0uNUg2bDEtMSAxLTF2OHpNNS41ODYgNWwxLjcwNy0xLjcwN0ExIDEgMCAwIDEgOSA0djhhMSAxIDAgMCAxLTEuNzA3LjcwN0w1LjU4NiAxMUg0LjVBMS41IDEuNSAwIDAgMSAzIDkuNXYtM0ExLjUgMS41IDAgMCAxIDQuNSA1ek0xMCAxMC41YzAgLjI3Ni4yMjYuNTA1LjQ5OC40NTlhMyAzIDAgMCAwIDAtNS45MThjLS4yNzItLjA0NS0uNDk4LjE4My0uNDk4LjQ2IDAgLjI3NS4yMjcuNDkzLjQ5NS41NmEyIDIgMCAwIDEgMCAzLjg3N2MtLjI2OC4wNjktLjQ5NS4yODYtLjQ5NS41NjJtMC0yYzAgLjI3Ni4yMzcuNTEuNDguMzc4YTEgMSAwIDAgMCAwLTEuNzU2Yy0uMjQzLS4xMzItLjQ4LjEwMi0uNDguMzc4eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13389
 */
export const Icon16SoundMid = memo(function Icon16SoundMid(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m7 11-1-1H4.5a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5H6l1-1 1-1v8zM5.586 5l1.707-1.707A1 1 0 0 1 9 4v8a1 1 0 0 1-1.707.707L5.586 11H4.5A1.5 1.5 0 0 1 3 9.5v-3A1.5 1.5 0 0 1 4.5 5zM10 10.5c0 .276.226.505.498.459a3 3 0 0 0 0-5.918c-.272-.045-.498.183-.498.46 0 .275.227.493.495.56a2 2 0 0 1 0 3.877c-.268.069-.495.286-.495.562m0-2c0 .276.237.51.48.378a1 1 0 0 0 0-1.756c-.243-.132-.48.102-.48.378z"
        clipRule="evenodd"
      />
    </svg>
  )
})
