// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.mobile
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE0Ljc1NiAzLjAxM0EyLjUgMi41IDAgMCAxIDE3IDUuNXYxM2wtLjAxMy4yNTZhMi41IDIuNSAwIDAgMS0yLjIzMSAyLjIzMUwxNC41IDIxaC01bC0uMjU2LS4wMTNhMi41IDIuNSAwIDAgMS0yLjIzMS0yLjIzMUw3IDE4LjV2LTEzYTIuNSAyLjUgMCAwIDEgMi4yNDQtMi40ODdMOS41IDNoNXpNOS41IDRBMS41IDEuNSAwIDAgMCA4IDUuNXYxM0ExLjUgMS41IDAgMCAwIDkuNSAyMGg1YTEuNSAxLjUgMCAwIDAgMS41LTEuNXYtMTNBMS41IDEuNSAwIDAgMCAxNC41IDR6TTEyIDE4YS41LjUgMCAxIDEgMCAxIC41LjUgMCAwIDEgMC0xbTEtMTNhLjUuNSAwIDAgMSAwIDFoLTJhLjUuNSAwIDAgMSAwLTF6Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3984-8423
 */
export const Icon24Mobile = memo(function Icon24Mobile(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M14.756 3.013A2.5 2.5 0 0 1 17 5.5v13l-.013.256a2.5 2.5 0 0 1-2.231 2.231L14.5 21h-5l-.256-.013a2.5 2.5 0 0 1-2.231-2.231L7 18.5v-13a2.5 2.5 0 0 1 2.244-2.487L9.5 3h5zM9.5 4A1.5 1.5 0 0 0 8 5.5v13A1.5 1.5 0 0 0 9.5 20h5a1.5 1.5 0 0 0 1.5-1.5v-13A1.5 1.5 0 0 0 14.5 4zM12 18a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1m1-13a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1z"
      />
    </svg>
  )
})
