// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.help.alt
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyIDE1LjVhLjc1Ljc1IDAgMSAxIDAgMS41Ljc1Ljc1IDAgMCAxIDAtMS41TTEyIDdhMyAzIDAgMCAxIDMgM2MwIDEuMDM4LS41MyAxLjc2NC0xLjMyMiAyLjE1Mi0uNzE1LjM1LTEuMTc4LjgzLTEuMTc4IDEuMzQ4di41YS41LjUgMCAwIDEtMSAwdi0uNWMwLTEuMTM4Ljk2NC0xLjg2NyAxLjczNy0yLjI0Ni40Ny0uMjMuNzYzLS42MTkuNzYzLTEuMjU0YTIgMiAwIDEgMC00IDAgLjUuNSAwIDAgMS0xIDAgMyAzIDAgMCAxIDMtMyIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11945
 */
export const Icon16HelpAlt = memo(function Icon16HelpAlt(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12 15.5a.75.75 0 1 1 0 1.5.75.75 0 0 1 0-1.5M12 7a3 3 0 0 1 3 3c0 1.038-.53 1.764-1.322 2.152-.715.35-1.178.83-1.178 1.348v.5a.5.5 0 0 1-1 0v-.5c0-1.138.964-1.867 1.737-2.246.47-.23.763-.619.763-1.254a2 2 0 1 0-4 0 .5.5 0 0 1-1 0 3 3 0 0 1 3-3"
      />
    </svg>
  )
})
