// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.boolean.intersect
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTQgMTB2NGgtNHYtNHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTEwIDE1djRoOXYtOWgtNHY0YTEgMSAwIDAgMS0xIDF6bS41LTFIMTB2LTRoNHY0ek05IDE0SDVWNWg5djRoLTRhMSAxIDAgMCAwLTEgMXptLTEgMUg1YTEgMSAwIDAgMS0xLTFWNWExIDEgMCAwIDEgMS0xaDlhMSAxIDAgMCAxIDEgMXY0aDRhMSAxIDAgMCAxIDEgMXY5YTEgMSAwIDAgMS0xIDFoLTlhMSAxIDAgMCAxLTEtMXYtNHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3935
 */
export const Icon24BooleanIntersect = memo(function Icon24BooleanIntersect(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M14 10v4h-4v-4z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 15v4h9v-9h-4v4a1 1 0 0 1-1 1zm.5-1H10v-4h4v4zM9 14H5V5h9v4h-4a1 1 0 0 0-1 1zm-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v4h4a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1h-9a1 1 0 0 1-1-1v-4z"
        clipRule="evenodd"
      />
    </svg>
  )
})
