// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.generate.code
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTkuMDE1IDEuNDQxLS41MTUgMi4wNi0yLjA2LjUxNWMtLjUwNS4xMjYtLjUwNS44NDQgMCAuOTdsMi4wNi41MTUuNTE1IDIuMDZjLjEyNi41MDUuODQ0LjUwNS45NyAwTDIwLjUgNS41bDIuMDYtLjUxNWMuNTA1LS4xMjYuNTA1LS44NDQgMC0uOTdMMjAuNSAzLjVsLS41MTUtMi4wNmMtLjEyNi0uNTA1LS44NDQtLjUwNS0uOTcgME0xMy41IDQuMDAxYS41LjUgMCAwIDEgMCAxSDZhMSAxIDAgMCAwLTEgMXYxMmExIDEgMCAwIDAgMSAxaDEyYTEgMSAwIDAgMCAxLTF2LTcuNWEuNS41IDAgMCAxIDEgMFYxOGEyIDIgMCAwIDEtMiAySDZhMiAyIDAgMCAxLTItMlY2YTIgMiAwIDAgMSAyLTJ6bS0yLjY0NiA1Ljg1M2EuNS41IDAgMCAwLS43MDgtLjcwN2wtMi41IDIuNWEuNS41IDAgMCAwIDAgLjcwN2wyLjUgMi41YS41LjUgMCAwIDAgLjcwOC0uNzA3bC0yLjE0Ny0yLjE0NnptMi4yOTItLjg0MWEuNS41IDAgMCAwIDAgLjcwN2wyLjE0NyAyLjE0Ni0yLjE0NyAyLjE0N2EuNS41IDAgMCAwIC43MDguNzA3bDIuNS0yLjVhLjUuNSAwIDAgMCAwLS43MDdsLTIuNS0yLjVhLjUuNSAwIDAgMC0uNzA4IDAiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=2250-30590
 */
export const Icon24GenerateCode = memo(function Icon24GenerateCode(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m19.015 1.441-.515 2.06-2.06.515c-.505.126-.505.844 0 .97l2.06.515.515 2.06c.126.505.844.505.97 0L20.5 5.5l2.06-.515c.505-.126.505-.844 0-.97L20.5 3.5l-.515-2.06c-.126-.505-.844-.505-.97 0M13.5 4.001a.5.5 0 0 1 0 1H6a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-7.5a.5.5 0 0 1 1 0V18a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2zm-2.646 5.853a.5.5 0 0 0-.708-.707l-2.5 2.5a.5.5 0 0 0 0 .707l2.5 2.5a.5.5 0 0 0 .708-.707l-2.147-2.146zm2.292-.841a.5.5 0 0 0 0 .707l2.147 2.146-2.147 2.147a.5.5 0 0 0 .708.707l2.5-2.5a.5.5 0 0 0 0-.707l-2.5-2.5a.5.5 0 0 0-.708 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
