// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.vector.paint.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOC44NTQgNS4xNDZhLjUuNSAwIDEgMC0uNzA4LjcwOGw0LjM4OCA0LjM4N2ExIDEgMCAxIDAgLjcwNy0uNzA3TDExLjIwNyA3LjUgMTIuNSA2LjIwN2w1LjI5MyA1LjI5My01LjczMiA1LjczMmExLjUgMS41IDAgMCAxLTIuMTIyIDBsLTMuMTcxLTMuMTcxYTEuNSAxLjUgMCAwIDEgMC0yLjEyMmwyLjU4Ni0yLjU4NWEuNS41IDAgMCAwLS43MDgtLjcwOGwtMi41ODUgMi41ODZhMi41IDIuNSAwIDAgMCAwIDMuNTM2bDMuMTcxIDMuMTcxYTIuNSAyLjUgMCAwIDAgMy41MzYgMGw1LjczMi01LjczMmExIDEgMCAwIDAgMC0xLjQxNEwxMy4yMDcgNS41YTEgMSAwIDAgMC0xLjQxNCAwTDEwLjUgNi43OTN6TTE4IDE3LjVhLjUuNSAwIDEgMS0xIDBjMC0uNDMzLjIzNC0uODQuNTA4LTEuMTYuMjY1LjMwOC40OTIuNzEuNDkyIDEuMTZtMSAwYTEuNSAxLjUgMCAxIDEtMyAwYzAtMS4xMDYuODE1LTEuOTQgMS4yNDQtMi4zMDJhLjQuNCAwIDAgMSAuNTE2LS4wMDRjLjQzLjM1MiAxLjI0IDEuMTY4IDEuMjQgMi4zMDYiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3072
 */
export const Icon24VectorPaintSmall = memo(function Icon24VectorPaintSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8.854 5.146a.5.5 0 1 0-.708.708l4.388 4.387a1 1 0 1 0 .707-.707L11.207 7.5 12.5 6.207l5.293 5.293-5.732 5.732a1.5 1.5 0 0 1-2.122 0l-3.171-3.171a1.5 1.5 0 0 1 0-2.122l2.586-2.585a.5.5 0 0 0-.708-.708l-2.585 2.586a2.5 2.5 0 0 0 0 3.536l3.171 3.171a2.5 2.5 0 0 0 3.536 0l5.732-5.732a1 1 0 0 0 0-1.414L13.207 5.5a1 1 0 0 0-1.414 0L10.5 6.793zM18 17.5a.5.5 0 1 1-1 0c0-.433.234-.84.508-1.16.265.308.492.71.492 1.16m1 0a1.5 1.5 0 1 1-3 0c0-1.106.815-1.94 1.244-2.302a.4.4 0 0 1 .516-.004c.43.352 1.24 1.168 1.24 2.306"
        clipRule="evenodd"
      />
    </svg>
  )
})
