// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.lock.open.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgMTJIOC41YS41LjUgMCAwIDAtLjUuNXY0YS41LjUgMCAwIDAgLjUuNWg3YS41LjUgMCAwIDAgLjUtLjV2LTRhLjUuNSAwIDAgMC0uNS0uNXpNOSA4YTMgMyAwIDEgMSA2IDB2LjVhLjUuNSAwIDAgMS0xIDBWOGEyIDIgMCAxIDAtNCAwdjNoNS41YTEuNSAxLjUgMCAwIDEgMS41IDEuNXY0YTEuNSAxLjUgMCAwIDEtMS41IDEuNWgtN0ExLjUgMS41IDAgMCAxIDcgMTYuNXYtNEExLjUgMS41IDAgMCAxIDguNSAxMUg5eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-9589
 */
export const Icon24LockOpenSmall = memo(function Icon24LockOpenSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 12H8.5a.5.5 0 0 0-.5.5v4a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5v-4a.5.5 0 0 0-.5-.5zM9 8a3 3 0 1 1 6 0v.5a.5.5 0 0 1-1 0V8a2 2 0 1 0-4 0v3h5.5a1.5 1.5 0 0 1 1.5 1.5v4a1.5 1.5 0 0 1-1.5 1.5h-7A1.5 1.5 0 0 1 7 16.5v-4A1.5 1.5 0 0 1 8.5 11H9z"
        clipRule="evenodd"
      />
    </svg>
  )
})
