// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.boolean.exclude
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNSA1aDl2NGgtNGExIDEgMCAwIDAtMSAxdjRINXptNSAxMHY0aDl2LTloLTR2NGExIDEgMCAwIDEtMSAxeiIgY2xpcC1ydWxlPSJldmVub2RkIi8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgMTV2NGg5di05aC00djRhMSAxIDAgMCAxLTEgMXptLjUtMUgxMHYtNGg0djR6TTkgMTRINVY1aDl2NGgtNGExIDEgMCAwIDAtMSAxem0tMSAxSDVhMSAxIDAgMCAxLTEtMVY1YTEgMSAwIDAgMSAxLTFoOWExIDEgMCAwIDEgMSAxdjRoNGExIDEgMCAwIDEgMSAxdjlhMSAxIDAgMCAxLTEgMWgtOWExIDEgMCAwIDEtMS0xdi00eiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3965
 */
export const Icon24BooleanExclude = memo(function Icon24BooleanExclude(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M5 5h9v4h-4a1 1 0 0 0-1 1v4H5zm5 10v4h9v-9h-4v4a1 1 0 0 1-1 1z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 15v4h9v-9h-4v4a1 1 0 0 1-1 1zm.5-1H10v-4h4v4zM9 14H5V5h9v4h-4a1 1 0 0 0-1 1zm-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v4h4a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1h-9a1 1 0 0 1-1-1v-4z"
        clipRule="evenodd"
      />
    </svg>
  )
})
