// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.string
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTExLjUgMTNhMS41IDEuNSAwIDAgMCAxLjUtMS41di03QTEuNSAxLjUgMCAwIDAgMTEuNSAzaC03QTEuNSAxLjUgMCAwIDAgMyA0LjV2N0ExLjUgMS41IDAgMCAwIDQuNSAxM3ptLTctMWEuNS41IDAgMCAxLS41LS41di03YS41LjUgMCAwIDEgLjUtLjVoN2EuNS41IDAgMCAxIC41LjV2N2EuNS41IDAgMCAxLS41LjV6bTQtMmEuNS41IDAgMCAwIDAtMVY3SDlhLjUuNSAwIDAgMCAxIDB2LS41YS41LjUgMCAwIDAtLjQtLjQ5TDkuNSA2aC0zYS41LjUgMCAwIDAtLjQ5LjRMNiA2LjVWN2EuNS41IDAgMCAwIDEgMGguNXYyYS41LjUgMCAwIDAgMCAxeiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11842
 */
export const Icon16String = memo(function Icon16String(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M11.5 13a1.5 1.5 0 0 0 1.5-1.5v-7A1.5 1.5 0 0 0 11.5 3h-7A1.5 1.5 0 0 0 3 4.5v7A1.5 1.5 0 0 0 4.5 13zm-7-1a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5zm4-2a.5.5 0 0 0 0-1V7H9a.5.5 0 0 0 1 0v-.5a.5.5 0 0 0-.4-.49L9.5 6h-3a.5.5 0 0 0-.49.4L6 6.5V7a.5.5 0 0 0 1 0h.5v2a.5.5 0 0 0 0 1z"
      />
    </svg>
  )
})
