// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.design.viewer.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzBkOTlmZiIgZD0iTTAgMmEyIDIgMCAwIDEgMi0yaDEyYTIgMiAwIDAgMSAyIDJ2MTJhMiAyIDAgMCAxLTIgMkgyYTIgMiAwIDAgMS0yLTJ6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTQgNC42NDljMC0xLjI4MyAxLjQtMi4wNzUgMi40OTktMS40MTVsNS43NTggMy40NTUuMTc0LjEyYTEuNTMyIDEuNTMyIDAgMCAxIDAgMi4zODNsLS4xNzQuMTItNS43NTggMy40NTVjLTEuMS42Ni0yLjQ5OS0uMTMzLTIuNDk5LTEuNDE1em0xLjk4NC0uNTU4YS42NS42NSAwIDAgMC0uOTc4LjQ2NUw1IDQuNjQ5djYuNzAzbC4wMDYuMDkzYS42NS42NSAwIDAgMCAuODk2LjUwNmwuMDgyLS4wNDIgNS43NTgtMy40NTVhLjUzLjUzIDAgMCAwIDAtLjkwOHoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13873
 */
export const Icon16DesignViewerFavicon = memo(function Icon16DesignViewerFavicon(
  props: SVGIconProps,
) {
  return (
    <ColorTheme brand="design">
      <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M4 4.649c0-1.283 1.4-2.075 2.499-1.415l5.758 3.455.174.12a1.532 1.532 0 0 1 0 2.383l-.174.12-5.758 3.455c-1.1.66-2.499-.133-2.499-1.415zm1.984-.558a.65.65 0 0 0-.978.465L5 4.649v6.703l.006.093a.65.65 0 0 0 .896.506l.082-.042 5.758-3.455a.53.53 0 0 0 0-.908z"
        />
      </svg>
    </ColorTheme>
  )
})
