// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.file.design.repo
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzBkOTlmZiIgZD0iTTQgMjRoMTZhMiAyIDAgMCAwIDItMlY2Ljc0M2EzIDMgMCAwIDAtLjg3OS0yLjEyMkwxNy4zOC44OEEzIDMgMCAwIDAgMTUuMjU3IDBINGEyIDIgMCAwIDAtMiAydjIwYTIgMiAwIDAgMCAyIDIiLz4KICA8cGF0aCBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yMiA3di0uMjU3YTMgMyAwIDAgMC0uODc5LTIuMTIyTDE3LjM4Ljg4QTMgMyAwIDAgMCAxNS4yNTcgMGgtLjIzN0ExIDEgMCAwIDEgMTYgMXYzYTIgMiAwIDAgMCAyIDJoM2ExIDEgMCAwIDEgMSAxTTcgMTAuNWEuNS41IDAgMCAxIC41LS41aDFhMi41IDIuNSAwIDAgMSAyLjUgMi41djJhMS41IDEuNSAwIDAgMCAxLjUgMS41aDIuNzkzbC0xLjE0Ny0xLjE0NmEuNS41IDAgMCAxIC43MDgtLjcwOGwyIDJhLjUuNSAwIDAgMSAwIC43MDhsLTIgMmEuNS41IDAgMCAxLS43MDgtLjcwOEwxNS4yOTMgMTdIMTIuNWEyLjUgMi41IDAgMCAxLTIuNS0yLjV2LTJBMS41IDEuNSAwIDAgMCA4LjUgMTFoLTFhLjUuNSAwIDAgMS0uNS0uNW01LjUgMGEuNS41IDAgMCAxIC41LS41aDMuNWEuNS41IDAgMCAxIDAgMUgxM2EuNS41IDAgMCAxLS41LS41IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=606-6278
 */
export const Icon24FileDesignRepo = memo(function Icon24FileDesignRepo(props: SVGIconProps) {
  return (
    <ColorTheme brand="design">
      <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M4 24h16a2 2 0 0 0 2-2V6.743a3 3 0 0 0-.879-2.122L17.38.88A3 3 0 0 0 15.257 0H4a2 2 0 0 0-2 2v20a2 2 0 0 0 2 2"
        />
        <path
          fill="var(--color-icon-onbrand-tertiary)"
          fillRule="evenodd"
          d="M22 7v-.257a3 3 0 0 0-.879-2.122L17.38.88A3 3 0 0 0 15.257 0h-.237A1 1 0 0 1 16 1v3a2 2 0 0 0 2 2h3a1 1 0 0 1 1 1"
          clipRule="evenodd"
        />
        <path
          fill="var(--color-icon-onbrand)"
          fillRule="evenodd"
          d="M7 10.5a.5.5 0 0 1 .5-.5h1a2.5 2.5 0 0 1 2.5 2.5v2a1.5 1.5 0 0 0 1.5 1.5h2.793l-1.147-1.146a.5.5 0 0 1 .708-.708l2 2a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708-.708L15.293 17H12.5a2.5 2.5 0 0 1-2.5-2.5v-2A1.5 1.5 0 0 0 8.5 11h-1a.5.5 0 0 1-.5-.5m5.5 0a.5.5 0 0 1 .5-.5h3.5a.5.5 0 0 1 0 1H13a.5.5 0 0 1-.5-.5"
          clipRule="evenodd"
        />
      </svg>
    </ColorTheme>
  )
})
