// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.boolean.subtract
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgMTV2NGg5di05aC00djRhMSAxIDAgMCAxLTEgMXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTEwIDE5di00aDRhMSAxIDAgMCAwIDEtMXYtNGg0djl6bTAtNWg0VjVINXY5em0tNSAxaDR2NGExIDEgMCAwIDAgMSAxaDlhMSAxIDAgMCAwIDEtMXYtOWExIDEgMCAwIDAtMS0xaC00VjVhMSAxIDAgMCAwLTEtMUg1YTEgMSAwIDAgMC0xIDF2OWExIDEgMCAwIDAgMSAxIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3904
 */
export const Icon24BooleanSubtract = memo(function Icon24BooleanSubtract(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M10 15v4h9v-9h-4v4a1 1 0 0 1-1 1z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 19v-4h4a1 1 0 0 0 1-1v-4h4v9zm0-5h4V5H5v9zm-5 1h4v4a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-9a1 1 0 0 0-1-1h-4V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1"
        clipRule="evenodd"
      />
    </svg>
  )
})
