// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.cursor-chat
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE0LjUgNWE2LjUgNi41IDAgMSAxIDAgMTNoLTVBNi41IDYuNSAwIDAgMSAzIDExLjV2LTVBMS41IDEuNSAwIDAgMSA0LjUgNXptLTEwIDEtLjEuMDFhLjUuNSAwIDAgMC0uNC40OXY1YTUuNSA1LjUgMCAwIDAgNS4yMTcgNS40OTNMOS41IDE3aDVhNS41IDUuNSAwIDAgMCAuMjgzLTEwLjk5M0wxNC41IDZ6TTggMTAuNWExIDEgMCAxIDEgMCAyIDEgMSAwIDAgMSAwLTJtNCAwYTEgMSAwIDEgMSAwIDIgMSAxIDAgMCAxIDAtMm00IDBhMSAxIDAgMSAxIDAgMiAxIDEgMCAwIDEgMC0yIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7432
 */
export const Icon24CursorChat = memo(function Icon24CursorChat(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M14.5 5a6.5 6.5 0 1 1 0 13h-5A6.5 6.5 0 0 1 3 11.5v-5A1.5 1.5 0 0 1 4.5 5zm-10 1-.1.01a.5.5 0 0 0-.4.49v5a5.5 5.5 0 0 0 5.217 5.493L9.5 17h5a5.5 5.5 0 0 0 .283-10.993L14.5 6zM8 10.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2m4 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2m4 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"
      />
    </svg>
  )
})
