// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.action.overlay.swap.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNiA2LjVhLjUuNSAwIDAgMSAuNS0uNUg5YTIgMiAwIDAgMSAyIDJ2MS41YS41LjUgMCAwIDEtMSAwVjhhMSAxIDAgMCAwLTEtMUg2LjVhLjUuNSAwIDAgMS0uNS0uNW00LjUgNy41YS41LjUgMCAwIDEgLjUuNVYxNmEyIDIgMCAwIDEtMiAySDYuNWEuNS41IDAgMCAxIDAtMUg5YTEgMSAwIDAgMCAxLTF2LTEuNWEuNS41IDAgMCAxIC41LS41TTE4IDYuNWEuNS41IDAgMCAwLS41LS41SDE1YTIgMiAwIDAgMC0yIDJ2MS41YS41LjUgMCAwIDAgMSAwVjhhMSAxIDAgMCAxIDEtMWgyLjVhLjUuNSAwIDAgMCAuNS0uNU0xMy41IDE0YS41LjUgMCAwIDAtLjUuNVYxNmEyIDIgMCAwIDAgMiAyaDIuNWEuNS41IDAgMCAwIDAtMUgxNWExIDEgMCAwIDEtMS0xdi0xLjVhLjUuNSAwIDAgMC0uNS0uNW0tNS4xNDYtMy4xNDZhLjUuNSAwIDAgMC0uNzA4LS43MDhsLTEuNSAxLjVhLjUuNSAwIDAgMCAwIC43MDhsMS41IDEuNWEuNS41IDAgMCAwIC43MDgtLjcwOGwtLjY0Ny0uNjQ2aDguNTg2bC0uNjQ3LjY0NmEuNS41IDAgMCAwIC43MDguNzA4bDEuNS0xLjVhLjUuNSAwIDAgMCAwLS43MDhsLTEuNS0xLjVhLjUuNSAwIDAgMC0uNzA4LjcwOGwuNjQ3LjY0Nkg3LjcwN3oiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10035
 */
export const Icon24ActionOverlaySwapSmall = memo(function Icon24ActionOverlaySwapSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6 6.5a.5.5 0 0 1 .5-.5H9a2 2 0 0 1 2 2v1.5a.5.5 0 0 1-1 0V8a1 1 0 0 0-1-1H6.5a.5.5 0 0 1-.5-.5m4.5 7.5a.5.5 0 0 1 .5.5V16a2 2 0 0 1-2 2H6.5a.5.5 0 0 1 0-1H9a1 1 0 0 0 1-1v-1.5a.5.5 0 0 1 .5-.5M18 6.5a.5.5 0 0 0-.5-.5H15a2 2 0 0 0-2 2v1.5a.5.5 0 0 0 1 0V8a1 1 0 0 1 1-1h2.5a.5.5 0 0 0 .5-.5M13.5 14a.5.5 0 0 0-.5.5V16a2 2 0 0 0 2 2h2.5a.5.5 0 0 0 0-1H15a1 1 0 0 1-1-1v-1.5a.5.5 0 0 0-.5-.5m-5.146-3.146a.5.5 0 0 0-.708-.708l-1.5 1.5a.5.5 0 0 0 0 .708l1.5 1.5a.5.5 0 0 0 .708-.708l-.647-.646h8.586l-.647.646a.5.5 0 0 0 .708.708l1.5-1.5a.5.5 0 0 0 0-.708l-1.5-1.5a.5.5 0 0 0-.708.708l.647.646H7.707z"
        clipRule="evenodd"
      />
    </svg>
  )
})
