// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'
import { ColorTheme } from '@fpl/tokens'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.figjam.template.favicon
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iIzk3NDdmZiIgZD0iTTAgMmEyIDIgMCAwIDEgMi0yaDEyYTIgMiAwIDAgMSAyIDJ2MTJhMiAyIDAgMCAxLTIgMkgyYTIgMiAwIDAgMS0yLTJ6Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyLjY1MyAzLjAwOEExLjUgMS41IDAgMCAxIDE0IDQuNXY3bC0uMDA4LjE1M2ExLjUgMS41IDAgMCAxLTEuMzM5IDEuMzRMMTIuNSAxM2gtOWwtLjE1My0uMDA4YTEuNSAxLjUgMCAwIDEtMS4zNC0xLjMzOUwyIDExLjV2LTdhMS41IDEuNSAwIDAgMSAxLjM0Ny0xLjQ5MkwzLjUgM2g5ek0zIDExLjVhLjUuNSAwIDAgMCAuNS41SDVWN0gzek02IDd2NWg2LjVhLjUuNSAwIDAgMCAuNS0uNVY3ek0zLjUgNGEuNS41IDAgMCAwLS41LjVWNmgxMFY0LjVhLjUuNSAwIDAgMC0uNS0uNXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=606-6120
 */
export const Icon16FigjamTemplateFavicon = memo(function Icon16FigjamTemplateFavicon(
  props: SVGIconProps,
) {
  return (
    <ColorTheme brand="whiteboard">
      <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
        <path
          fill="var(--color-bg-brand)"
          d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2z"
        />
        <path
          fill="var(--color-icon-onbrand)"
          d="M12.653 3.008A1.5 1.5 0 0 1 14 4.5v7l-.008.153a1.5 1.5 0 0 1-1.339 1.34L12.5 13h-9l-.153-.008a1.5 1.5 0 0 1-1.34-1.339L2 11.5v-7a1.5 1.5 0 0 1 1.347-1.492L3.5 3h9zM3 11.5a.5.5 0 0 0 .5.5H5V7H3zM6 7v5h6.5a.5.5 0 0 0 .5-.5V7zM3.5 4a.5.5 0 0 0-.5.5V6h10V4.5a.5.5 0 0 0-.5-.5z"
        />
      </svg>
    </ColorTheme>
  )
})
