// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.dock-to-side
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNSA3LjVBMi41IDIuNSAwIDAgMSA3LjUgNWg5QTIuNSAyLjUgMCAwIDEgMTkgNy41djYuMTcyYzAgMi4yMjctMi42OTMgMy4zNDItNC4yNjggMS43NjdMMTAgMTAuNzA3VjE0YS41LjUgMCAwIDEtMSAwVjkuNWEuNS41IDAgMCAxIC41LS41SDE0YS41LjUgMCAwIDEgMCAxaC0zLjI5M2w0LjczMiA0LjczMmMuOTQ1Ljk0NSAyLjU2MS4yNzYgMi41NjEtMS4wNlY3LjVBMS41IDEuNSAwIDAgMCAxNi41IDZoLTlBMS41IDEuNSAwIDAgMCA2IDcuNXY5QTEuNSAxLjUgMCAwIDAgNy41IDE4aDVhLjUuNSAwIDAgMSAwIDFoLTVBMi41IDIuNSAwIDAgMSA1IDE2LjV6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1671
 */
export const Icon24DockToSide = memo(function Icon24DockToSide(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M5 7.5A2.5 2.5 0 0 1 7.5 5h9A2.5 2.5 0 0 1 19 7.5v6.172c0 2.227-2.693 3.342-4.268 1.767L10 10.707V14a.5.5 0 0 1-1 0V9.5a.5.5 0 0 1 .5-.5H14a.5.5 0 0 1 0 1h-3.293l4.732 4.732c.945.945 2.561.276 2.561-1.06V7.5A1.5 1.5 0 0 0 16.5 6h-9A1.5 1.5 0 0 0 6 7.5v9A1.5 1.5 0 0 0 7.5 18h5a.5.5 0 0 1 0 1h-5A2.5 2.5 0 0 1 5 16.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
