// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.visual.search.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTAgOC41YTEuNSAxLjUgMCAxIDEtMyAwIDEuNSAxLjUgMCAwIDEgMyAwbS0uMTIxIDIuMDg2YTIuNSAyLjUgMCAxIDEgLjcwNy0uNzA3bDEuMjY4IDEuMjY3YS41LjUgMCAwIDEtLjcwOC43MDh6TTE0IDYuNWEuNS41IDAgMCAxIC41LS41aDFBMi41IDIuNSAwIDAgMSAxOCA4LjV2MWEuNS41IDAgMCAxLTEgMHYtMUExLjUgMS41IDAgMCAwIDE1LjUgN2gtMWEuNS41IDAgMCAxLS41LS41TTYuNSAxNGEuNS41IDAgMCAxIC41LjV2MUExLjUgMS41IDAgMCAwIDguNSAxN2gxYS41LjUgMCAwIDEgMCAxaC0xQTIuNSAyLjUgMCAwIDEgNiAxNS41di0xYS41LjUgMCAwIDEgLjUtLjVtOC41MTUtLjU2TDE0LjcgMTQuN2wtMS4yNi4zMTVjLS41MDUuMTI2LS41MDUuODQ0IDAgLjk3bDEuMjYuMzE1LjMxNSAxLjI2Yy4xMjYuNTA1Ljg0NC41MDUuOTcgMGwuMzE1LTEuMjYgMS4yNi0uMzE1Yy41MDUtLjEyNi41MDUtLjg0NCAwLS45N0wxNi4zIDE0LjdsLS4zMTUtMS4yNmMtLjEyNi0uNTA1LS44NDQtLjUwNS0uOTcgMCIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-7902
 */
export const Icon24VisualSearchSmall = memo(function Icon24VisualSearchSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M10 8.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m-.121 2.086a2.5 2.5 0 1 1 .707-.707l1.268 1.267a.5.5 0 0 1-.708.708zM14 6.5a.5.5 0 0 1 .5-.5h1A2.5 2.5 0 0 1 18 8.5v1a.5.5 0 0 1-1 0v-1A1.5 1.5 0 0 0 15.5 7h-1a.5.5 0 0 1-.5-.5M6.5 14a.5.5 0 0 1 .5.5v1A1.5 1.5 0 0 0 8.5 17h1a.5.5 0 0 1 0 1h-1A2.5 2.5 0 0 1 6 15.5v-1a.5.5 0 0 1 .5-.5m8.515-.56L14.7 14.7l-1.26.315c-.505.126-.505.844 0 .97l1.26.315.315 1.26c.126.505.844.505.97 0l.315-1.26 1.26-.315c.505-.126.505-.844 0-.97L16.3 14.7l-.315-1.26c-.126-.505-.844-.505-.97 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
