// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.trash.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi41IDdhMSAxIDAgMCAxIDEtMWg5YTEgMSAwIDAgMSAxIDF2MWExIDEgMCAwIDEtMSAxaC0uMDM5bC0uMDggMUgxN2EuNS41IDAgMCAxIDAgMWgtLjdsLS40NTUgNS42MkExLjUgMS41IDAgMCAxIDE0LjM1IDE4aC00LjdhMS41IDEuNSAwIDAgMS0xLjQ5NS0xLjM4TDcuNyAxMUg3YS41LjUgMCAwIDEgMC0xaC42MmwtLjA4MS0xSDcuNWExIDEgMCAwIDEtMS0xem05LjQ5NCAxaC41MDZWN2gtOXYxem0tLjUzNiAxSDguNTQybC42MSA3LjU0YS41LjUgMCAwIDAgLjQ5OC40Nmg0LjdhLjUuNSAwIDAgMCAuNDk5LS40NnpNMTEuNSAxMS41YS41LjUgMCAwIDAtMSAwdjNhLjUuNSAwIDAgMCAxIDB6bTIgMGEuNS41IDAgMCAwLTEgMHYzYS41LjUgMCAwIDAgMSAweiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-11103
 */
export const Icon24TrashSmall = memo(function Icon24TrashSmall(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.5 7a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1h-.039l-.08 1H17a.5.5 0 0 1 0 1h-.7l-.455 5.62A1.5 1.5 0 0 1 14.35 18h-4.7a1.5 1.5 0 0 1-1.495-1.38L7.7 11H7a.5.5 0 0 1 0-1h.62l-.081-1H7.5a1 1 0 0 1-1-1zm9.494 1h.506V7h-9v1zm-.536 1H8.542l.61 7.54a.5.5 0 0 0 .498.46h4.7a.5.5 0 0 0 .499-.46zM11.5 11.5a.5.5 0 0 0-1 0v3a.5.5 0 0 0 1 0zm2 0a.5.5 0 0 0-1 0v3a.5.5 0 0 0 1 0z"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 6a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h.039l.08 1H6.5a.5.5 0 0 0 0 1h.7l.455 5.62A1.5 1.5 0 0 0 9.15 18h4.7a1.5 1.5 0 0 0 1.495-1.38L15.8 11h.7a.5.5 0 0 0 0-1h-.62l.081-1H16a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1zm8.505 2H7V7h9v1zM8.042 9h6.916l-.61 7.54a.5.5 0 0 1-.498.46h-4.7a.5.5 0 0 1-.499-.46zm2.458 2a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
