// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.dev.edited
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNy4xMDYgNC4xN2ExIDEgMCAwIDEgMS43ODkuMDAxbDMuMTkgNi4zODJBMSAxIDAgMCAxIDExLjE5MiAxMkg0LjgxYTEgMSAwIDAgMS0uODk0LTEuNDQ3ek04IDQuNjE5IDQuODEgMTFoNi4zODF6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-13151
 */
export const Icon16DevEdited = memo(function Icon16DevEdited(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7.106 4.17a1 1 0 0 1 1.789.001l3.19 6.382A1 1 0 0 1 11.192 12H4.81a1 1 0 0 1-.894-1.447zM8 4.619 4.81 11h6.381z"
        clipRule="evenodd"
      />
    </svg>
  )
})
