// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.rotation-origin.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE0LjUgMTBhLjUuNSAwIDAgMSAuNS41djEuMDQxQTMgMyAwIDAgMSAxNy40NTcgMTRIMTguNWEuNS41IDAgMCAxIDAgMWgtMS4wNDNBMyAzIDAgMCAxIDE1IDE3LjQ1OFYxOC41YS41LjUgMCAwIDEtMSAwdi0xLjA0MkEzIDMgMCAwIDEgMTEuNTQyIDE1SDEwLjVhLjUuNSAwIDAgMSAwLTFoMS4wNDJBMyAzIDAgMCAxIDE0IDExLjU0MVYxMC41YS41LjUgMCAwIDEgLjUtLjVtLTEuOTM0IDVBMiAyIDAgMCAwIDE0IDE2LjQzNFYxNXpNMTUgMTYuNDM0QTIgMiAwIDAgMCAxNi40MzUgMTVIMTV6TTEzLjY1NCA2LjAwOEExLjUgMS41IDAgMCAxIDE1IDcuNXYxYS41LjUgMCAxIDEtMSAwdi0xYS41LjUgMCAwIDAtLjUtLjVoLTZhLjUuNSAwIDAgMC0uNDkuNEw3IDcuNXY2YS41LjUgMCAwIDAgLjUuNWgxYS41LjUgMCAwIDEgMCAxaC0xbC0uMTUzLS4wMDhhMS41IDEuNSAwIDAgMS0xLjMzOS0xLjMzOUw2IDEzLjV2LTZhMS41IDEuNSAwIDAgMSAxLjM0Ny0xLjQ5Mkw3LjUgNmg2ek0xNCAxMi41NjVBMiAyIDAgMCAwIDEyLjU2NiAxNEgxNHpNMTUgMTRoMS40MzVBMiAyIDAgMCAwIDE1IDEyLjU2NXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=6598-8287
 */
export const Icon24RotationOriginSmall = memo(function Icon24RotationOriginSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M14.5 10a.5.5 0 0 1 .5.5v1.041A3 3 0 0 1 17.457 14H18.5a.5.5 0 0 1 0 1h-1.043A3 3 0 0 1 15 17.458V18.5a.5.5 0 0 1-1 0v-1.042A3 3 0 0 1 11.542 15H10.5a.5.5 0 0 1 0-1h1.042A3 3 0 0 1 14 11.541V10.5a.5.5 0 0 1 .5-.5m-1.934 5A2 2 0 0 0 14 16.434V15zM15 16.434A2 2 0 0 0 16.435 15H15zM13.654 6.008A1.5 1.5 0 0 1 15 7.5v1a.5.5 0 1 1-1 0v-1a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0-.49.4L7 7.5v6a.5.5 0 0 0 .5.5h1a.5.5 0 0 1 0 1h-1l-.153-.008a1.5 1.5 0 0 1-1.339-1.339L6 13.5v-6a1.5 1.5 0 0 1 1.347-1.492L7.5 6h6zM14 12.565A2 2 0 0 0 12.566 14H14zM15 14h1.435A2 2 0 0 0 15 12.565z"
      />
    </svg>
  )
})
