// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.chevron
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE0LjUyNyA1LjAwOGExLjUgMS41IDAgMCAxIC45MTIuNDMxbDUuMTQ3IDUuMTQ3LjEzNy4xNTFhMiAyIDAgMCAxIDAgMi41MjZsLS4xMzcuMTUxLTUuMTQ3IDUuMTQ3YTEuNSAxLjUgMCAwIDEtLjkxMi40MzFMMTQuMzggMTlINC4wN2MtMS4xMiAwLTEuNjc1LTEuMzYyLS44NzMtMi4xNDVMOC4xNzMgMTIgMy4xOTcgNy4xNDVDMi4zOTUgNi4zNjIgMi45NSA1IDQuMDcgNWgxMC4zMXpNNC4wNyA2YS4yNS4yNSAwIDAgMC0uMTc1LjQyOWw0Ljk3NiA0Ljg1NS43MzMuNzE2LS43MzMuNzE2LTQuOTc2IDQuODU1QS4yNS4yNSAwIDAgMCA0LjA3IDE4aDEwLjMxYy4xMzIgMCAuMjYtLjA1My4zNTMtLjE0Nmw1LjE0Ny01LjE0N2ExIDEgMCAwIDAgMC0xLjQxNGwtNS4xNDctNS4xNDdBLjUuNSAwIDAgMCAxNC4zOCA2eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7772
 */
export const Icon24ShapeChevron = memo(function Icon24ShapeChevron(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M14.527 5.008a1.5 1.5 0 0 1 .912.431l5.147 5.147.137.151a2 2 0 0 1 0 2.526l-.137.151-5.147 5.147a1.5 1.5 0 0 1-.912.431L14.38 19H4.07c-1.12 0-1.675-1.362-.873-2.145L8.173 12 3.197 7.145C2.395 6.362 2.95 5 4.07 5h10.31zM4.07 6a.25.25 0 0 0-.175.429l4.976 4.855.733.716-.733.716-4.976 4.855A.25.25 0 0 0 4.07 18h10.31c.132 0 .26-.053.353-.146l5.147-5.147a1 1 0 0 0 0-1.414l-5.147-5.147A.5.5 0 0 0 14.38 6z"
      />
    </svg>
  )
})
