// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.rich-text
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTEyLjUgMTJhLjUuNSAwIDAgMSAwIDFoLTlhLjUuNSAwIDAgMSAwLTF6bTAtM2EuNS41IDAgMCAxIDAgMWgtOWEuNS41IDAgMCAxIDAtMXpNNi42IDMuMDFhLjUuNSAwIDAgMSAuNC40OVY0YS41LjUgMCAwIDEtMSAwaC0uNXYyYS41LjUgMCAwIDEgMCAxaC0xYS41LjUgMCAwIDEgMC0xVjRINGEuNS41IDAgMCAxLTEgMHYtLjVsLjAxLS4xQS41LjUgMCAwIDEgMy41IDNoM3pNMTIuNSA2YS41LjUgMCAwIDEgMCAxaC0zYS41LjUgMCAwIDEgMC0xem0wLTNhLjUuNSAwIDAgMSAwIDFoLTNhLjUuNSAwIDAgMSAwLTF6Ii8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1982-29954
 */
export const Icon16RichText = memo(function Icon16RichText(props: SVGIconProps) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        d="M12.5 12a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1zm0-3a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1zM6.6 3.01a.5.5 0 0 1 .4.49V4a.5.5 0 0 1-1 0h-.5v2a.5.5 0 0 1 0 1h-1a.5.5 0 0 1 0-1V4H4a.5.5 0 0 1-1 0v-.5l.01-.1A.5.5 0 0 1 3.5 3h3zM12.5 6a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1zm0-3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1z"
      />
    </svg>
  )
})
