// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.generate.code.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJtMTYuNyA1LjY5OS4zMTUtMS4yNmMuMTI2LS41MDUuODQ0LS41MDUuOTcgMEwxOC4zIDUuN2wxLjI2LjMxNWMuNTA1LjEyNi41MDUuODQ0IDAgLjk3TDE4LjMgNy4zbC0uMzE1IDEuMjZjLS4xMjYuNTA1LS44NDQuNTA1LS45NyAwTDE2LjcgNy4zbC0xLjI2LS4zMTVjLS41MDUtLjEyNi0uNTA1LS44NDQgMC0uOTd6TTEzIDZhLjUuNSAwIDAgMSAwIDFINy41YS41LjUgMCAwIDAtLjUuNXY5YS41LjUgMCAwIDAgLjUuNWg5YS41LjUgMCAwIDAgLjUtLjVWMTFhLjUuNSAwIDAgMSAxIDB2NS41YTEuNSAxLjUgMCAwIDEtMS41IDEuNWgtOUExLjUgMS41IDAgMCAxIDYgMTYuNXYtOUExLjUgMS41IDAgMCAxIDcuNSA2em0tMi4xNDYgNC4xNDZhLjUuNSAwIDAgMSAwIC43MDhMOS43MDcgMTJsMS4xNDcgMS4xNDZhLjUuNSAwIDAgMS0uNzA4LjcwOGwtMS41LTEuNWEuNS41IDAgMCAxIDAtLjcwOGwxLjUtMS41YS41LjUgMCAwIDEgLjcwOCAwbTIuMjkyLjcwOGEuNS41IDAgMCAxIC43MDgtLjcwOGwxLjUgMS41YS41LjUgMCAwIDEgMCAuNzA4bC0xLjUgMS41YS41LjUgMCAwIDEtLjcwOC0uNzA4TDE0LjI5MyAxMnoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=977-5806
 */
export const Icon24GenerateCodeSmall = memo(function Icon24GenerateCodeSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="m16.7 5.699.315-1.26c.126-.505.844-.505.97 0L18.3 5.7l1.26.315c.505.126.505.844 0 .97L18.3 7.3l-.315 1.26c-.126.505-.844.505-.97 0L16.7 7.3l-1.26-.315c-.505-.126-.505-.844 0-.97zM13 6a.5.5 0 0 1 0 1H7.5a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V11a.5.5 0 0 1 1 0v5.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 6 16.5v-9A1.5 1.5 0 0 1 7.5 6zm-2.146 4.146a.5.5 0 0 1 0 .708L9.707 12l1.147 1.146a.5.5 0 0 1-.708.708l-1.5-1.5a.5.5 0 0 1 0-.708l1.5-1.5a.5.5 0 0 1 .708 0m2.292.708a.5.5 0 0 1 .708-.708l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708-.708L14.293 12z"
        clipRule="evenodd"
      />
    </svg>
  )
})
