// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.document
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE4IDRhMiAyIDAgMCAxIDIgMnYxM2ExIDEgMCAwIDEtMS4zNzEuOTI5bC0yLjM4OS0uOTU1YTMuMTggMy4xOCAwIDAgMC0zLjQ3Ljc0NiA1LjE4IDUuMTggMCAwIDEtNi4zMzYuODg1bC0uMTk3LS4xMkw0LjQ2IDE5LjM0QTEgMSAwIDAgMSA0IDE4LjVWNmEyIDIgMCAwIDEgMi0yek02IDVsLS4xMDMuMDA1QTEgMSAwIDAgMCA1IDZ2MTIuNWwxLjc3OCAxLjE0M2E0LjE4IDQuMTggMCAwIDAgNS4xMzktLjQ4NmwuMTMyLS4xM2E0LjE4IDQuMTggMCAwIDEgNC41NjItLjk4MkwxOSAxOVY2YTEgMSAwIDAgMC0uODk4LS45OTVMMTggNXoiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7792
 */
export const Icon24ShapeDocument = memo(function Icon24ShapeDocument(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M18 4a2 2 0 0 1 2 2v13a1 1 0 0 1-1.371.929l-2.389-.955a3.18 3.18 0 0 0-3.47.746 5.18 5.18 0 0 1-6.336.885l-.197-.12L4.46 19.34A1 1 0 0 1 4 18.5V6a2 2 0 0 1 2-2zM6 5l-.103.005A1 1 0 0 0 5 6v12.5l1.778 1.143a4.18 4.18 0 0 0 5.139-.486l.132-.13a4.18 4.18 0 0 1 4.562-.982L19 19V6a1 1 0 0 0-.898-.995L18 5z"
      />
    </svg>
  )
})
