// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.sound.off.toggle.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTQgNy44Nzl2LTEuODhhMSAxIDAgMCAwLTEuNzA3LS43MDZMOS41ODYgOEg3LjVBMS41IDEuNSAwIDAgMCA2IDkuNXY1YzAgLjM4My4xNDQuNzMzLjM4Ljk5OGwuNzExLS43MUEuNS41IDAgMCAxIDcgMTQuNXYtNWEuNS41IDAgMCAxIC41LS41SDEwbDItMiAxLTF2Mi44Nzl6bTAgNC4yNDItMSAxVjE4bC0xLTEtMS40NC0xLjQ0LS43MDYuNzA4IDIuNDM5IDIuNDM5QTEgMSAwIDAgMCAxNCAxOHptMi4wNjktMi4wNjguNzEtLjcxYTMuNTAxIDMuNTAxIDAgMCAxLTEuMjE3IDUuOTkzYy0uMjkuMDkyLS41NjItLjE0NC0uNTYyLS40NDh2LS4wM2MwLS4yMzcuMTctLjQzNy4zOTItLjUyMmEyLjUgMi41IDAgMCAwIC42NzctNC4yODNtLTEuMDEzIDEuMDEzLjE3Mi0uMTcyYy4xMTMtLjA1Ni4yNDgtLjA0NC4zNi4wNzMuMjU1LjI2OS40MTIuNjMyLjQxMiAxLjAzM3MtLjE1Ny43NjQtLjQxMiAxLjAzM2MtLjIzOC4yNS0uNTg4LjAyLS41ODgtLjMyNnYtMS40MTVhLjUuNSAwIDAgMSAuMDU2LS4yMjZtMi43OTgtNC45MmEuNS41IDAgMCAxIDAgLjcwOGwtMTEgMTFhLjUuNSAwIDEgMS0uNzA4LS43MDdsMTEtMTFhLjUuNSAwIDAgMSAuNzA4IDAiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-1863
 */
export const Icon24SoundOffToggleSmall = memo(function Icon24SoundOffToggleSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M14 7.879v-1.88a1 1 0 0 0-1.707-.706L9.586 8H7.5A1.5 1.5 0 0 0 6 9.5v5c0 .383.144.733.38.998l.711-.71A.5.5 0 0 1 7 14.5v-5a.5.5 0 0 1 .5-.5H10l2-2 1-1v2.879zm0 4.242-1 1V18l-1-1-1.44-1.44-.706.708 2.439 2.439A1 1 0 0 0 14 18v-5.88m2.069-2.068.71-.71a3.501 3.501 0 0 1-1.217 5.993c-.29.092-.562-.144-.562-.448v-.03c0-.237.17-.437.392-.522a2.5 2.5 0 0 0 .677-4.283m-1.013 1.013.172-.172c.113-.056.248-.044.36.073.255.269.412.632.412 1.033s-.157.764-.412 1.033c-.238.25-.588.02-.588-.326v-1.415a.5.5 0 0 1 .056-.226m2.798-4.92a.5.5 0 0 1 0 .708l-11 11a.5.5 0 1 1-.708-.707l11-11a.5.5 0 0 1 .708 0"
        clipRule="evenodd"
      />
    </svg>
  )
})
