// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.interaction.leave.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTYuNSA2QTEuNSAxLjUgMCAwIDEgMTggNy41djFhLjUuNSAwIDAgMS0xIDB2LTFhLjUuNSAwIDAgMC0uNS0uNWgtOWEuNS41IDAgMCAwLS41LjV2OWEuNS41IDAgMCAwIC41LjVoOWEuNS41IDAgMCAwIC41LS41di0xYS41LjUgMCAwIDEgMSAwdjFhMS41IDEuNSAwIDAgMS0xLjUgMS41aC05QTEuNSAxLjUgMCAwIDEgNiAxNi41di05QTEuNSAxLjUgMCAwIDEgNy41IDZ6bS00Ljg1NCAzLjE0NmEuNS41IDAgMCAxIC43MDggMGwyLjUgMi41YS41LjUgMCAwIDEgMCAuNzA4bC0yLjUgMi41YS41LjUgMCAwIDEtLjcwOC0uNzA4bDEuNjQ3LTEuNjQ2SDkuNWEuNS41IDAgMCAxIDAtMWgzLjc5M2wtMS42NDctMS42NDZhLjUuNSAwIDAgMSAwLS43MDgiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-9803
 */
export const Icon24InteractionLeaveSmall = memo(function Icon24InteractionLeaveSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M16.5 6A1.5 1.5 0 0 1 18 7.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 1 1 0v1a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 6 16.5v-9A1.5 1.5 0 0 1 7.5 6zm-4.854 3.146a.5.5 0 0 1 .708 0l2.5 2.5a.5.5 0 0 1 0 .708l-2.5 2.5a.5.5 0 0 1-.708-.708l1.647-1.646H9.5a.5.5 0 0 1 0-1h3.793l-1.647-1.646a.5.5 0 0 1 0-.708"
        clipRule="evenodd"
      />
    </svg>
  )
})
