// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.vote
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE0LjUgM2EuNS41IDAgMCAxIC41LjVWN2gyLjVhLjUuNSAwIDAgMSAuNDY0LjMxNGwyIDVBLjUuNSAwIDAgMSAyMCAxMi41djdhLjUuNSAwIDAgMS0uNS41aC0xNWEuNS41IDAgMCAxLS41LS41di03YS41LjUgMCAwIDEgLjAzNi0uMTg1bDItNSAuMDMzLS4wNjlBLjUuNSAwIDAgMSA2LjUgN0g5VjMuNWwuMDEtLjFBLjUuNSAwIDAgMSA5LjUgM3pNNSAxOWgxNHYtNkg1em0uMjM4LTdoMTMuNTI0bC0xLjYtNEgxNXYyaC41YS41LjUgMCAwIDEgMCAxaC03YS41LjUgMCAwIDEgMC0xSDlWOEg2LjgzOHpNMTAgMTBoNFY0aC00eiIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7480
 */
export const Icon24Vote = memo(function Icon24Vote(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M14.5 3a.5.5 0 0 1 .5.5V7h2.5a.5.5 0 0 1 .464.314l2 5A.5.5 0 0 1 20 12.5v7a.5.5 0 0 1-.5.5h-15a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .036-.185l2-5 .033-.069A.5.5 0 0 1 6.5 7H9V3.5l.01-.1A.5.5 0 0 1 9.5 3zM5 19h14v-6H5zm.238-7h13.524l-1.6-4H15v2h.5a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1H9V8H6.838zM10 10h4V4h-4z"
      />
    </svg>
  )
})
