// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.noodle.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE1LjE0NyA1LjY0NmEuNS41IDAgMCAxIC43MDcgMGwyIDIgLjA2NC4wNzlhLjUuNSAwIDAgMS0uMDY0LjYyOGwtMiAyLS4wNzkuMDY1YS41LjUgMCAwIDEtLjY5My0uNjkzbC4wNjQtLjA3OUwxNi4yOTMgOC41SDE0LjVBMS41IDEuNSAwIDAgMCAxMyAxMHY0YTIuNSAyLjUgMCAwIDEtMi41IDIuNUgxMHEtLjAzMy0uMDAxLS4wNjQtLjAwN0ExLjk5OCAxLjk5OCAwIDAgMSA2IDE2YTIgMiAwIDAgMSAzLjkzNi0uNDk0cS4wMy0uMDA1LjA2NC0uMDA2aC41QTEuNSAxLjUgMCAwIDAgMTIgMTR2LTRhMi41IDIuNSAwIDAgMSAyLjUtMi41aDEuNzkzbC0xLjE0Ni0xLjE0N2EuNS41IDAgMCAxIDAtLjcwN004IDE1YTEgMSAwIDEgMCAwIDIgMSAxIDAgMCAwIDAtMiIvPjwvc3ZnPg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3640-8832
 */
export const Icon24NoodleSmall = memo(function Icon24NoodleSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M15.147 5.646a.5.5 0 0 1 .707 0l2 2 .064.079a.5.5 0 0 1-.064.628l-2 2-.079.065a.5.5 0 0 1-.693-.693l.064-.079L16.293 8.5H14.5A1.5 1.5 0 0 0 13 10v4a2.5 2.5 0 0 1-2.5 2.5H10q-.033-.001-.064-.007A1.998 1.998 0 0 1 6 16a2 2 0 0 1 3.936-.494q.03-.005.064-.006h.5A1.5 1.5 0 0 0 12 14v-4a2.5 2.5 0 0 1 2.5-2.5h1.793l-1.146-1.147a.5.5 0 0 1 0-.707M8 15a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
      />
    </svg>
  )
})
