// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.connected-project.paused.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTYuNjQ2IDYuMTQ1YS41LjUgMCAwIDEgLjcwOC43MDdsLTExIDExYS41LjUgMCAxIDEtLjcwOC0uNzA3em0tMy44MS45OTJjLjQzMS0uMTAzLjY1NC4zOTYuMzQuNzFsLS4yMzEuMjMyYS41LjUgMCAwIDEtLjIxLjEyN3EtLjM3Ni4xMjYtLjczMy4zM2E0IDQgMCAwIDAtMS43OTQgMi4xOTcuNS41IDAgMCAxLS4xMjguMjFsLS42MzcuNjM3Yy0uMTU3LjE1Ny0uNDQuMTQxLS40MTctLjA4YTUgNSAwIDAgMSAyLjQ3Ni0zLjgzIDUgNSAwIDAgMSAxLjMzNC0uNTMzbTQuMzM1IDEuNjY1Yy0uMTk2LjE5Ni0uMTkyLjUxMi0uMDIyLjczcS4xNzIuMjIuMzE3LjQ2OWE0IDQgMCAwIDEtMi45NjQgNS45N2MtLjI3NS4wMzQtLjUuMjU1LS41LjUzMXMuMjI1LjUwMy41LjQ3NWE1IDUgMCAwIDAgMy4zNTctOC4xNi40NjQuNDY0IDAgMCAwLS42ODgtLjAxNW0tNC4yNDcgNC4yNDdhLjUuNSAwIDAgMC0uMTI3LjIxIDQgNCAwIDAgMS0yLjUzOCAyLjUzOC41LjUgMCAwIDAtLjIxMS4xMjhsLS4yMy4yM2MtLjMxNC4zMTQtLjA5MS44MTMuMzQuNzFsLjEzNS0uMDM1YTUgNSAwIDAgMCAzLjY4My00LjMzYy4wMjItLjIyNC0uMjY0LS4yNC0uNDIzLS4wOHptLTcuMDc2IDEuNDE3Yy4xNy4yMTguMTc1LjUzNS0uMDIxLjczcy0uNTEzLjE5Ny0uNjg4LS4wMTVBNSA1IDAgMCAxIDguNSA3LjAyNWMuMjc1LS4wMjguNS4xOTkuNS40NzVzLS4yMjUuNDk3LS40OTguNTMxYTQgNCAwIDAgMC0yLjY1MyA2LjQzNSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3175-6476
 */
export const Icon24ConnectedProjectPausedSmall = memo(function Icon24ConnectedProjectPausedSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M16.646 6.145a.5.5 0 0 1 .708.707l-11 11a.5.5 0 1 1-.708-.707zm-3.81.992c.431-.103.654.396.34.71l-.231.232a.5.5 0 0 1-.21.127q-.376.126-.733.33a4 4 0 0 0-1.794 2.197.5.5 0 0 1-.128.21l-.637.637c-.157.157-.44.141-.417-.08a5 5 0 0 1 2.476-3.83 5 5 0 0 1 1.334-.533m4.335 1.665c-.196.196-.192.512-.022.73q.172.22.317.469a4 4 0 0 1-2.964 5.97c-.275.034-.5.255-.5.531s.225.503.5.475a5 5 0 0 0 3.357-8.16.464.464 0 0 0-.688-.015m-4.247 4.247a.5.5 0 0 0-.127.21 4 4 0 0 1-2.538 2.538.5.5 0 0 0-.211.128l-.23.23c-.314.314-.091.813.34.71l.135-.035a5 5 0 0 0 3.683-4.33c.022-.224-.264-.24-.423-.08zm-7.076 1.417c.17.218.175.535-.021.73s-.513.197-.688-.015A5 5 0 0 1 8.5 7.025c.275-.028.5.199.5.475s-.225.497-.498.531a4 4 0 0 0-2.653 6.435"
        clipRule="evenodd"
      />
    </svg>
  )
})
