// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.array-linear-vertical
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICA8cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTMgNGExIDEgMCAwIDAtMS0xIC41LjUgMCAwIDAgMCAxIC41LjUgMCAwIDAgMSAwbTAgMmEuNS41IDAgMCAwLTEgMHYxYS41LjUgMCAwIDAgMSAwem0wIDNhLjUuNSAwIDAgMC0xIDB2MWEuNS41IDAgMCAwIDEgMHptMCAzYS41LjUgMCAwIDAtMSAwIC41LjUgMCAwIDAgMCAxIDEgMSAwIDAgMCAxLTFtLTMtOGEuNS41IDAgMCAwIDAtMUg5YS41LjUgMCAwIDAgMCAxem0wIDlhLjUuNSAwIDAgMCAwLTFIOWEuNS41IDAgMCAwIDAgMXpNNyA0YS41LjUgMCAwIDAgMC0xSDZhLjUuNSAwIDAgMCAwIDF6bTAgOWEuNS41IDAgMCAwIDAtMUg2YS41LjUgMCAwIDAgMCAxek00IDRhLjUuNSAwIDAgMCAwLTEgMSAxIDAgMCAwLTEgMSAuNS41IDAgMCAwIDEgMG0wIDlhLjUuNSAwIDAgMCAwLTEgLjUuNSAwIDAgMC0xIDAgMSAxIDAgMCAwIDEgMW0wLTdhLjUuNSAwIDAgMC0xIDB2MWEuNS41IDAgMCAwIDEgMHptMCAzYS41LjUgMCAwIDAtMSAwdjFhLjUuNSAwIDAgMCAxIDB6bTYuNS00YS41LjUgMCAwIDEgMCAxaC01YS41LjUgMCAwIDEgMC0xem0wIDIuNWEuNS41IDAgMCAxIDAgMWgtNWEuNS41IDAgMCAxIDAtMXptLjUgM2EuNS41IDAgMCAwLS41LS41aC01YS41LjUgMCAwIDAgMCAxaDVhLjUuNSAwIDAgMCAuNS0uNSIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1228-7731
 */
export const Icon16ArrayLinearVertical = memo(function Icon16ArrayLinearVertical(
  props: SVGIconProps,
) {
  return (
    <svg width="16" height="16" fill="none" viewBox="0 0 16 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M13 4a1 1 0 0 0-1-1 .5.5 0 0 0 0 1 .5.5 0 0 0 1 0m0 2a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm0 3a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm0 3a.5.5 0 0 0-1 0 .5.5 0 0 0 0 1 1 1 0 0 0 1-1m-3-8a.5.5 0 0 0 0-1H9a.5.5 0 0 0 0 1zm0 9a.5.5 0 0 0 0-1H9a.5.5 0 0 0 0 1zM7 4a.5.5 0 0 0 0-1H6a.5.5 0 0 0 0 1zm0 9a.5.5 0 0 0 0-1H6a.5.5 0 0 0 0 1zM4 4a.5.5 0 0 0 0-1 1 1 0 0 0-1 1 .5.5 0 0 0 1 0m0 9a.5.5 0 0 0 0-1 .5.5 0 0 0-1 0 1 1 0 0 0 1 1m0-7a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm0 3a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0zm6.5-4a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zm0 2.5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zm.5 3a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5"
        clipRule="evenodd"
      />
    </svg>
  )
})
