// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.stroke-join-round
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNi41IDZhLjUuNSAwIDAgMCAwIDFoNWE1LjUgNS41IDAgMCAxIDUuNSA1LjV2NWEuNS41IDAgMCAwIDEgMHYtNUE2LjUgNi41IDAgMCAwIDExLjUgNnoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTExIDE2LjQyOVYxNy41YS41LjUgMCAwIDAgMSAwdi0xLjA3MWEuNS41IDAgMCAwLTEgME0xMSAxM3YuNTcxYS41LjUgMCAwIDAgMSAwVjEyLjVhLjUuNSAwIDAgMC0uNC0uNDlsLS4xLS4wMWgtMS4wNzFhLjUuNSAwIDAgMCAwIDF6bS0zLjMyOC0uOTktLjEtLjAxSDYuNWEuNS41IDAgMCAwIDAgMWgxLjA3MWwuMS0uMDFhLjUuNSAwIDAgMCAwLS45OCIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-5826
 */
export const Icon24StrokeJoinRound = memo(function Icon24StrokeJoinRound(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M6.5 6a.5.5 0 0 0 0 1h5a5.5 5.5 0 0 1 5.5 5.5v5a.5.5 0 0 0 1 0v-5A6.5 6.5 0 0 0 11.5 6z"
        clipRule="evenodd"
      />
      <path
        fill="var(--color-icon-tertiary)"
        fillRule="evenodd"
        d="M11 16.429V17.5a.5.5 0 0 0 1 0v-1.071a.5.5 0 0 0-1 0M11 13v.571a.5.5 0 0 0 1 0V12.5a.5.5 0 0 0-.4-.49l-.1-.01h-1.071a.5.5 0 0 0 0 1zm-3.328-.99-.1-.01H6.5a.5.5 0 0 0 0 1h1.071l.1-.01a.5.5 0 0 0 0-.98"
        clipRule="evenodd"
      />
    </svg>
  )
})
