// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.education
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMi41IDkuNDk1YTEgMSAwIDAgMSAuNjItLjkyNWw4LjExOS0zLjM0M2EyIDIgMCAwIDEgMS41MjIgMGw4LjEyIDMuMzQzYTEgMSAwIDAgMSAwIDEuODVsLS44ODEuMzYyVjE1LjVhLjUuNSAwIDAgMS0xIDB2LTQuMzA2bC0xIC40MTJWMTZjMCAuNjQtLjMyOCAxLjE0OC0uNzA2IDEuNTA1LS4zNzUuMzU1LS44NjUuNjI5LTEuMzg3LjgzOC0xLjA1LjQyLTIuNDMyLjY1Ny0zLjkwNy42NTdzLTIuODU3LS4yMzctMy45MDctLjY1N2MtLjUyMi0uMjEtMS4wMTItLjQ4My0xLjM4Ny0uODM4QzYuMzI4IDE3LjE0OCA2IDE2LjY0IDYgMTZ2LTQuMzk0bC0yLjg4LTEuMTg3YTEgMSAwIDAgMS0uNjItLjkyNE03IDEyLjAxN1YxNmMwIDEuMTA1IDIuMjM5IDIgNSAyczUtLjg5NSA1LTJ2LTMuOTgzbC00LjIzOCAxLjc0NmEyIDIgMCAwIDEtMS41MjQgMHpNMy41IDkuNDk1bDEuMzEzLjU0IDYuODA2IDIuODAzYTEgMSAwIDAgMCAuNzYyIDBsNi44MDYtMi44MDMgMS4zMTMtLjU0LTEuMzEzLS41NDEtNi44MDYtMi44MDNhMSAxIDAgMCAwLS43NjIgMEw0LjgxMyA4Ljk1NHoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=875-5557
 */
export const Icon24Education = memo(function Icon24Education(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M2.5 9.495a1 1 0 0 1 .62-.925l8.119-3.343a2 2 0 0 1 1.522 0l8.12 3.343a1 1 0 0 1 0 1.85l-.881.362V15.5a.5.5 0 0 1-1 0v-4.306l-1 .412V16c0 .64-.328 1.148-.706 1.505-.375.355-.865.629-1.387.838-1.05.42-2.432.657-3.907.657s-2.857-.237-3.907-.657c-.522-.21-1.012-.483-1.387-.838C6.328 17.148 6 16.64 6 16v-4.394l-2.88-1.187a1 1 0 0 1-.62-.924M7 12.017V16c0 1.105 2.239 2 5 2s5-.895 5-2v-3.983l-4.238 1.746a2 2 0 0 1-1.524 0zM3.5 9.495l1.313.54 6.806 2.803a1 1 0 0 0 .762 0l6.806-2.803 1.313-.54-1.313-.541-6.806-2.803a1 1 0 0 0-.762 0L4.813 8.954z"
        clipRule="evenodd"
      />
    </svg>
  )
})
