// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.password.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNNyA5aDEwYTEgMSAwIDAgMSAxIDF2NGExIDEgMCAwIDEtMSAxSDdhMSAxIDAgMCAxLTEtMXYtNGExIDEgMCAwIDEgMS0xbS0yIDFhMiAyIDAgMCAxIDItMmgxMGEyIDIgMCAwIDEgMiAydjRhMiAyIDAgMCAxLTIgMkg3YTIgMiAwIDAgMS0yLTJ6bTcgM2ExIDEgMCAxIDAgMC0yIDEgMSAwIDAgMCAwIDJtNC0xYTEgMSAwIDEgMS0yIDAgMSAxIDAgMCAxIDIgMG0tNyAxYTEgMSAwIDEgMCAwLTIgMSAxIDAgMCAwIDAgMiIgY2xpcC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPgo=)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-2315
 */
export const Icon24PasswordSmall = memo(function Icon24PasswordSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M7 9h10a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1m-2 1a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2zm7 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2m4-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-7 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2"
        clipRule="evenodd"
      />
    </svg>
  )
})
