// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.connector.elbow.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2LjUgNmEuNS41IDAgMCAxIDAgMWgtM0ExLjUgMS41IDAgMCAwIDEyIDguNXY3QTIuNSAyLjUgMCAwIDEgOS41IDE4aC0zYS41LjUgMCAwIDEgMC0xaDNhMS41IDEuNSAwIDAgMCAxLjUtMS41di03QTIuNSAyLjUgMCAwIDEgMTMuNSA2eiIvPjwvc3ZnPg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3640-104101
 */
export const Icon24ConnectorElbowSmall = memo(function Icon24ConnectorElbowSmall(
  props: SVGIconProps,
) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M16.5 6a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 0 12 8.5v7A2.5 2.5 0 0 1 9.5 18h-3a.5.5 0 0 1 0-1h3a1.5 1.5 0 0 0 1.5-1.5v-7A2.5 2.5 0 0 1 13.5 6z"
      />
    </svg>
  )
})
