// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.16.stroke.end.point.square
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDgiIGhlaWdodD0iNjQiIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA1MiAxNiI+CiAgPHJlY3Qgd2lkdGg9IjUyIiBoZWlnaHQ9IjE2IiBmaWxsPSIjMDAwIiByeD0iNCIvPgogIDxwYXRoIGZpbGw9IiNmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTAgMy41QS41LjUgMCAwIDEgLjUgM2g1MGEuNS41IDAgMCAxIC41LjV2OWEuNS41IDAgMCAxLS41LjVILjVhLjUuNSAwIDAgMSAwLTFINTBWNEguNWEuNS41IDAgMCAxLS41LS41IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-14299
 */
export const Icon16StrokeEndPointSquare = memo(function Icon16StrokeEndPointSquare(
  props: SVGIconProps,
) {
  return (
    <svg width="52" height="16" fill="none" viewBox="0 0 52 16" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M0 3.5A.5.5 0 0 1 .5 3h50a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1 0-1H50V4H.5a.5.5 0 0 1-.5-.5"
        clipRule="evenodd"
      />
    </svg>
  )
})
