// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.thumb.up.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOS44IDkuNzUyYy4xNzgtLjEwMy4zNi0uMjQuNTM2LS40MTYuNDctLjQ3LjY2NC0uOTg2LjY2NC0xLjMzNmEyIDIgMCAxIDEgNCAwcS0uMDAxLjUxMy0uMDk4IDFhNS42IDUuNiAwIDAgMS0uMjk3IDFoMi4xNzRhMiAyIDAgMCAxIDEuOTEgMi41OTdsLTEuMDU1IDMuMzczYTIuNSAyLjUgMCAwIDEtMi43NCAxLjczbC00Ljk3NS0uNzEyQTEuNSAxLjUgMCAwIDEgOC41IDE4aC0xQTEuNSAxLjUgMCAwIDEgNiAxNi41di02QTEuNSAxLjUgMCAwIDEgNy41IDloMWExLjUgMS41IDAgMCAxIDEuMy43NTJtLjIgMS4wMTl2NS4yMTlsNS4wMzYuNzJhMS41IDEuNSAwIDAgMCAxLjY0NC0xLjAzOGwxLjA1NC0zLjM3NEExIDEgMCAwIDAgMTYuNzggMTFoLTMuNjUybC41NDgtMS4zNzFBNC40IDQuNCAwIDAgMCAxNCA4YTEgMSAwIDEgMC0yIDBjMCAuNjcyLS4zNDUgMS40My0uOTU3IDIuMDQzQTMuNSAzLjUgMCAwIDEgMTAgMTAuNzdtLTEtLjI3YS41LjUgMCAwIDAtLjUtLjVoLTFhLjUuNSAwIDAgMC0uNS41djZhLjUuNSAwIDAgMCAuNS41aDFhLjUuNSAwIDAgMCAuNS0uNXoiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-10659
 */
export const Icon24ThumbUpSmall = memo(function Icon24ThumbUpSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M9.8 9.752c.178-.103.36-.24.536-.416.47-.47.664-.986.664-1.336a2 2 0 1 1 4 0q-.001.513-.098 1a5.6 5.6 0 0 1-.297 1h2.174a2 2 0 0 1 1.91 2.597l-1.055 3.373a2.5 2.5 0 0 1-2.74 1.73l-4.975-.712A1.5 1.5 0 0 1 8.5 18h-1A1.5 1.5 0 0 1 6 16.5v-6A1.5 1.5 0 0 1 7.5 9h1a1.5 1.5 0 0 1 1.3.752m.2 1.019v5.219l5.036.72a1.5 1.5 0 0 0 1.644-1.038l1.054-3.374A1 1 0 0 0 16.78 11h-3.652l.548-1.371A4.4 4.4 0 0 0 14 8a1 1 0 1 0-2 0c0 .672-.345 1.43-.957 2.043A3.5 3.5 0 0 1 10 10.77m-1-.27a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v6a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5z"
        clipRule="evenodd"
      />
    </svg>
  )
})
