// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.stroke-dynamic
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTIgMTFhMSAxIDAgMCAxIDEgMSAyIDIgMCAxIDAgNCAwIDEgMSAwIDAgMSAxLTFoLjVhLjUuNSAwIDAgMCAwLTFIMThhMiAyIDAgMCAwLTIgMiAxIDEgMCAxIDEtMiAwIDIgMiAwIDEgMC00IDAgMSAxIDAgMSAxLTIgMCAyIDIgMCAwIDAtMi0yaC0uNWEuNS41IDAgMCAwIDAgMUg2YTEgMSAwIDAgMSAxIDEgMiAyIDAgMSAwIDQgMCAxIDEgMCAwIDEgMS0xIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3633-8722
 */
export const Icon24StrokeDynamic = memo(function Icon24StrokeDynamic(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M12 11a1 1 0 0 1 1 1 2 2 0 1 0 4 0 1 1 0 0 1 1-1h.5a.5.5 0 0 0 0-1H18a2 2 0 0 0-2 2 1 1 0 1 1-2 0 2 2 0 1 0-4 0 1 1 0 1 1-2 0 2 2 0 0 0-2-2h-.5a.5.5 0 0 0 0 1H6a1 1 0 0 1 1 1 2 2 0 1 0 4 0 1 1 0 0 1 1-1"
        clipRule="evenodd"
      />
    </svg>
  )
})
