// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.connected-project
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMTkuODI0IDEzLjI5NEE1IDUgMCAxIDAgMTAuMDIgMTEuNWEuNTQuNTQgMCAwIDEtLjUyNi41LjQ3LjQ3IDAgMCAxLS40NzktLjVxLjA0NC0uNTI2LjE4NS0xLjA1NGE2IDYgMCAxIDEgNi4zIDcuNTMzLjQ3LjQ3IDAgMCAxLS41LS40OGMwLS4yNzUuMjI0LS40OTcuNS0uNTI0YTUgNSAwIDAgMCA0LjMyNS0zLjY4Mk04LjUgNi4wMmMuMjc1LS4wMjQuNS4yMDIuNS40NzlhLjU0LjU0IDAgMCAxLS40OTkuNTI1QTUgNSAwIDEgMCAxMy45OCAxMi41Yy4wMjgtLjI3NS4yNS0uNS41MjYtLjVzLjUwMi4yMjQuNDc5LjVhNi4wMDIgNi4wMDIgMCAwIDEtMTEuNzc2IDEuMDUzQTYgNiAwIDAgMSA4LjUgNi4wMjEiIGNsaXAtcnVsZT0iZXZlbm9kZCIvPgo8L3N2Zz4K)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=2319-32464
 */
export const Icon24ConnectedProject = memo(function Icon24ConnectedProject(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M19.824 13.294A5 5 0 1 0 10.02 11.5a.54.54 0 0 1-.526.5.47.47 0 0 1-.479-.5q.044-.526.185-1.054a6 6 0 1 1 6.3 7.533.47.47 0 0 1-.5-.48c0-.275.224-.497.5-.524a5 5 0 0 0 4.325-3.682M8.5 6.02c.275-.024.5.202.5.479a.54.54 0 0 1-.499.525A5 5 0 1 0 13.98 12.5c.028-.275.25-.5.526-.5s.502.224.479.5a6.002 6.002 0 0 1-11.776 1.053A6 6 0 0 1 8.5 6.021"
        clipRule="evenodd"
      />
    </svg>
  )
})
