// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'

/**
 * icon.24.shape.shield.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2LjUgNkExLjUgMS41IDAgMCAxIDE4IDcuNXY1LjA4NmEyIDIgMCAwIDEtLjQ1MyAxLjI2OGwtLjEzMy4xNDYtNC4zNTQgNC4zNTRhMS41IDEuNSAwIDAgMS0yLjAwNi4xMDJsLS4xMTQtLjEwMkw2LjU4NiAxNEEyIDIgMCAwIDEgNiAxMi41ODZWNy41QTEuNSAxLjUgMCAwIDEgNy41IDZ6bS05IDEtLjEuMDFhLjUuNSAwIDAgMC0uNC40OXY1LjA4NmwuMDA1LjA5OWExIDEgMCAwIDAgLjI4OC42MDhsNC4zNTMgNC4zNTRhLjUuNSAwIDAgMCAuNjMuMDY0bC4wNzgtLjA2NCA0LjM1My00LjM1NGExIDEgMCAwIDAgLjI4OC0uNjA4bC4wMDUtLjFWNy41YS41LjUgMCAwIDAtLjQtLjQ5TDE2LjUgN3oiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=3613-7936
 */
export const Icon24ShapeShieldSmall = memo(function Icon24ShapeShieldSmall(props: SVGIconProps) {
  return (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        d="M16.5 6A1.5 1.5 0 0 1 18 7.5v5.086a2 2 0 0 1-.453 1.268l-.133.146-4.354 4.354a1.5 1.5 0 0 1-2.006.102l-.114-.102L6.586 14A2 2 0 0 1 6 12.586V7.5A1.5 1.5 0 0 1 7.5 6zm-9 1-.1.01a.5.5 0 0 0-.4.49v5.086l.005.099a1 1 0 0 0 .288.608l4.353 4.354a.5.5 0 0 0 .63.064l.078-.064 4.353-4.354a1 1 0 0 0 .288-.608l.005-.1V7.5a.5.5 0 0 0-.4-.49L16.5 7z"
      />
    </svg>
  )
})
