// This file was auto-generated by fpl/foundations/figma-import

import { memo } from 'react'

import type { SVGIconProps } from './support/icon-types'
import { useIs2xResolution } from './support/use-is-2x-resolution'

/**
 * icon.24.edit.mode.small
 *
 * ![](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICA8cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiMwMDAiIHJ4PSI0Ii8+CiAgPHBhdGggZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNOCA5YTEgMSAwIDEgMSAwLTIgMSAxIDAgMCAxIDAgMm0uNS45MzdBMiAyIDAgMCAwIDkuOTM3IDguNWg0LjEyNmMuMTguNzAzLjczNCAxLjI1NiAxLjQzNyAxLjQzN3Y0LjEyNmEyIDIgMCAwIDAtMS40MzcgMS40MzdIOS45MzdBMiAyIDAgMCAwIDguNSAxNC4wNjN6bTggNC4xMjZhMiAyIDAgMSAxLTIuNDM3IDIuNDM3SDkuOTM3QTIgMiAwIDEgMSA3LjUgMTQuMDYzVjkuOTM3QTIgMiAwIDEgMSA5LjkzNyA3LjVoNC4xMjZBMiAyIDAgMSAxIDE2LjUgOS45Mzd6TTE2IDE1YTEgMSAwIDEgMCAwIDIgMSAxIDAgMCAwIDAtMm0wLTZhMSAxIDAgMSAwIDAtMiAxIDEgMCAwIDAgMCAybS04IDZhMSAxIDAgMSAxIDAgMiAxIDEgMCAwIDEgMC0yIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==)
 *
 * https://staging.figma.com/file/ycDPAaAih2bZY5LgXehVai/?node-id=1-3219
 */
export const Icon24EditModeSmall = memo(function Icon24EditModeSmall(props: SVGIconProps) {
  const is2x = useIs2xResolution()

  const icon = is2x ? (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 9a1 1 0 1 1 0-2 1 1 0 0 1 0 2m.5.937A2 2 0 0 0 9.937 8.5h4.126c.18.703.734 1.256 1.437 1.437v4.126a2 2 0 0 0-1.437 1.437H9.937A2 2 0 0 0 8.5 14.063zm8 4.126a2 2 0 1 1-2.437 2.437H9.937A2 2 0 1 1 7.5 14.063V9.937A2 2 0 1 1 9.937 7.5h4.126A2 2 0 1 1 16.5 9.937zM16 15a1 1 0 1 0 0 2 1 1 0 0 0 0-2m0-6a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-8 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2"
        clipRule="evenodd"
      />
    </svg>
  ) : (
    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" {...props}>
      <path
        fill="var(--color-icon)"
        fillRule="evenodd"
        d="M8 9a1 1 0 1 1 0-2 1 1 0 0 1 0 2m1 .732A2 2 0 0 0 9.732 9h4.536c.175.304.428.557.732.732v4.536a2 2 0 0 0-.732.732H9.732A2 2 0 0 0 9 14.268zM16 14a2 2 0 1 1-2 2h-4a2 2 0 1 1-2-2v-4a2 2 0 1 1 2-2h4a2 2 0 1 1 2 2zm0-5a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-8 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"
        clipRule="evenodd"
      />
    </svg>
  )

  return icon
})
